{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1366038,
          "sha512": "7d509d14f4c183c7ef8eb65c76559539ede4cad1a5459760f1b276b6f1b1732c4bf664459f00530632ccd18d2ceb54e29f8cf29ecef8c63d55575779950b28fe",
          "sha256": "2a37ee1a3a630b5924349b88884709889a457dde463a3962b844b032cd968859",
          "sha1": "a803ac99a4869675c246c1ecaed1f6e60ca8ce8b",
          "md5": "a6a5d6753971c07f975dd5fb15ffce7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1366038,
          "sha512": "7d509d14f4c183c7ef8eb65c76559539ede4cad1a5459760f1b276b6f1b1732c4bf664459f00530632ccd18d2ceb54e29f8cf29ecef8c63d55575779950b28fe",
          "sha256": "2a37ee1a3a630b5924349b88884709889a457dde463a3962b844b032cd968859",
          "sha1": "a803ac99a4869675c246c1ecaed1f6e60ca8ce8b",
          "md5": "a6a5d6753971c07f975dd5fb15ffce7b"
        }
      ]
    }
  ]
}
