{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "deobfuscator",
    "version": "4.31.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "deobfuscator-4.31.2.jar",
          "url": "deobfuscator-4.31.2.jar",
          "size": 557261,
          "sha512": "652b6d4702ac475a6c2743c74370c90f548092f5b2b7db350a435e658bfed2519fafbbef3832063ecacfe09e05726a5b5f85196fbbbca51ae9de3cbd14a4db47",
          "sha256": "e71b32c591b853560b8b062bc18756162d7abaf9ad3d328fe4947f4423e3215e",
          "sha1": "1dddadf8d67be07e4dc9cb8d531737d99c76088a",
          "md5": "2d5738fe34a9f122ef06321bcf9d575d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.31.2"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "fernflower",
          "version": {
            "requires": "07082019"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "deobfuscator-4.31.2.jar",
          "url": "deobfuscator-4.31.2.jar",
          "size": 557261,
          "sha512": "652b6d4702ac475a6c2743c74370c90f548092f5b2b7db350a435e658bfed2519fafbbef3832063ecacfe09e05726a5b5f85196fbbbca51ae9de3cbd14a4db47",
          "sha256": "e71b32c591b853560b8b062bc18756162d7abaf9ad3d328fe4947f4423e3215e",
          "sha1": "1dddadf8d67be07e4dc9cb8d531737d99c76088a",
          "md5": "2d5738fe34a9f122ef06321bcf9d575d"
        }
      ]
    }
  ]
}
