{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 122320,
          "sha512": "1101e4de977aa14817d6702e7ecb537836480a18d89e3418c131ba0c86cf0dbe301a1583672abe9a31ac577df3cb3053627ec99f57db41b1312d6fea7846ac92",
          "sha256": "22190e74e3737eefdaf0968889be82e3f086abb0b60493129e4feff54602c72a",
          "sha1": "d4add573a3c727ab187ca7e83839ec3b724df9f8",
          "md5": "715a66df42fd15099b1ae16879b164b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0.jar",
          "url": "runescape-api-4.28.0.jar",
          "size": 122320,
          "sha512": "1101e4de977aa14817d6702e7ecb537836480a18d89e3418c131ba0c86cf0dbe301a1583672abe9a31ac577df3cb3053627ec99f57db41b1312d6fea7846ac92",
          "sha256": "22190e74e3737eefdaf0968889be82e3f086abb0b60493129e4feff54602c72a",
          "sha1": "d4add573a3c727ab187ca7e83839ec3b724df9f8",
          "md5": "715a66df42fd15099b1ae16879b164b1"
        }
      ]
    }
  ]
}
