{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.4-SNAPSHOT.jar",
          "url": "runelite-api-1.0.4-SNAPSHOT.jar",
          "size": 1377570,
          "sha512": "687b60d5cdb6bb1a40482e01249565eec8bdfe04e74605a88d843f9143653baa1482bd73226998ad148783d8076fb31274d664b40e32fb8f37a45cec3d8b1151",
          "sha256": "1a42c374db3643172e9820ad6ae47c46c60e82a88379da6da6e4514bf5824062",
          "sha1": "7e45523bdb5af7cd787e9f70442ecf6f1d84b884",
          "md5": "1c8b88e9de7580989e632cf1fa5791f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.4-SNAPSHOT.jar",
          "url": "runelite-api-1.0.4-SNAPSHOT.jar",
          "size": 1377570,
          "sha512": "687b60d5cdb6bb1a40482e01249565eec8bdfe04e74605a88d843f9143653baa1482bd73226998ad148783d8076fb31274d664b40e32fb8f37a45cec3d8b1151",
          "sha256": "1a42c374db3643172e9820ad6ae47c46c60e82a88379da6da6e4514bf5824062",
          "sha1": "7e45523bdb5af7cd787e9f70442ecf6f1d84b884",
          "md5": "1c8b88e9de7580989e632cf1fa5791f6"
        }
      ]
    }
  ]
}
