{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.4-SNAPSHOT.jar",
          "url": "runelite-api-1.0.4-SNAPSHOT.jar",
          "size": 1377572,
          "sha512": "886ebaeb6ca4967a478451c3e038ac878a19949704f517d118d64995d82e7778ea6d54f22b84c0f609eb09d35c6b4c1ff2f6ed524fa43b68dc3fef71180ccefa",
          "sha256": "c05c66ca234813a25df8dd6756077365817e19629ff372fea1269103f5ad0d02",
          "sha1": "8e66e086c9d232c5676cf6e71e6f74146b1f67b3",
          "md5": "cccd6ed4c83600e5f8bd5aeaec789a7d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.4-SNAPSHOT.jar",
          "url": "runelite-api-1.0.4-SNAPSHOT.jar",
          "size": 1377572,
          "sha512": "886ebaeb6ca4967a478451c3e038ac878a19949704f517d118d64995d82e7778ea6d54f22b84c0f609eb09d35c6b4c1ff2f6ed524fa43b68dc3fef71180ccefa",
          "sha256": "c05c66ca234813a25df8dd6756077365817e19629ff372fea1269103f5ad0d02",
          "sha1": "8e66e086c9d232c5676cf6e71e6f74146b1f67b3",
          "md5": "cccd6ed4c83600e5f8bd5aeaec789a7d"
        }
      ]
    }
  ]
}
