{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.4-SNAPSHOT.jar",
          "url": "runelite-api-1.0.4-SNAPSHOT.jar",
          "size": 1377551,
          "sha512": "cd37cfea10e26f08d6f9df2c9df10fe459e0c891aae5b3b4add01285ae93603060e7c4142f94f1670cf1dde82dde8aaf9ae987f13e01be9d6f866d2f824026b5",
          "sha256": "04032217ad69551f1bd581be0229e2b1532d399421daa93448d592b639e459f0",
          "sha1": "94628da4a4bcf13ebb0059c8b2cfbf3353d5610a",
          "md5": "20a9126bed2d583afe28fcac0269b931"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.4-SNAPSHOT.jar",
          "url": "runelite-api-1.0.4-SNAPSHOT.jar",
          "size": 1377551,
          "sha512": "cd37cfea10e26f08d6f9df2c9df10fe459e0c891aae5b3b4add01285ae93603060e7c4142f94f1670cf1dde82dde8aaf9ae987f13e01be9d6f866d2f824026b5",
          "sha256": "04032217ad69551f1bd581be0229e2b1532d399421daa93448d592b639e459f0",
          "sha1": "94628da4a4bcf13ebb0059c8b2cfbf3353d5610a",
          "md5": "20a9126bed2d583afe28fcac0269b931"
        }
      ]
    }
  ]
}
