{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.4-SNAPSHOT.jar",
          "url": "runelite-api-1.0.4-SNAPSHOT.jar",
          "size": 1377503,
          "sha512": "e5e0e6345c46493d0a90634b051de8b6c1268762593baf0075d5850c23d1d39f605d8f886b52ca088eb461f462175e5b5908fd4ce59fbfa7f9685e6e8125eb14",
          "sha256": "58203ebec81a40589def82ed9b0b6ffb02ba0754c566a82f57949b9a5a154819",
          "sha1": "3bd2efe9b876a970335a1a2c033488da88213f6a",
          "md5": "5ef56fd5d2595f93496d0768f5e1b5e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.4-SNAPSHOT.jar",
          "url": "runelite-api-1.0.4-SNAPSHOT.jar",
          "size": 1377503,
          "sha512": "e5e0e6345c46493d0a90634b051de8b6c1268762593baf0075d5850c23d1d39f605d8f886b52ca088eb461f462175e5b5908fd4ce59fbfa7f9685e6e8125eb14",
          "sha256": "58203ebec81a40589def82ed9b0b6ffb02ba0754c566a82f57949b9a5a154819",
          "sha1": "3bd2efe9b876a970335a1a2c033488da88213f6a",
          "md5": "5ef56fd5d2595f93496d0768f5e1b5e4"
        }
      ]
    }
  ]
}
