{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88796,
          "sha512": "a829821d9d628ca6831cf4b1945894f3f707a5b3df384eb1efc1e549f2ecc9124c56e7336ebb6208435bd8875af74164da9525beafb5fd94d9b7a0e56adfe7d4",
          "sha256": "f010aae828fa077d4bab2fd9d0821fe88b302cc273b49322c8ef4de6089536f2",
          "sha1": "412c0ff99d83f20b5d9e6db6559b60a6cbb8a94e",
          "md5": "bf19895c7be20b8f1adf8f34480d9306"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88796,
          "sha512": "a829821d9d628ca6831cf4b1945894f3f707a5b3df384eb1efc1e549f2ecc9124c56e7336ebb6208435bd8875af74164da9525beafb5fd94d9b7a0e56adfe7d4",
          "sha256": "f010aae828fa077d4bab2fd9d0821fe88b302cc273b49322c8ef4de6089536f2",
          "sha1": "412c0ff99d83f20b5d9e6db6559b60a6cbb8a94e",
          "md5": "bf19895c7be20b8f1adf8f34480d9306"
        }
      ]
    }
  ]
}
