{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88794,
          "sha512": "a8bce10cbcd9de9273ed00f818f35c7d1494f50d19a1c6e39a73f86d4b0c1e83b732a959784b2e182cbad243c00b4631245165033c56bb2fcffae0b09842e732",
          "sha256": "f9aef0ff73abad220347ef062fa8e9d7f33c85de571b4b91abd452acdb986256",
          "sha1": "06c4dbd710cffc122ead9eb87e948678392ed11e",
          "md5": "01ab0de91e3f505a3e6b855deda56961"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88794,
          "sha512": "a8bce10cbcd9de9273ed00f818f35c7d1494f50d19a1c6e39a73f86d4b0c1e83b732a959784b2e182cbad243c00b4631245165033c56bb2fcffae0b09842e732",
          "sha256": "f9aef0ff73abad220347ef062fa8e9d7f33c85de571b4b91abd452acdb986256",
          "sha1": "06c4dbd710cffc122ead9eb87e948678392ed11e",
          "md5": "01ab0de91e3f505a3e6b855deda56961"
        }
      ]
    }
  ]
}
