{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8.jar",
          "url": "http-api-1.0.8.jar",
          "size": 91329,
          "sha512": "916b337b9f7c85d5444da8e673834fa79fe489a5d20edaccb9a4c4bd484657e7f1384415e264606d0a813a1575f5f132ab14c42f70edece1882716851e159a08",
          "sha256": "9733d33de85200e0c51d3a944f62bc4183f123f9941141adb7fb6a73a697142a",
          "sha1": "90aea750da8f1e54d9bb4569a07038bb99b2aeb3",
          "md5": "7e1f1878e9af321cd967c88488f65884"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8.jar",
          "url": "http-api-1.0.8.jar",
          "size": 91329,
          "sha512": "916b337b9f7c85d5444da8e673834fa79fe489a5d20edaccb9a4c4bd484657e7f1384415e264606d0a813a1575f5f132ab14c42f70edece1882716851e159a08",
          "sha256": "9733d33de85200e0c51d3a944f62bc4183f123f9941141adb7fb6a73a697142a",
          "sha1": "90aea750da8f1e54d9bb4569a07038bb99b2aeb3",
          "md5": "7e1f1878e9af321cd967c88488f65884"
        }
      ]
    }
  ]
}
