{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8.jar",
          "url": "http-api-1.0.8.jar",
          "size": 91329,
          "sha512": "ac7e4603aee864cc630a832c0ef7ce49b5b0ec1fb47dcdf93f16778aabd597d64f4476f1d2a22739ec8a3ecdecd4482a547e407f8f32d3464264cc3b60220b75",
          "sha256": "3f55d2b37b3fbae8648322000f277fc39ace22188d2831db98a6806259363278",
          "sha1": "8e1da04b2b44ad6f280587bba00566e96751414b",
          "md5": "93d27d2d1751d99e033db94feb3fa376"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8.jar",
          "url": "http-api-1.0.8.jar",
          "size": 91329,
          "sha512": "ac7e4603aee864cc630a832c0ef7ce49b5b0ec1fb47dcdf93f16778aabd597d64f4476f1d2a22739ec8a3ecdecd4482a547e407f8f32d3464264cc3b60220b75",
          "sha256": "3f55d2b37b3fbae8648322000f277fc39ace22188d2831db98a6806259363278",
          "sha1": "8e1da04b2b44ad6f280587bba00566e96751414b",
          "md5": "93d27d2d1751d99e033db94feb3fa376"
        }
      ]
    }
  ]
}
