{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8.jar",
          "url": "http-api-1.0.8.jar",
          "size": 91329,
          "sha512": "83075efcc2550add2459dbb10bb5741edf4997297f9d8783f80db7e1aee1627cc35b9ab6990b260acdce5497dbdb98faa320ae4bd1feadff3760b2240eef4a00",
          "sha256": "289440f1070d8037cdb99d54af2d57fc82c4d0d6c7ea801aa5d362f74839e546",
          "sha1": "1755e8690e744998a058aeadb58880cdec4b7607",
          "md5": "31cfedb9e34653ea2ce3175e4003783c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8.jar",
          "url": "http-api-1.0.8.jar",
          "size": 91329,
          "sha512": "83075efcc2550add2459dbb10bb5741edf4997297f9d8783f80db7e1aee1627cc35b9ab6990b260acdce5497dbdb98faa320ae4bd1feadff3760b2240eef4a00",
          "sha256": "289440f1070d8037cdb99d54af2d57fc82c4d0d6c7ea801aa5d362f74839e546",
          "sha1": "1755e8690e744998a058aeadb58880cdec4b7607",
          "md5": "31cfedb9e34653ea2ce3175e4003783c"
        }
      ]
    }
  ]
}
