{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.0.jar",
          "url": "http-api-1.0.0.jar",
          "size": 88795,
          "sha512": "a039dc04b01a6a3a20c563a39f7c09f95624a6c64b5b07ce0908a4295966143e60f53f28b81d1d73fabc776a5cb3d24e3dbce0a4a138a85a4678b05e85da931c",
          "sha256": "5738c22dd3c6426641a1b9bd15aba48649935138c9e328c12af9bfcf62b1573a",
          "sha1": "30e81128a6bcaed6fba191fdde3b089ca147eec3",
          "md5": "9f0b0fda8b98a6c5c80d2633095ede33"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.0.jar",
          "url": "http-api-1.0.0.jar",
          "size": 88795,
          "sha512": "a039dc04b01a6a3a20c563a39f7c09f95624a6c64b5b07ce0908a4295966143e60f53f28b81d1d73fabc776a5cb3d24e3dbce0a4a138a85a4678b05e85da931c",
          "sha256": "5738c22dd3c6426641a1b9bd15aba48649935138c9e328c12af9bfcf62b1573a",
          "sha1": "30e81128a6bcaed6fba191fdde3b089ca147eec3",
          "md5": "9f0b0fda8b98a6c5c80d2633095ede33"
        }
      ]
    }
  ]
}
