{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.0.jar",
          "url": "http-api-1.0.0.jar",
          "size": 88794,
          "sha512": "d6f1c074c3e9c9a2053109e290d1a7db8e3f037cc2b2939bd1b0ea118ec16c8631cc9526c372f52154edf9c3a7167b957095e43f112bb15e8f73ba258e0112ff",
          "sha256": "656adcea05f7a18afa088f5e00f3137df96a4c5c2c888ba375a56d8ebc3c405e",
          "sha1": "60d4091f2234e689e7ff40aa5e1e259f5ecb9d12",
          "md5": "d710a015e0e7426e92ede5597b751e18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.0.jar",
          "url": "http-api-1.0.0.jar",
          "size": 88794,
          "sha512": "d6f1c074c3e9c9a2053109e290d1a7db8e3f037cc2b2939bd1b0ea118ec16c8631cc9526c372f52154edf9c3a7167b957095e43f112bb15e8f73ba258e0112ff",
          "sha256": "656adcea05f7a18afa088f5e00f3137df96a4c5c2c888ba375a56d8ebc3c405e",
          "sha1": "60d4091f2234e689e7ff40aa5e1e259f5ecb9d12",
          "md5": "d710a015e0e7426e92ede5597b751e18"
        }
      ]
    }
  ]
}
