{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.1.jar",
          "url": "http-api-1.0.1.jar",
          "size": 88794,
          "sha512": "10ce66d238cd9e54eefcfe47b178c8316b1080963b22fa45fedeb6209f190c240eb40436ba5213e58f989e12ee0f96abae6e2cd24854430813441041f403a596",
          "sha256": "98dae2a1a0cd886ae22def71265468102a810ae8e50fc694e4098efbd5cc9d84",
          "sha1": "7a3faa5ca0dfd96e14f28d0767bc83c4c2dc5b88",
          "md5": "5cc19e76bf1273b299bfe7f7da1f35ba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.1.jar",
          "url": "http-api-1.0.1.jar",
          "size": 88794,
          "sha512": "10ce66d238cd9e54eefcfe47b178c8316b1080963b22fa45fedeb6209f190c240eb40436ba5213e58f989e12ee0f96abae6e2cd24854430813441041f403a596",
          "sha256": "98dae2a1a0cd886ae22def71265468102a810ae8e50fc694e4098efbd5cc9d84",
          "sha1": "7a3faa5ca0dfd96e14f28d0767bc83c4c2dc5b88",
          "md5": "5cc19e76bf1273b299bfe7f7da1f35ba"
        }
      ]
    }
  ]
}
