{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4.jar",
          "url": "http-api-1.0.4.jar",
          "size": 85931,
          "sha512": "27e760f5b71b8dd1a522a190723cfde9feab600ab5468722173679980cc20322b61864e1084b900ec450bc172d6dfca36b23d0f94adee471c462c8befd60621d",
          "sha256": "943bad8bf83e89876baa9cbc3e1af9ab32e187d7827a6d77172bbd6ec34b1bb1",
          "sha1": "a43af78098bcb000adb006344c2b9c27b7b23171",
          "md5": "bd280d6ff1c66cb2ab0fb7e7902d4d91"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4.jar",
          "url": "http-api-1.0.4.jar",
          "size": 85931,
          "sha512": "27e760f5b71b8dd1a522a190723cfde9feab600ab5468722173679980cc20322b61864e1084b900ec450bc172d6dfca36b23d0f94adee471c462c8befd60621d",
          "sha256": "943bad8bf83e89876baa9cbc3e1af9ab32e187d7827a6d77172bbd6ec34b1bb1",
          "sha1": "a43af78098bcb000adb006344c2b9c27b7b23171",
          "md5": "bd280d6ff1c66cb2ab0fb7e7902d4d91"
        }
      ]
    }
  ]
}
