{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-client",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-4.32.0-SNAPSHOT.jar",
          "url": "runelite-client-4.32.0-SNAPSHOT.jar",
          "size": 11493033,
          "sha512": "e52e2a0bce952a484d28f8968c2208c2cdc05ab71646c841c7f72655cb2feb6c6580f4594d22a18b32be0c54419f76c08c607c5f38250febbb80796679b835ba",
          "sha256": "ed43a678ab78e9c62880adbd86964c4efa9664c829145c14067327fe7dfe3e43",
          "sha1": "4133e144f0e5833014bbfae16f8fd7f7993ff92f",
          "md5": "1594f36f159f51e0f2679a529a3126fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-jshell",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.21.1"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "5.2.2.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "substance",
          "version": {
            "requires": "8.0.02"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.madlonkay",
          "module": "desktopsupport",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-gldesktop-dbg",
          "version": {
            "requires": "2.4.0-rc-20220318"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.miglayout",
          "module": "miglayout",
          "version": {
            "requires": "3.7.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jboss.aerogear",
          "module": "aerogear-otp-java",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "engine.io-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.kwhat",
          "module": "jnativehook",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "trident",
          "version": {
            "requires": "1.5.00"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "gluegen-rt",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macosx-universal"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-rl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-rl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-amd64"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-rl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-i586"
            }
          }
        },
        {
          "group": "net.runelite.jogl",
          "module": "jogl-rl",
          "version": {
            "requires": "2.4.0-rc-20220318"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jogl-rl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macosx-universal"
            }
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-x64"
            }
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-arm64"
            }
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-4.32.0-SNAPSHOT.jar",
          "url": "runelite-client-4.32.0-SNAPSHOT.jar",
          "size": 11493033,
          "sha512": "e52e2a0bce952a484d28f8968c2208c2cdc05ab71646c841c7f72655cb2feb6c6580f4594d22a18b32be0c54419f76c08c607c5f38250febbb80796679b835ba",
          "sha256": "ed43a678ab78e9c62880adbd86964c4efa9664c829145c14067327fe7dfe3e43",
          "sha1": "4133e144f0e5833014bbfae16f8fd7f7993ff92f",
          "md5": "1594f36f159f51e0f2679a529a3126fc"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-4.32.0-SNAPSHOT-shaded.jar",
          "url": "runelite-client-4.32.0-SNAPSHOT-shaded.jar",
          "size": 38621296,
          "sha512": "08f2e4e167f13c039b520d2c96a812972659cb428de80c9ff11cc6a399ea2381e5e2159a330bfc6ae7690362f4a1ee6bc2e7dbc7bfe316b5067fb838630e8670",
          "sha256": "a451f06519750d58d6d19f9cae6c69b6b61ede9bf7b8ec529aa40828bf9ad2a3",
          "sha1": "5f2103a2698395810b894ad805ffe3eaff56026f",
          "md5": "cd22c4e8ae09408a1b424c9d00c73c80"
        }
      ]
    }
  ]
}
