{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.2.jar",
          "url": "injector-plugin-2.0.2.jar",
          "size": 121807,
          "sha512": "6a0c043ad3f7d26f58acf6c8fd65e920e4800aa250cc560e162a590b98530bc105e7a7f47b8bb7b48a3dbd5b8fa62587b343b365474285ecc9a04722ef6c3412",
          "sha256": "5c4e1006aeae8827483f6b40bad51cc0d2c97afd7e0d87748514536fc0162bf3",
          "sha1": "6676eac9c4d928b2dfef7a663292ecdefa71185a",
          "md5": "b329801a282c51cddd8cfc5207e0b097"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.2.jar",
          "url": "injector-plugin-2.0.2.jar",
          "size": 121807,
          "sha512": "6a0c043ad3f7d26f58acf6c8fd65e920e4800aa250cc560e162a590b98530bc105e7a7f47b8bb7b48a3dbd5b8fa62587b343b365474285ecc9a04722ef6c3412",
          "sha256": "5c4e1006aeae8827483f6b40bad51cc0d2c97afd7e0d87748514536fc0162bf3",
          "sha1": "6676eac9c4d928b2dfef7a663292ecdefa71185a",
          "md5": "b329801a282c51cddd8cfc5207e0b097"
        }
      ]
    }
  ]
}
