{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "6ebfa57ad73b0e6c154c9ec2dbe555a636ca51d02789ced00906bc75e681c2708663624f54f902190e05de1d9505bbe7b1dd34b4618a2aca117cf982c296858d",
          "sha256": "3e94ba59ea07181ccfcf9639c3c080fae69b5db8111389681ef1236d03453f6b",
          "sha1": "b8688068191345ea15ccf961d72fd5c6d5d11e8f",
          "md5": "ea156579af3a915b951131ed5b458305"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "6ebfa57ad73b0e6c154c9ec2dbe555a636ca51d02789ced00906bc75e681c2708663624f54f902190e05de1d9505bbe7b1dd34b4618a2aca117cf982c296858d",
          "sha256": "3e94ba59ea07181ccfcf9639c3c080fae69b5db8111389681ef1236d03453f6b",
          "sha1": "b8688068191345ea15ccf961d72fd5c6d5d11e8f",
          "md5": "ea156579af3a915b951131ed5b458305"
        }
      ]
    }
  ]
}
