{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "8443b9233daccec33328d868dfaa58389338f428bc6132672efcbcbf14cbc4dcc6eb38f4a1d8e163db5e36318d54b1213b8cd6434b32f01c301fe31e0bb2b01e",
          "sha256": "f28f4ccb4559992c83dcc4d9fa25f7dfbf2b90feff9644215437a79eec30a226",
          "sha1": "4be58c7e6fa230ff67fbee5b63d72f31db33ee9f",
          "md5": "f21e29b891d80ef202fb565609ea8013"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "8443b9233daccec33328d868dfaa58389338f428bc6132672efcbcbf14cbc4dcc6eb38f4a1d8e163db5e36318d54b1213b8cd6434b32f01c301fe31e0bb2b01e",
          "sha256": "f28f4ccb4559992c83dcc4d9fa25f7dfbf2b90feff9644215437a79eec30a226",
          "sha1": "4be58c7e6fa230ff67fbee5b63d72f31db33ee9f",
          "md5": "f21e29b891d80ef202fb565609ea8013"
        }
      ]
    }
  ]
}
