{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "16aaeeadeb000b85350974b38033b737ad8dd16cfb4dbc371fd3bcd32ce05846a5122b9d2a11f761649c9657365ea3ffc8bbdc493ad3bc50013e95b5dbf0ee9c",
          "sha256": "451e35d7c61c888e4e2114587ebdc95eccf6c245f8ccf022f40aceea4a8f14b5",
          "sha1": "4d881869c6728caab97e5dbaba3d466ee042f0cb",
          "md5": "cd59216415cbd7c6311c1a7129ece865"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "16aaeeadeb000b85350974b38033b737ad8dd16cfb4dbc371fd3bcd32ce05846a5122b9d2a11f761649c9657365ea3ffc8bbdc493ad3bc50013e95b5dbf0ee9c",
          "sha256": "451e35d7c61c888e4e2114587ebdc95eccf6c245f8ccf022f40aceea4a8f14b5",
          "sha1": "4d881869c6728caab97e5dbaba3d466ee042f0cb",
          "md5": "cd59216415cbd7c6311c1a7129ece865"
        }
      ]
    }
  ]
}
