{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "8c4a9f19d015878f5d4137f9b4399761d730c55aea6f913fd969b565befc2d7d4ea31fc1155c78e8baf6db5b5c6da86aeb21b7f05ef82c338c6eeab111405df3",
          "sha256": "7a506a7a6e01055bb5232b845587bb35ddfd3dfc53bb8f36997d20e1ee8dbeac",
          "sha1": "fe04d54dcc2d016e8070607b9966b91ad739e9ba",
          "md5": "23e33ac116498a021bf7f0cc5021f832"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "8c4a9f19d015878f5d4137f9b4399761d730c55aea6f913fd969b565befc2d7d4ea31fc1155c78e8baf6db5b5c6da86aeb21b7f05ef82c338c6eeab111405df3",
          "sha256": "7a506a7a6e01055bb5232b845587bb35ddfd3dfc53bb8f36997d20e1ee8dbeac",
          "sha1": "fe04d54dcc2d016e8070607b9966b91ad739e9ba",
          "md5": "23e33ac116498a021bf7f0cc5021f832"
        }
      ]
    }
  ]
}
