{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "583b85e16e40d3232bc13334d082381318a3c8cb1226793686085910875367df2f1d809deaa97185a2e39217ddee9e806027263b05fa1d68808df8884a86292e",
          "sha256": "0bd2fe24ff190bfe8c3ad5c1d04a7060a424e2cb0d361c7f2f4477fefbc1d0b4",
          "sha1": "d6164d0b19c527b407e3aca59733bd37f4b468f5",
          "md5": "3f861b34426e7f824ffdbb2c06f2e643"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "583b85e16e40d3232bc13334d082381318a3c8cb1226793686085910875367df2f1d809deaa97185a2e39217ddee9e806027263b05fa1d68808df8884a86292e",
          "sha256": "0bd2fe24ff190bfe8c3ad5c1d04a7060a424e2cb0d361c7f2f4477fefbc1d0b4",
          "sha1": "d6164d0b19c527b407e3aca59733bd37f4b468f5",
          "md5": "3f861b34426e7f824ffdbb2c06f2e643"
        }
      ]
    }
  ]
}
