{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "77d06e989ba554cca81c3cf4fcdb70afe3b2831360a8f8ab8d93c0c6b75f9bd4400cb3043f01af17ebfb75ea4115cd335eb53bb6b921a2273dba69edf9cc06f2",
          "sha256": "762c3400d2828b85d5eda565d13aab2262ad1b8f7a6ae66503e67beb214e6b26",
          "sha1": "f63308eae0ef22912a68b08ad503bbf7387a8ab8",
          "md5": "ba6eda59034b6d144fa7aa5786e92650"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "77d06e989ba554cca81c3cf4fcdb70afe3b2831360a8f8ab8d93c0c6b75f9bd4400cb3043f01af17ebfb75ea4115cd335eb53bb6b921a2273dba69edf9cc06f2",
          "sha256": "762c3400d2828b85d5eda565d13aab2262ad1b8f7a6ae66503e67beb214e6b26",
          "sha1": "f63308eae0ef22912a68b08ad503bbf7387a8ab8",
          "md5": "ba6eda59034b6d144fa7aa5786e92650"
        }
      ]
    }
  ]
}
