{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "b32744874bae9f529b27cb9b3b477b1099619c88ca45734d80f3b3f19c8d54c66185c461e8ba8361772a17ce4634829f9af6aa92636f4a9c71953111b4800bae",
          "sha256": "c77f6cc50c37f9ef226f6e7601dc7f29683d28e3577236410103ecb67db5f575",
          "sha1": "4ef96b2d7b4913b57ac346fea82d171eae62e2a4",
          "md5": "d222305dbb0986e74edbf6950c0c0d9a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "b32744874bae9f529b27cb9b3b477b1099619c88ca45734d80f3b3f19c8d54c66185c461e8ba8361772a17ce4634829f9af6aa92636f4a9c71953111b4800bae",
          "sha256": "c77f6cc50c37f9ef226f6e7601dc7f29683d28e3577236410103ecb67db5f575",
          "sha1": "4ef96b2d7b4913b57ac346fea82d171eae62e2a4",
          "md5": "d222305dbb0986e74edbf6950c0c0d9a"
        }
      ]
    }
  ]
}
