{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "0707e013311f26bf0efc6bb7b58645f205d66728b5244a200ffc7addc4960f44f09f8d8ca99c2a89d38003282b71a55aad4cfccb06e69dbb36315e35fdbab08b",
          "sha256": "f705b80bc9a08588669393e7311b77e8b3a1289964b2e77d19b219937d636c6e",
          "sha1": "b9b88ecc569643979cc527fc0c2f893513facfa2",
          "md5": "36e7ee51c1d709457c734043c8333796"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "0707e013311f26bf0efc6bb7b58645f205d66728b5244a200ffc7addc4960f44f09f8d8ca99c2a89d38003282b71a55aad4cfccb06e69dbb36315e35fdbab08b",
          "sha256": "f705b80bc9a08588669393e7311b77e8b3a1289964b2e77d19b219937d636c6e",
          "sha1": "b9b88ecc569643979cc527fc0c2f893513facfa2",
          "md5": "36e7ee51c1d709457c734043c8333796"
        }
      ]
    }
  ]
}
