{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "7b1cdf2588dfe0bfbb8dd180fdf0e8cfee1edf0800f0839dd040ee35aa3b1754c35a3af6d40bed87cd9747625be140666dc30a02d374cd3e3b51ec7a6647e5e1",
          "sha256": "0388bbde274688bab5b88ecfc90ac6b3edd909ba62814af78e1e087da2b95027",
          "sha1": "8d65a2adbe83d1a46c0091a7c7105cc6ce5a2a17",
          "md5": "ce4036166c0347a9660e51db497ae9eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "7b1cdf2588dfe0bfbb8dd180fdf0e8cfee1edf0800f0839dd040ee35aa3b1754c35a3af6d40bed87cd9747625be140666dc30a02d374cd3e3b51ec7a6647e5e1",
          "sha256": "0388bbde274688bab5b88ecfc90ac6b3edd909ba62814af78e1e087da2b95027",
          "sha1": "8d65a2adbe83d1a46c0091a7c7105cc6ce5a2a17",
          "md5": "ce4036166c0347a9660e51db497ae9eb"
        }
      ]
    }
  ]
}
