{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "700d58638751a4d0be63d1d71008edff117774a5915b7603de01ec87aafe6bd6803face26f82dfdfa43da726e1a03789df7838a16eadef60c46ea0cab3023a17",
          "sha256": "9f6cd5f10763bd3e61f8b5f715bedd54582112e7212f4b5fe40a9fc1da72ca8b",
          "sha1": "187f7934be38d07e9f9d527b6fab717ac7f9f252",
          "md5": "575bb1ab6293872852fd0ac638810fb3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "700d58638751a4d0be63d1d71008edff117774a5915b7603de01ec87aafe6bd6803face26f82dfdfa43da726e1a03789df7838a16eadef60c46ea0cab3023a17",
          "sha256": "9f6cd5f10763bd3e61f8b5f715bedd54582112e7212f4b5fe40a9fc1da72ca8b",
          "sha1": "187f7934be38d07e9f9d527b6fab717ac7f9f252",
          "md5": "575bb1ab6293872852fd0ac638810fb3"
        }
      ]
    }
  ]
}
