{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "e859459a9ba00ba7912130696260c31904810998fcf38c9c3617820caf0058b6168aee8bb1da42935e7661106c09c6338f29a80cd6666b680f1d92cefc79d096",
          "sha256": "92eb3b407981474c09f1a7a687f410ae77c6dc41ba70c178816f20877f23fb93",
          "sha1": "613e3cd5392b00de7c138951da691d69ee79bf22",
          "md5": "1c5206f073ed6b4a28dd78723c58e684"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "e859459a9ba00ba7912130696260c31904810998fcf38c9c3617820caf0058b6168aee8bb1da42935e7661106c09c6338f29a80cd6666b680f1d92cefc79d096",
          "sha256": "92eb3b407981474c09f1a7a687f410ae77c6dc41ba70c178816f20877f23fb93",
          "sha1": "613e3cd5392b00de7c138951da691d69ee79bf22",
          "md5": "1c5206f073ed6b4a28dd78723c58e684"
        }
      ]
    }
  ]
}
