{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "6f9adb930f8dfb1c99c01ab9a4a583e77867f0bce55aa68bddca11d23c40a036d2eb350b52550561455146cd4f26b39fcac08cc252fa1feaf5ab3ca86dce2967",
          "sha256": "7c482a9cad4a7d756aa3273f12d3fa1877e24a1dca20e24e489a68db0118f2e7",
          "sha1": "efbe2d5f96ad73aba8603163e3bb52520c73c27f",
          "md5": "818a3322fd463c3587e450ee52090331"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "6f9adb930f8dfb1c99c01ab9a4a583e77867f0bce55aa68bddca11d23c40a036d2eb350b52550561455146cd4f26b39fcac08cc252fa1feaf5ab3ca86dce2967",
          "sha256": "7c482a9cad4a7d756aa3273f12d3fa1877e24a1dca20e24e489a68db0118f2e7",
          "sha1": "efbe2d5f96ad73aba8603163e3bb52520c73c27f",
          "md5": "818a3322fd463c3587e450ee52090331"
        }
      ]
    }
  ]
}
