{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "f0ecf20313d59fcbc56dffdac9c96c889463ac6ed6d29b52d3b27bf3957003bbbfdc803592449d6428900f7567d08d8e80b6f2328754a88f4f3d97bb1aa4da7c",
          "sha256": "88e59d55c710f661ab42019713fb38945b98e1d09802727c8f8b26b3d9864491",
          "sha1": "f8f1ae5761bfad23a3bf188f9de8d969e592a076",
          "md5": "6deee627471a7589363851cbe661ac8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "f0ecf20313d59fcbc56dffdac9c96c889463ac6ed6d29b52d3b27bf3957003bbbfdc803592449d6428900f7567d08d8e80b6f2328754a88f4f3d97bb1aa4da7c",
          "sha256": "88e59d55c710f661ab42019713fb38945b98e1d09802727c8f8b26b3d9864491",
          "sha1": "f8f1ae5761bfad23a3bf188f9de8d969e592a076",
          "md5": "6deee627471a7589363851cbe661ac8e"
        }
      ]
    }
  ]
}
