{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "7683ce4cf2bd6444196adee5b282fa64f812fa66d330b247efd9023992caac0258b838817781c4b2470fbe05ba86ae96299543fabee97b7567453e25660416b9",
          "sha256": "5769f32031b14afe352deb1e54b82708f0740d288c92d7e6af0310d9e9dfba2f",
          "sha1": "be37807c6d08c8de692ec33f7169b17cabb8955d",
          "md5": "d503c191b94f4be543f1b8e28f66d368"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "7683ce4cf2bd6444196adee5b282fa64f812fa66d330b247efd9023992caac0258b838817781c4b2470fbe05ba86ae96299543fabee97b7567453e25660416b9",
          "sha256": "5769f32031b14afe352deb1e54b82708f0740d288c92d7e6af0310d9e9dfba2f",
          "sha1": "be37807c6d08c8de692ec33f7169b17cabb8955d",
          "md5": "d503c191b94f4be543f1b8e28f66d368"
        }
      ]
    }
  ]
}
