{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "b1009a3393542614148a34e5787fa6c680e251f90123d01e7172e0f101513bfb99aaaabc03a96ef221ceb748d62680ac05c1e884886064487de32a6d2093254f",
          "sha256": "7e048cde2d14f1f0388dad210aa1f1402b4886f4e6e7fdaa5ab529c39669b82d",
          "sha1": "bf208302962cb794f2fb3fce7f312615e02d8d29",
          "md5": "38d874484186cb51f1c63c37b1f9a64e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "b1009a3393542614148a34e5787fa6c680e251f90123d01e7172e0f101513bfb99aaaabc03a96ef221ceb748d62680ac05c1e884886064487de32a6d2093254f",
          "sha256": "7e048cde2d14f1f0388dad210aa1f1402b4886f4e6e7fdaa5ab529c39669b82d",
          "sha1": "bf208302962cb794f2fb3fce7f312615e02d8d29",
          "md5": "38d874484186cb51f1c63c37b1f9a64e"
        }
      ]
    }
  ]
}
