{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "13ef3776345a70216c2c2a85a5b28dd2ac931af3aaa8ee76f944f0a9f5dfc77b48d03d7228408c889ede0980da35e80d606043f4152eef5068ad6b3aa0fb6dd8",
          "sha256": "3192c4921cb6dbc9a3ceff7f4b30bd55843e89a670d7005eb2e6d7b84a227717",
          "sha1": "263e5ac2f7d847c808efb06ac511f0d69a316bfc",
          "md5": "2d91a325ea109ef9fdfb99bd995f9bac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "13ef3776345a70216c2c2a85a5b28dd2ac931af3aaa8ee76f944f0a9f5dfc77b48d03d7228408c889ede0980da35e80d606043f4152eef5068ad6b3aa0fb6dd8",
          "sha256": "3192c4921cb6dbc9a3ceff7f4b30bd55843e89a670d7005eb2e6d7b84a227717",
          "sha1": "263e5ac2f7d847c808efb06ac511f0d69a316bfc",
          "md5": "2d91a325ea109ef9fdfb99bd995f9bac"
        }
      ]
    }
  ]
}
