{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "faaecb1cc913acbb65fde545cb417ccfe3ed7c3a51077c39cef485f616afca7e8e7968b3649416b94e5640163df78a99d6a0fad6aceb7945386502707cef96a8",
          "sha256": "82d5b20404a375a2831ebf51067c6feefd0eaee0aab6be05644ebc684032c5b4",
          "sha1": "47a9c9ef0a4d0f7e49ab3abbcd778a4e2dd56f52",
          "md5": "0409e9e439026e60f731f9558ef54187"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "faaecb1cc913acbb65fde545cb417ccfe3ed7c3a51077c39cef485f616afca7e8e7968b3649416b94e5640163df78a99d6a0fad6aceb7945386502707cef96a8",
          "sha256": "82d5b20404a375a2831ebf51067c6feefd0eaee0aab6be05644ebc684032c5b4",
          "sha1": "47a9c9ef0a4d0f7e49ab3abbcd778a4e2dd56f52",
          "md5": "0409e9e439026e60f731f9558ef54187"
        }
      ]
    }
  ]
}
