{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "ba6a2df56e82f88925c21ced1bfb9d4a522743598a003f91f629f196210ff4c9016790689719921e73e78fb5b34fbdb45ec1017a40ac9aa8fda71c3b7046a14c",
          "sha256": "f5f1deb5ed257392eff1def3585cbbdda27a51de4d9ffb418c1e511634c9c6db",
          "sha1": "7b21f27d3016014bc73027d6832ea2e43ff04935",
          "md5": "b526f1be02eef90a7e54215522707cad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "ba6a2df56e82f88925c21ced1bfb9d4a522743598a003f91f629f196210ff4c9016790689719921e73e78fb5b34fbdb45ec1017a40ac9aa8fda71c3b7046a14c",
          "sha256": "f5f1deb5ed257392eff1def3585cbbdda27a51de4d9ffb418c1e511634c9c6db",
          "sha1": "7b21f27d3016014bc73027d6832ea2e43ff04935",
          "md5": "b526f1be02eef90a7e54215522707cad"
        }
      ]
    }
  ]
}
