{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "8c89942b15433dc6b32e181cd1f25d8dde26fa5cd9dfee934f845ab4f57fdd36b4a742caf2e650ac3addeb8f2410f8fe4eb9fd0d942879af78d5af32ebdb21ef",
          "sha256": "4c6ef258f6802e48887f2d1c34dd3e821dbaf3438a2a162c5f89f82d5beabb4f",
          "sha1": "61a90d4cf147cafe69d5b125069a8d6c5d05b6ad",
          "md5": "67f0b27568fc99caed77c7e68ee2a5b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "8c89942b15433dc6b32e181cd1f25d8dde26fa5cd9dfee934f845ab4f57fdd36b4a742caf2e650ac3addeb8f2410f8fe4eb9fd0d942879af78d5af32ebdb21ef",
          "sha256": "4c6ef258f6802e48887f2d1c34dd3e821dbaf3438a2a162c5f89f82d5beabb4f",
          "sha1": "61a90d4cf147cafe69d5b125069a8d6c5d05b6ad",
          "md5": "67f0b27568fc99caed77c7e68ee2a5b2"
        }
      ]
    }
  ]
}
