{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "424dc2543c83d6a83ec69ff280551aa7654ebda2bc5b8e20f02544fdbec814b56ef22e4af6267994ee394d29f6e77151c5627f9fac0f2649ea3b93442aa5048e",
          "sha256": "38ae7e07fcb2c068390012916a2fd36c8d5651a37af0e665f7aff3674273acbe",
          "sha1": "398fc150a18fc54ffa662cf6c5c9b18ab4d98ce5",
          "md5": "8c3dd8be7f548f4de5530e26dc5c74a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "424dc2543c83d6a83ec69ff280551aa7654ebda2bc5b8e20f02544fdbec814b56ef22e4af6267994ee394d29f6e77151c5627f9fac0f2649ea3b93442aa5048e",
          "sha256": "38ae7e07fcb2c068390012916a2fd36c8d5651a37af0e665f7aff3674273acbe",
          "sha1": "398fc150a18fc54ffa662cf6c5c9b18ab4d98ce5",
          "md5": "8c3dd8be7f548f4de5530e26dc5c74a4"
        }
      ]
    }
  ]
}
