{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "99d0fce6ae57edf45c66ea407ab6d7ff6db661efca32e01c659709981ad5eafda5aa8653d40f929a1dc53f3e57f34a348e5b5f409c40ba3a50495ebbba6fec04",
          "sha256": "5a5af73009c2a13ad1601baaa83de61fadfb086f03cccfb170120dd6c03d3e09",
          "sha1": "1c8280a04b04454a57d5f49800f2d46c4fbef06d",
          "md5": "50cd70c25d00cbed2039f3af7552639f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "99d0fce6ae57edf45c66ea407ab6d7ff6db661efca32e01c659709981ad5eafda5aa8653d40f929a1dc53f3e57f34a348e5b5f409c40ba3a50495ebbba6fec04",
          "sha256": "5a5af73009c2a13ad1601baaa83de61fadfb086f03cccfb170120dd6c03d3e09",
          "sha1": "1c8280a04b04454a57d5f49800f2d46c4fbef06d",
          "md5": "50cd70c25d00cbed2039f3af7552639f"
        }
      ]
    }
  ]
}
