{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "7ade6adf75b785d64e4137869d250bdc8be00f7c4f31af181e119443c32467f898ffffb4d9744ef1e05c91e0930eec842c5ec85e33a9844f1a97114e97ef7f88",
          "sha256": "05f02afec0fa6baaee58064171dbbea1919d884bde6291a0e73750c7458f7291",
          "sha1": "5cdd95ee04c775c247d404cd83afebe0bd18e9cd",
          "md5": "9482edbe4186724c4f15b0c3cd6d1cfc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "7ade6adf75b785d64e4137869d250bdc8be00f7c4f31af181e119443c32467f898ffffb4d9744ef1e05c91e0930eec842c5ec85e33a9844f1a97114e97ef7f88",
          "sha256": "05f02afec0fa6baaee58064171dbbea1919d884bde6291a0e73750c7458f7291",
          "sha1": "5cdd95ee04c775c247d404cd83afebe0bd18e9cd",
          "md5": "9482edbe4186724c4f15b0c3cd6d1cfc"
        }
      ]
    }
  ]
}
