{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "226c28f62010812aba424695fb8f3776313c62ae7f7cebeab7d7eea92e13e0507621bfe749c2f3fe628fb5c77fef86936ee537904feca8f8f4d139ee57f562ec",
          "sha256": "4195ba0d71ad6e94941999e51b28db34445e4051b2fb189b7b5e85d3a30bb029",
          "sha1": "233a43363eecd39a153cd6d0f6b705ba38f975d5",
          "md5": "251bf44af5bd3baa7b67ada3fefed1eb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "226c28f62010812aba424695fb8f3776313c62ae7f7cebeab7d7eea92e13e0507621bfe749c2f3fe628fb5c77fef86936ee537904feca8f8f4d139ee57f562ec",
          "sha256": "4195ba0d71ad6e94941999e51b28db34445e4051b2fb189b7b5e85d3a30bb029",
          "sha1": "233a43363eecd39a153cd6d0f6b705ba38f975d5",
          "md5": "251bf44af5bd3baa7b67ada3fefed1eb"
        }
      ]
    }
  ]
}
