{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.3-SNAPSHOT.jar",
          "url": "runelite-api-1.0.3-SNAPSHOT.jar",
          "size": 1377658,
          "sha512": "4b267487d283a0460ac74059af5641c8bcdf27855a6903892dfc6d7eb55dcdac7fd73fffa1fb51a9f58617c57ecc366f007a314cf0b373a676bf45cb4220c1e9",
          "sha256": "fadd0437c18b7d338e7a93176186c6ddb8e08b50bf4fc5f842d55b792b33f0a7",
          "sha1": "f1b0f705fc9844d8d8907865bad397a81474ca48",
          "md5": "156adf1ac8fdc523b9f136ba34c17fad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.3-SNAPSHOT.jar",
          "url": "runelite-api-1.0.3-SNAPSHOT.jar",
          "size": 1377658,
          "sha512": "4b267487d283a0460ac74059af5641c8bcdf27855a6903892dfc6d7eb55dcdac7fd73fffa1fb51a9f58617c57ecc366f007a314cf0b373a676bf45cb4220c1e9",
          "sha256": "fadd0437c18b7d338e7a93176186c6ddb8e08b50bf4fc5f842d55b792b33f0a7",
          "sha1": "f1b0f705fc9844d8d8907865bad397a81474ca48",
          "md5": "156adf1ac8fdc523b9f136ba34c17fad"
        }
      ]
    }
  ]
}
