{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.3-SNAPSHOT.jar",
          "url": "runelite-api-1.0.3-SNAPSHOT.jar",
          "size": 1377625,
          "sha512": "09c1581c67b2571da575f19b8cdb992861a25becc6aa0a4d5bd4c1fccc073165a056ffa61a3bf72ba84770f5b70b401b2b0c32eb72b15691ebb21a0ad7d6c1a8",
          "sha256": "0ac252ce316838ec70cf0e14027a7408ff3dfa0bd3f4b9eabe6ba075effca858",
          "sha1": "0dbc4ed8e946011152f7b756212823f8358e5602",
          "md5": "b4d4b746a1c83f02ee31d011b5f373ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.3-SNAPSHOT.jar",
          "url": "runelite-api-1.0.3-SNAPSHOT.jar",
          "size": 1377625,
          "sha512": "09c1581c67b2571da575f19b8cdb992861a25becc6aa0a4d5bd4c1fccc073165a056ffa61a3bf72ba84770f5b70b401b2b0c32eb72b15691ebb21a0ad7d6c1a8",
          "sha256": "0ac252ce316838ec70cf0e14027a7408ff3dfa0bd3f4b9eabe6ba075effca858",
          "sha1": "0dbc4ed8e946011152f7b756212823f8358e5602",
          "md5": "b4d4b746a1c83f02ee31d011b5f373ea"
        }
      ]
    }
  ]
}
