{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.0-SNAPSHOT.jar",
          "url": "http-api-4.31.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "e636322d4a2aecf68e7c3825485370cd8913abd23f7ba13239574e94d008b5f6e159ca5f29a1bbf61b954e4d1b4c98496ad48614b726832daac91f85add6dce0",
          "sha256": "e1d7605b884afef75e6535e774cdc996f978dc479385f0b3a9f0b1b578091fe0",
          "sha1": "12517fb6a5bd17f1a200ce4dda06b1d23105c1d1",
          "md5": "4c08c73f780ba06874a280b743063acf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.0-SNAPSHOT.jar",
          "url": "http-api-4.31.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "e636322d4a2aecf68e7c3825485370cd8913abd23f7ba13239574e94d008b5f6e159ca5f29a1bbf61b954e4d1b4c98496ad48614b726832daac91f85add6dce0",
          "sha256": "e1d7605b884afef75e6535e774cdc996f978dc479385f0b3a9f0b1b578091fe0",
          "sha1": "12517fb6a5bd17f1a200ce4dda06b1d23105c1d1",
          "md5": "4c08c73f780ba06874a280b743063acf"
        }
      ]
    }
  ]
}
