{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.0-SNAPSHOT.jar",
          "url": "http-api-4.31.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "88a619411b84b397e59d1c8a5053a002772a29edd5c3fbf06e4d1668141bfc79c7345b8624e44ad967d0b5091413331e8ef4627306579a10361e3dabfb216863",
          "sha256": "252c32a83f4e294a8ac76a748fde929bb0c20d21101e53ffa6f261cba2da52e2",
          "sha1": "53d5f5436a18ea6dedd002efbf14566bd1b99cf9",
          "md5": "da07db371ffc38a9796c438f432c79f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.0-SNAPSHOT.jar",
          "url": "http-api-4.31.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "88a619411b84b397e59d1c8a5053a002772a29edd5c3fbf06e4d1668141bfc79c7345b8624e44ad967d0b5091413331e8ef4627306579a10361e3dabfb216863",
          "sha256": "252c32a83f4e294a8ac76a748fde929bb0c20d21101e53ffa6f261cba2da52e2",
          "sha1": "53d5f5436a18ea6dedd002efbf14566bd1b99cf9",
          "md5": "da07db371ffc38a9796c438f432c79f8"
        }
      ]
    }
  ]
}
