{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0.jar",
          "url": "http-api-4.27.0.jar",
          "size": 88795,
          "sha512": "86c1d0f45697407666bd776b522f7b9c7342fefae9e9dbd9744c2ee0dddbd51c9022914be08a0c5d9cc6076094895f73d3fc1dbaa71bab1def755ebeeea183cf",
          "sha256": "c678af722e2b80e1010c4bb55d507f3c93578be71437a4ad9fc7ad08f34603cc",
          "sha1": "67f3364341f038ef442b5b15d88c42c4abe140d3",
          "md5": "2c917e8ebcfd3ca000b38036e2b426a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0.jar",
          "url": "http-api-4.27.0.jar",
          "size": 88795,
          "sha512": "86c1d0f45697407666bd776b522f7b9c7342fefae9e9dbd9744c2ee0dddbd51c9022914be08a0c5d9cc6076094895f73d3fc1dbaa71bab1def755ebeeea183cf",
          "sha256": "c678af722e2b80e1010c4bb55d507f3c93578be71437a4ad9fc7ad08f34603cc",
          "sha1": "67f3364341f038ef442b5b15d88c42c4abe140d3",
          "md5": "2c917e8ebcfd3ca000b38036e2b426a1"
        }
      ]
    }
  ]
}
