{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.27.0-SNAPSHOT.jar",
          "url": "runelite-api-4.27.0-SNAPSHOT.jar",
          "size": 1357946,
          "sha512": "e5d05f3fe0da9bc1ea2029ceea9c34a777156fcfcccb9356b34862759aa73dfda3585ecb86bf00deab8e9c7e6dc2abba964622c35514f7e2d8a8d79891578d1e",
          "sha256": "132c78d29c2c5c563283a5209024a1c9530ac31e0a844de31a50cdd2c44f36cf",
          "sha1": "acdabf3be91a47d47adc783cf0531b890f4ebe68",
          "md5": "9f2cac2965215f72e44d9707944c3865"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.27.0-SNAPSHOT.jar",
          "url": "runelite-api-4.27.0-SNAPSHOT.jar",
          "size": 1357946,
          "sha512": "e5d05f3fe0da9bc1ea2029ceea9c34a777156fcfcccb9356b34862759aa73dfda3585ecb86bf00deab8e9c7e6dc2abba964622c35514f7e2d8a8d79891578d1e",
          "sha256": "132c78d29c2c5c563283a5209024a1c9530ac31e0a844de31a50cdd2c44f36cf",
          "sha1": "acdabf3be91a47d47adc783cf0531b890f4ebe68",
          "md5": "9f2cac2965215f72e44d9707944c3865"
        }
      ]
    }
  ]
}
