{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.27.0-SNAPSHOT.jar",
          "url": "runelite-api-4.27.0-SNAPSHOT.jar",
          "size": 1359882,
          "sha512": "fe511396daf16d5d79ef6c22c50c96e01813a1f75f3b83eda4a4a90da3d008d227a56778d5eb871dd76f599cef8f6f1900164738595c8ee934caf3a9a1769d92",
          "sha256": "e9530e74d855b2249a471384d0ae8ef3a1d39edf1840ae62dbca178d49387f9e",
          "sha1": "da694381487a6ee638078d2a7ad57ecc3eece8f9",
          "md5": "57fd5317da93416e94f61b29353b262a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.27.0-SNAPSHOT.jar",
          "url": "runelite-api-4.27.0-SNAPSHOT.jar",
          "size": 1359882,
          "sha512": "fe511396daf16d5d79ef6c22c50c96e01813a1f75f3b83eda4a4a90da3d008d227a56778d5eb871dd76f599cef8f6f1900164738595c8ee934caf3a9a1769d92",
          "sha256": "e9530e74d855b2249a471384d0ae8ef3a1d39edf1840ae62dbca178d49387f9e",
          "sha1": "da694381487a6ee638078d2a7ad57ecc3eece8f9",
          "md5": "57fd5317da93416e94f61b29353b262a"
        }
      ]
    }
  ]
}
