{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.5-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.5-EXPERIMENTAL.jar",
          "url": "http-api-1.0.5-EXPERIMENTAL.jar",
          "size": 85931,
          "sha512": "fc4bc1b9998b4f38de89388dd1a0a99a6d2ca28529375d462d1f717f69b503e3247b43fb497ab7a2cb5b0c37b8a30f47c91eac2b35e82c12f848427ad52a11df",
          "sha256": "0dc9502ce1034ee821efb94e8acc613f94d1d931e9adce82bf636fbc18536f6b",
          "sha1": "3a7fd138177829240081897b652b55db156ce6c3",
          "md5": "ce2efbf537ef2ce1346781f53a7d3f81"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.5-EXPERIMENTAL.jar",
          "url": "http-api-1.0.5-EXPERIMENTAL.jar",
          "size": 85931,
          "sha512": "fc4bc1b9998b4f38de89388dd1a0a99a6d2ca28529375d462d1f717f69b503e3247b43fb497ab7a2cb5b0c37b8a30f47c91eac2b35e82c12f848427ad52a11df",
          "sha256": "0dc9502ce1034ee821efb94e8acc613f94d1d931e9adce82bf636fbc18536f6b",
          "sha1": "3a7fd138177829240081897b652b55db156ce6c3",
          "md5": "ce2efbf537ef2ce1346781f53a7d3f81"
        }
      ]
    }
  ]
}
