{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.6.jar",
          "url": "runelite-api-1.0.6.jar",
          "size": 1379772,
          "sha512": "6aa6f78076dd0e64163967be1f6f9c3070f109e823b6f6478b203ce6f700894b74ed15c4033508e9a983c407312d9542a239c898e3c305d897cec5b77d04176d",
          "sha256": "ac76613cf7334b5355e4d0c4fc0bc467906d9845593ab852a71a431257db6c87",
          "sha1": "b471f9c6006553345946411520fec270db492242",
          "md5": "7e6cc681c6327ede1295c63a318d579f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.6.jar",
          "url": "runelite-api-1.0.6.jar",
          "size": 1379772,
          "sha512": "6aa6f78076dd0e64163967be1f6f9c3070f109e823b6f6478b203ce6f700894b74ed15c4033508e9a983c407312d9542a239c898e3c305d897cec5b77d04176d",
          "sha256": "ac76613cf7334b5355e4d0c4fc0bc467906d9845593ab852a71a431257db6c87",
          "sha1": "b471f9c6006553345946411520fec270db492242",
          "md5": "7e6cc681c6327ede1295c63a318d579f"
        }
      ]
    }
  ]
}
