{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.6.jar",
          "url": "runelite-api-1.0.6.jar",
          "size": 1379836,
          "sha512": "9d468dbc765654cbfadbe075f876537447edc2f9fedba223f9438fd238bc11156c41eb892f35f28d977f991e9068e0da6d846b174f21953cf86a570e13aa6433",
          "sha256": "29dc4a52c9ec5eab61685d941eb7c3414bd438d3334bbf85fa122ba79af2d961",
          "sha1": "bd18f7b6243cca341f9fb1621d5f087d48983997",
          "md5": "d02a45113fd0823b0d1a58b3ef67fc9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.6.jar",
          "url": "runelite-api-1.0.6.jar",
          "size": 1379836,
          "sha512": "9d468dbc765654cbfadbe075f876537447edc2f9fedba223f9438fd238bc11156c41eb892f35f28d977f991e9068e0da6d846b174f21953cf86a570e13aa6433",
          "sha256": "29dc4a52c9ec5eab61685d941eb7c3414bd438d3334bbf85fa122ba79af2d961",
          "sha1": "bd18f7b6243cca341f9fb1621d5f087d48983997",
          "md5": "d02a45113fd0823b0d1a58b3ef67fc9e"
        }
      ]
    }
  ]
}
