{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.6.jar",
          "url": "runelite-api-1.0.6.jar",
          "size": 1379933,
          "sha512": "6e3c56235110da4265376a0649f3177cf9885f935479dda4b3e6e5d6e349d28639929800dc332c86b295b0a9334654205f376ee3e2fc510472a175d67f9b4884",
          "sha256": "25258331610c8dfd2b64946424918fa0c390f92a03ee969f98055bec099f0db2",
          "sha1": "bbd58992ad6631e675e87ea0fccf4ab70c2299cb",
          "md5": "2c0842912300b5d3e3d723029cf2cf5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.6.jar",
          "url": "runelite-api-1.0.6.jar",
          "size": 1379933,
          "sha512": "6e3c56235110da4265376a0649f3177cf9885f935479dda4b3e6e5d6e349d28639929800dc332c86b295b0a9334654205f376ee3e2fc510472a175d67f9b4884",
          "sha256": "25258331610c8dfd2b64946424918fa0c390f92a03ee969f98055bec099f0db2",
          "sha1": "bbd58992ad6631e675e87ea0fccf4ab70c2299cb",
          "md5": "2c0842912300b5d3e3d723029cf2cf5d"
        }
      ]
    }
  ]
}
