{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "0965070e1a63d65394ada1b2cafff3d73f8cb4ff129d1b027273944149641998f81c336a511d46aec958fd641e43a790c958f3675cd5d4d029267f133099d201",
          "sha256": "41a9f5a717f9cfc1cdf6054afc0573aace513bc3f42b8067b2efd745a1e0cbb2",
          "sha1": "be49de80357b5488eb5f353a61012e3a1784c825",
          "md5": "5b54465b63f1c4689faf146f585f21af"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "0965070e1a63d65394ada1b2cafff3d73f8cb4ff129d1b027273944149641998f81c336a511d46aec958fd641e43a790c958f3675cd5d4d029267f133099d201",
          "sha256": "41a9f5a717f9cfc1cdf6054afc0573aace513bc3f42b8067b2efd745a1e0cbb2",
          "sha1": "be49de80357b5488eb5f353a61012e3a1784c825",
          "md5": "5b54465b63f1c4689faf146f585f21af"
        }
      ]
    }
  ]
}
