{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "c272527f450f70b5f7de602e5925fcfe2f24ee0898220085c545fe9d596ba2554185c40340e66eb5f77a65fbf5cd7222dd0ef4396b7da9850e368c9b93ff7a05",
          "sha256": "7a359b0aec352ef7ee540a3f11abb211941f3726271a9acc2eb3cf7e925fc23c",
          "sha1": "1f0ed8503bbede0ee5377665e4e7769dca0fbcb9",
          "md5": "af1e90f532842476f5cefdf442519b71"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "c272527f450f70b5f7de602e5925fcfe2f24ee0898220085c545fe9d596ba2554185c40340e66eb5f77a65fbf5cd7222dd0ef4396b7da9850e368c9b93ff7a05",
          "sha256": "7a359b0aec352ef7ee540a3f11abb211941f3726271a9acc2eb3cf7e925fc23c",
          "sha1": "1f0ed8503bbede0ee5377665e4e7769dca0fbcb9",
          "md5": "af1e90f532842476f5cefdf442519b71"
        }
      ]
    }
  ]
}
