{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6.jar",
          "url": "http-api-1.0.6.jar",
          "size": 91330,
          "sha512": "4a95db0ff0f56ce6229cefa6a2d0ac3145cdc0fd637c0aed7bd0a8fd686f0415957f3386b7f79a2db6cd88c4a7e7a9cb4d9bad3b40755e46bc3ddb2f5d8c42d8",
          "sha256": "5de4a64ab9de560e221701d6f695808fcb6630c14c309d46034973facc0278f9",
          "sha1": "5243905ffd19dfa3344b8ff6783be2dd8f01a552",
          "md5": "4218520691f9d2968b151de4e5726c60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6.jar",
          "url": "http-api-1.0.6.jar",
          "size": 91330,
          "sha512": "4a95db0ff0f56ce6229cefa6a2d0ac3145cdc0fd637c0aed7bd0a8fd686f0415957f3386b7f79a2db6cd88c4a7e7a9cb4d9bad3b40755e46bc3ddb2f5d8c42d8",
          "sha256": "5de4a64ab9de560e221701d6f695808fcb6630c14c309d46034973facc0278f9",
          "sha1": "5243905ffd19dfa3344b8ff6783be2dd8f01a552",
          "md5": "4218520691f9d2968b151de4e5726c60"
        }
      ]
    }
  ]
}
