{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6.jar",
          "url": "http-api-1.0.6.jar",
          "size": 91329,
          "sha512": "5caba0a10074e70b2130cb6f48b5868e4ec403bab0d724299c26f2f6ded2b49385bfe878b677c2babcac333e06efbe00c5703715df92f7e3c9901c394b0b9ee0",
          "sha256": "23417c4c03ebefb01c65781374c969260eb3f50f90f3dd9227448f700b26f617",
          "sha1": "d70d6f7238d492ea4c6e961d4e52f448acc651fd",
          "md5": "0871a2abc6686c1c50186a1a60bcf0fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6.jar",
          "url": "http-api-1.0.6.jar",
          "size": 91329,
          "sha512": "5caba0a10074e70b2130cb6f48b5868e4ec403bab0d724299c26f2f6ded2b49385bfe878b677c2babcac333e06efbe00c5703715df92f7e3c9901c394b0b9ee0",
          "sha256": "23417c4c03ebefb01c65781374c969260eb3f50f90f3dd9227448f700b26f617",
          "sha1": "d70d6f7238d492ea4c6e961d4e52f448acc651fd",
          "md5": "0871a2abc6686c1c50186a1a60bcf0fd"
        }
      ]
    }
  ]
}
