{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6.jar",
          "url": "http-api-1.0.6.jar",
          "size": 91329,
          "sha512": "ef485b566368dc66ef99631a54910895c10a053ab7f686e52e394ed924d73b72c3a64b65669c1f3e7f78d2f24ebf97d1d0b80789685a71dd7bfb1bccd5d0ff44",
          "sha256": "a0c134c4d9f54dca8862a0fddfb9e9f166996b8f3935d4c1bd5df9bfffe91d5e",
          "sha1": "1fde22d9c620e57373708c770c8444b32ca3c71f",
          "md5": "7bb756a7e3f72a01e8cfc2b8ff456286"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6.jar",
          "url": "http-api-1.0.6.jar",
          "size": 91329,
          "sha512": "ef485b566368dc66ef99631a54910895c10a053ab7f686e52e394ed924d73b72c3a64b65669c1f3e7f78d2f24ebf97d1d0b80789685a71dd7bfb1bccd5d0ff44",
          "sha256": "a0c134c4d9f54dca8862a0fddfb9e9f166996b8f3935d4c1bd5df9bfffe91d5e",
          "sha1": "1fde22d9c620e57373708c770c8444b32ca3c71f",
          "md5": "7bb756a7e3f72a01e8cfc2b8ff456286"
        }
      ]
    }
  ]
}
