{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.3.jar",
          "url": "injector-plugin-2.0.3.jar",
          "size": 118831,
          "sha512": "4bf7d3b50167acc1d9d9c90bd3086d7e8776c0e0e93b966e261b680cb76e72057d2736089df9ebee75373525427252b71b95340b02e8e6f257b235f5b9bdd546",
          "sha256": "9e368645e2e8654bb55db487e24506ff1126f873eff8e7ce8016f1f48565a053",
          "sha1": "a0e13c762c1b698b8b5f2d5b547e0bc35e61927f",
          "md5": "40e7fda98ee8c19185083c0dac8b5f06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.3.jar",
          "url": "injector-plugin-2.0.3.jar",
          "size": 118831,
          "sha512": "4bf7d3b50167acc1d9d9c90bd3086d7e8776c0e0e93b966e261b680cb76e72057d2736089df9ebee75373525427252b71b95340b02e8e6f257b235f5b9bdd546",
          "sha256": "9e368645e2e8654bb55db487e24506ff1126f873eff8e7ce8016f1f48565a053",
          "sha1": "a0e13c762c1b698b8b5f2d5b547e0bc35e61927f",
          "md5": "40e7fda98ee8c19185083c0dac8b5f06"
        }
      ]
    }
  ]
}
