{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.7.jar",
          "url": "http-api-1.0.7.jar",
          "size": 91329,
          "sha512": "a2d7aa17e3de0abe018e3b84af5343045c615c6a76b715fd82dd8b3b5740b62c645dc2a6dee2ad02a48ab0dd74d2280c14ae6efd356ec8fc364ebf5606ce26c5",
          "sha256": "ec1549ca1aeb0ba2875e2030dfc106289d65fcc922b20b6e5a538af6e1f6d881",
          "sha1": "bf37d4ba2fa8f86bbeb4e21380bc68bcb68b6441",
          "md5": "00d37fc8d659c8e976464ec68f915f53"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.7.jar",
          "url": "http-api-1.0.7.jar",
          "size": 91329,
          "sha512": "a2d7aa17e3de0abe018e3b84af5343045c615c6a76b715fd82dd8b3b5740b62c645dc2a6dee2ad02a48ab0dd74d2280c14ae6efd356ec8fc364ebf5606ce26c5",
          "sha256": "ec1549ca1aeb0ba2875e2030dfc106289d65fcc922b20b6e5a538af6e1f6d881",
          "sha1": "bf37d4ba2fa8f86bbeb4e21380bc68bcb68b6441",
          "md5": "00d37fc8d659c8e976464ec68f915f53"
        }
      ]
    }
  ]
}
