{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.7.jar",
          "url": "http-api-1.0.7.jar",
          "size": 91329,
          "sha512": "47c105003de76f50c45401bfb04c91e42bcdd2b326195c6a32bff6d1013eabefcee0c09642b36d8998b2e2f975176cabd2de2c09008cefd98b0bbe5695592121",
          "sha256": "9305dc1cce14d6c9fe86ab292230a6a92a8640dc11efdbca0976374b49d90e57",
          "sha1": "2069f8b2bdfeabe410c5fb645ddf806106f19667",
          "md5": "549c3cc3fb6c387abaea06b6bbdc968d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.7.jar",
          "url": "http-api-1.0.7.jar",
          "size": 91329,
          "sha512": "47c105003de76f50c45401bfb04c91e42bcdd2b326195c6a32bff6d1013eabefcee0c09642b36d8998b2e2f975176cabd2de2c09008cefd98b0bbe5695592121",
          "sha256": "9305dc1cce14d6c9fe86ab292230a6a92a8640dc11efdbca0976374b49d90e57",
          "sha1": "2069f8b2bdfeabe410c5fb645ddf806106f19667",
          "md5": "549c3cc3fb6c387abaea06b6bbdc968d"
        }
      ]
    }
  ]
}
