{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1358828,
          "sha512": "b0e2ff38774d3d874c595ba4b3c5d8b0aef939a9dcf10a3590383aa00290a302671f806c7bfae3fcd019cb1f96e2079e862082ba79e00cd79927e47ec931e5e5",
          "sha256": "4c4860efd8edb434e44d3150a0754dddb32acca55089b37bb2522ec780276c23",
          "sha1": "5c24f74b7381fdc6ed5f96166a69616b816c6eb3",
          "md5": "1288b9306f51ba1b9e5d45e140153a60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1358828,
          "sha512": "b0e2ff38774d3d874c595ba4b3c5d8b0aef939a9dcf10a3590383aa00290a302671f806c7bfae3fcd019cb1f96e2079e862082ba79e00cd79927e47ec931e5e5",
          "sha256": "4c4860efd8edb434e44d3150a0754dddb32acca55089b37bb2522ec780276c23",
          "sha1": "5c24f74b7381fdc6ed5f96166a69616b816c6eb3",
          "md5": "1288b9306f51ba1b9e5d45e140153a60"
        }
      ]
    }
  ]
}
