{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1362258,
          "sha512": "06990b2dd452c289793611a2097ac8069c4b7eded4bc238829deae5c05547d96f58e61227997a29b1e47392181745d001da57d156d813c3eb335d0f59d506b6c",
          "sha256": "57e3179e4dd66855a8748b26d5b54307fb623be30b3aec7786100208e03ad370",
          "sha1": "8f3421156cac719b39850406000218225faf143f",
          "md5": "df67d564b30da2b7d26f0e448f0faa88"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1362258,
          "sha512": "06990b2dd452c289793611a2097ac8069c4b7eded4bc238829deae5c05547d96f58e61227997a29b1e47392181745d001da57d156d813c3eb335d0f59d506b6c",
          "sha256": "57e3179e4dd66855a8748b26d5b54307fb623be30b3aec7786100208e03ad370",
          "sha1": "8f3421156cac719b39850406000218225faf143f",
          "md5": "df67d564b30da2b7d26f0e448f0faa88"
        }
      ]
    }
  ]
}
