{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1361222,
          "sha512": "f3b52618b008e5633dbc9822ca3685c7e6659335a20c59861a70d8e835db82ef3fb5d1b3be420c282713c33fe384b7df1682436355eabffcb52112c87612bcdf",
          "sha256": "40331339dec864227676ad96f9f578f9d4625b3ecd5dd42c009aa242a74589fb",
          "sha1": "362d08c1cca4535ceb21605fa63b42884abf086f",
          "md5": "d181e5049e293b09d43835ffc40bd163"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1361222,
          "sha512": "f3b52618b008e5633dbc9822ca3685c7e6659335a20c59861a70d8e835db82ef3fb5d1b3be420c282713c33fe384b7df1682436355eabffcb52112c87612bcdf",
          "sha256": "40331339dec864227676ad96f9f578f9d4625b3ecd5dd42c009aa242a74589fb",
          "sha1": "362d08c1cca4535ceb21605fa63b42884abf086f",
          "md5": "d181e5049e293b09d43835ffc40bd163"
        }
      ]
    }
  ]
}
