{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1358802,
          "sha512": "b31eb77e3ae9b5e5e97dffbec48cfaacdc07d5872472ed8755401a2704d436efd37289613efdac5f2d838f55bf1ca00b5fd5626ab40d4f5344d84de3530015a2",
          "sha256": "f602abf2e38e02730c58d7cce720c79194bd5098250c277b3da09abc3c28b691",
          "sha1": "f042a5e77e369f0f2bbb396146148e41159b112f",
          "md5": "a539382ebe82e65dd4fbb1f953423b57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1358802,
          "sha512": "b31eb77e3ae9b5e5e97dffbec48cfaacdc07d5872472ed8755401a2704d436efd37289613efdac5f2d838f55bf1ca00b5fd5626ab40d4f5344d84de3530015a2",
          "sha256": "f602abf2e38e02730c58d7cce720c79194bd5098250c277b3da09abc3c28b691",
          "sha1": "f042a5e77e369f0f2bbb396146148e41159b112f",
          "md5": "a539382ebe82e65dd4fbb1f953423b57"
        }
      ]
    }
  ]
}
