{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1360191,
          "sha512": "0ad4b50139de54a1645321a80a7ddccf90c3ae0ec399514aa4235cae1712aa191b5de05df350e4ee231d39a0bf8a5c24b05d0f3c9a688f3580c096b0ba1b8c6a",
          "sha256": "6c489c10413bf98df8825ef30b71386a0be1d9077d39556fb12a399f020ac7c2",
          "sha1": "3c4b8473dcd16e5a544d91edbcfff3671f21e600",
          "md5": "726dfb87c0f30885629912f31c373440"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.28.0-SNAPSHOT.jar",
          "url": "runelite-api-4.28.0-SNAPSHOT.jar",
          "size": 1360191,
          "sha512": "0ad4b50139de54a1645321a80a7ddccf90c3ae0ec399514aa4235cae1712aa191b5de05df350e4ee231d39a0bf8a5c24b05d0f3c9a688f3580c096b0ba1b8c6a",
          "sha256": "6c489c10413bf98df8825ef30b71386a0be1d9077d39556fb12a399f020ac7c2",
          "sha1": "3c4b8473dcd16e5a544d91edbcfff3671f21e600",
          "md5": "726dfb87c0f30885629912f31c373440"
        }
      ]
    }
  ]
}
