{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "3c64b6e4cb843f83d530de82f6ce7a3dfa2c94fc98224c7fdc543a4ee35f1631dae21920b509091c1c6ae0e3cbe4243afac78ff222a7734cf06d6f150798ee00",
          "sha256": "5cd1f02320de99159a6dc5a32596dd4dc6243f87f3ae684f7e62d588e406952f",
          "sha1": "47994bfbe97e0a155682d2ac434a0ce6812d28f6",
          "md5": "c659b9e21b13e4eacdeb18e36248ebf2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "3c64b6e4cb843f83d530de82f6ce7a3dfa2c94fc98224c7fdc543a4ee35f1631dae21920b509091c1c6ae0e3cbe4243afac78ff222a7734cf06d6f150798ee00",
          "sha256": "5cd1f02320de99159a6dc5a32596dd4dc6243f87f3ae684f7e62d588e406952f",
          "sha1": "47994bfbe97e0a155682d2ac434a0ce6812d28f6",
          "md5": "c659b9e21b13e4eacdeb18e36248ebf2"
        }
      ]
    }
  ]
}
