{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "f2f4cf67fa2650200cab2860b68f379bd9e189f5333f68100923e33e3106b780ba5649bca1c8378f8cb2e1233ed0748866546f9cfb684545301187db88ec8d38",
          "sha256": "407fec00aa6b7d276f56d751b0ffdf45bdcd7eb47d4a373894e84c4acd14a081",
          "sha1": "126b1baeef605fb5f07609a08807ce5c288098fd",
          "md5": "2b5526c5408420f4133436bd5fdb700a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "f2f4cf67fa2650200cab2860b68f379bd9e189f5333f68100923e33e3106b780ba5649bca1c8378f8cb2e1233ed0748866546f9cfb684545301187db88ec8d38",
          "sha256": "407fec00aa6b7d276f56d751b0ffdf45bdcd7eb47d4a373894e84c4acd14a081",
          "sha1": "126b1baeef605fb5f07609a08807ce5c288098fd",
          "md5": "2b5526c5408420f4133436bd5fdb700a"
        }
      ]
    }
  ]
}
