{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "a5a2238e87817061d746a4af8eb792d46572896006ba188df4bd0c3915c3979f310f70f35e959fd2853a39c8ac6b71db2b4a6c8a515999b38588b1a689c0941e",
          "sha256": "f6cd8a0cdff5b8ebb17f23a496943fda8484e3d8184bc01bffa34a0b853c677c",
          "sha1": "565a45a13ab25af367f5f7a674eb6492aac3372d",
          "md5": "d12cbdeb2575c0a17b8585e76ed3b2e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0.jar",
          "url": "http-api-4.29.0.jar",
          "size": 88795,
          "sha512": "a5a2238e87817061d746a4af8eb792d46572896006ba188df4bd0c3915c3979f310f70f35e959fd2853a39c8ac6b71db2b4a6c8a515999b38588b1a689c0941e",
          "sha256": "f6cd8a0cdff5b8ebb17f23a496943fda8484e3d8184bc01bffa34a0b853c677c",
          "sha1": "565a45a13ab25af367f5f7a674eb6492aac3372d",
          "md5": "d12cbdeb2575c0a17b8585e76ed3b2e5"
        }
      ]
    }
  ]
}
