{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.9-SNAPSHOT.jar",
          "url": "http-api-1.0.9-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "ec372474484dff4f424e073f2c864fc034ba253265f7b226d6f68545b73f4974491a72ff793f98d5e3d7b082cf1e77aaee7cfb9b62059b8663ca9c73303a4bb3",
          "sha256": "594f8cb929c0b326faa9565b0e3dd5211aa10ca33a5090e6de84aebf9a8f0f6d",
          "sha1": "c2ef873cb5e9a3e4163e43f87c5fe6dd7feb6364",
          "md5": "c8ef76cf1e559599e08f257aa3f9c5cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.9-SNAPSHOT.jar",
          "url": "http-api-1.0.9-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "ec372474484dff4f424e073f2c864fc034ba253265f7b226d6f68545b73f4974491a72ff793f98d5e3d7b082cf1e77aaee7cfb9b62059b8663ca9c73303a4bb3",
          "sha256": "594f8cb929c0b326faa9565b0e3dd5211aa10ca33a5090e6de84aebf9a8f0f6d",
          "sha1": "c2ef873cb5e9a3e4163e43f87c5fe6dd7feb6364",
          "md5": "c8ef76cf1e559599e08f257aa3f9c5cf"
        }
      ]
    }
  ]
}
