{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.0.jar",
          "url": "injector-plugin-2.0.0.jar",
          "size": 119796,
          "sha512": "5e37bb25e3155326f51a649c57267e5dd75aae5f71473bef5249da7d39cdfecd5aac74e2612ca85c3024d1b4069a333b308ca8603f095459a178c7730b0a69cc",
          "sha256": "98ae3bd921faa79081b98ac2bbb679994858bcefb9b61fdbe7e51fead7e4939e",
          "sha1": "09c441d634a31dd4e0225c61049fd9a22909d053",
          "md5": "dfdc2007d4655d8fbe01215d2323f92f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.0.jar",
          "url": "injector-plugin-2.0.0.jar",
          "size": 119796,
          "sha512": "5e37bb25e3155326f51a649c57267e5dd75aae5f71473bef5249da7d39cdfecd5aac74e2612ca85c3024d1b4069a333b308ca8603f095459a178c7730b0a69cc",
          "sha256": "98ae3bd921faa79081b98ac2bbb679994858bcefb9b61fdbe7e51fead7e4939e",
          "sha1": "09c441d634a31dd4e0225c61049fd9a22909d053",
          "md5": "dfdc2007d4655d8fbe01215d2323f92f"
        }
      ]
    }
  ]
}
