{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6.jar",
          "url": "runescape-api-1.0.6.jar",
          "size": 126040,
          "sha512": "21c7f5c808f392d902ec8fdf42c8c5fedceb6d8b73df8e3b8fb35aefa92a719c3a431647f75730690577616b6249b6f7bd8a8885913cafe1e55da797570be927",
          "sha256": "bba22aa4eb0fdd782ee23cf177952d6514bc4651c60c4e386d1c005db9b336c4",
          "sha1": "0fc9428b8d049f9f3c8af72bceac9383a14a7289",
          "md5": "d3c4859a966c0762ee6d022569df0cb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6.jar",
          "url": "runescape-api-1.0.6.jar",
          "size": 126040,
          "sha512": "21c7f5c808f392d902ec8fdf42c8c5fedceb6d8b73df8e3b8fb35aefa92a719c3a431647f75730690577616b6249b6f7bd8a8885913cafe1e55da797570be927",
          "sha256": "bba22aa4eb0fdd782ee23cf177952d6514bc4651c60c4e386d1c005db9b336c4",
          "sha1": "0fc9428b8d049f9f3c8af72bceac9383a14a7289",
          "md5": "d3c4859a966c0762ee6d022569df0cb4"
        }
      ]
    }
  ]
}
