{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6.jar",
          "url": "runescape-api-1.0.6.jar",
          "size": 126016,
          "sha512": "adac4e0cc39b29a4dd9ad7c26e9d1904cf38d8606ab3f1d454e10cb6c7bfd621c73839bd75c5efa9499d0af35ed11e10ac8ca8cf79c538533c525cce2ef56a43",
          "sha256": "8e21682f3e32dea1f63b414293dbd13f1d54ae3b3f056f2524e9b11913e92aee",
          "sha1": "4e0e4ec994f87d75234fd950e672fdfa624c59e3",
          "md5": "74f06a3469d1f54fd0ee21e9541afa0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6.jar",
          "url": "runescape-api-1.0.6.jar",
          "size": 126016,
          "sha512": "adac4e0cc39b29a4dd9ad7c26e9d1904cf38d8606ab3f1d454e10cb6c7bfd621c73839bd75c5efa9499d0af35ed11e10ac8ca8cf79c538533c525cce2ef56a43",
          "sha256": "8e21682f3e32dea1f63b414293dbd13f1d54ae3b3f056f2524e9b11913e92aee",
          "sha1": "4e0e4ec994f87d75234fd950e672fdfa624c59e3",
          "md5": "74f06a3469d1f54fd0ee21e9541afa0d"
        }
      ]
    }
  ]
}
