{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6.jar",
          "url": "runescape-api-1.0.6.jar",
          "size": 125995,
          "sha512": "c728e54697562cc929cc498505bff4b1c7dd88b629a90e507d06b92399f698610ad4de7cb4cb76f594b57d619de37de15a7cb94dc161339a8588ba79cc0d62a1",
          "sha256": "13f080b33d94a7aceead65e04efc684c4194be3d2f6d511ca163ace6ff8a8715",
          "sha1": "9406a697b8d7472c8081c132625d1f0000284d45",
          "md5": "5bc5314bf9d599dd662e484d24a9d6ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6.jar",
          "url": "runescape-api-1.0.6.jar",
          "size": 125995,
          "sha512": "c728e54697562cc929cc498505bff4b1c7dd88b629a90e507d06b92399f698610ad4de7cb4cb76f594b57d619de37de15a7cb94dc161339a8588ba79cc0d62a1",
          "sha256": "13f080b33d94a7aceead65e04efc684c4194be3d2f6d511ca163ace6ff8a8715",
          "sha1": "9406a697b8d7472c8081c132625d1f0000284d45",
          "md5": "5bc5314bf9d599dd662e484d24a9d6ac"
        }
      ]
    }
  ]
}
