{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6.jar",
          "url": "runescape-api-1.0.6.jar",
          "size": 123407,
          "sha512": "5df29b43e1e2f68349a074bcb5ae679af6ce8b79de01e62ed367ef4c82899533ff9f37ab0918c4e916ff8efc8cf0031ea7b929be4b625577c1c56c0a4768d7bd",
          "sha256": "b3eb7351ad214cc5cf6201711f7f5eeb5b3cbfa5555a9fb75a631ac402489222",
          "sha1": "ad7f125c06ea6d1a9c15e7111df1093e6464f835",
          "md5": "2ede849af5874a614f60e41db392f702"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6.jar",
          "url": "runescape-api-1.0.6.jar",
          "size": 123407,
          "sha512": "5df29b43e1e2f68349a074bcb5ae679af6ce8b79de01e62ed367ef4c82899533ff9f37ab0918c4e916ff8efc8cf0031ea7b929be4b625577c1c56c0a4768d7bd",
          "sha256": "b3eb7351ad214cc5cf6201711f7f5eeb5b3cbfa5555a9fb75a631ac402489222",
          "sha1": "ad7f125c06ea6d1a9c15e7111df1093e6464f835",
          "md5": "2ede849af5874a614f60e41db392f702"
        }
      ]
    }
  ]
}
