{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "adce7ac2c58f80174376082305e9fc5312667d12e4d0e2e9b59d77d3900e1059a50154442fcbff41054ae2cd494b422af287c40a9da7dc22c4c019b883a205b6",
          "sha256": "4b07a93246d5ef12007cb4c37a8f4b1a73d866a5f6db191e81e931d17765a3df",
          "sha1": "9c9e06084e19f1a33e173fa9beb8659c91143328",
          "md5": "7d28e1eb0012cdb0c4d4616a3992b769"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "adce7ac2c58f80174376082305e9fc5312667d12e4d0e2e9b59d77d3900e1059a50154442fcbff41054ae2cd494b422af287c40a9da7dc22c4c019b883a205b6",
          "sha256": "4b07a93246d5ef12007cb4c37a8f4b1a73d866a5f6db191e81e931d17765a3df",
          "sha1": "9c9e06084e19f1a33e173fa9beb8659c91143328",
          "md5": "7d28e1eb0012cdb0c4d4616a3992b769"
        }
      ]
    }
  ]
}
