{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "903e0ff8fca856aaa9886bf62c5484c60b1046f7e1d0de8dd31a43f5067aea91862bbd2413b0ec25b2b39505d474703892438f4d02288793a1af3bdfaea82448",
          "sha256": "e94a4fc99f903114a11b33614ad7105a99d1a45580f5084a2326a3b7a09abb95",
          "sha1": "307f4254d0c468702db519832ab1f255ac5cfcfd",
          "md5": "835fbec7480639cf1fdcb29b24c808ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "903e0ff8fca856aaa9886bf62c5484c60b1046f7e1d0de8dd31a43f5067aea91862bbd2413b0ec25b2b39505d474703892438f4d02288793a1af3bdfaea82448",
          "sha256": "e94a4fc99f903114a11b33614ad7105a99d1a45580f5084a2326a3b7a09abb95",
          "sha1": "307f4254d0c468702db519832ab1f255ac5cfcfd",
          "md5": "835fbec7480639cf1fdcb29b24c808ad"
        }
      ]
    }
  ]
}
