{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "f40564d869abaa588194154547a0d163d7e6ab0820e50871b720cf2db849a883e9e6a73cdc8c609c9fc10b67bf46184a8cc1aeff6da38636e1f4809eb8ca38d1",
          "sha256": "be67a7b2c3821f2b77ca14b44d0a9598e88112060d5b2339f01c5520ad9210c4",
          "sha1": "43df5a8328db2f680742e4481252d71c416f37f7",
          "md5": "55fbe9caaa2a572a5260bcfed98ef33f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "f40564d869abaa588194154547a0d163d7e6ab0820e50871b720cf2db849a883e9e6a73cdc8c609c9fc10b67bf46184a8cc1aeff6da38636e1f4809eb8ca38d1",
          "sha256": "be67a7b2c3821f2b77ca14b44d0a9598e88112060d5b2339f01c5520ad9210c4",
          "sha1": "43df5a8328db2f680742e4481252d71c416f37f7",
          "md5": "55fbe9caaa2a572a5260bcfed98ef33f"
        }
      ]
    }
  ]
}
