{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88825,
          "sha512": "2f08861a4df33faa9335028d4be541776d4c20b71cedac63a2e485d11768c50dd1cf4e2171298e089d63b47c3127020c226b2e459658437e3fd3fe2edece6b78",
          "sha256": "154d571a685c8c1e62e881fc8ed4bcd7a0ed5e4162f329db3cb35cffd8e3d65d",
          "sha1": "d7ffdf15a09d5cc1f819742ac2daff7617b0b36c",
          "md5": "6264baaabead718a24cc0d76eb2621dd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88825,
          "sha512": "2f08861a4df33faa9335028d4be541776d4c20b71cedac63a2e485d11768c50dd1cf4e2171298e089d63b47c3127020c226b2e459658437e3fd3fe2edece6b78",
          "sha256": "154d571a685c8c1e62e881fc8ed4bcd7a0ed5e4162f329db3cb35cffd8e3d65d",
          "sha1": "d7ffdf15a09d5cc1f819742ac2daff7617b0b36c",
          "md5": "6264baaabead718a24cc0d76eb2621dd"
        }
      ]
    }
  ]
}
