{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88826,
          "sha512": "34816782f53564eabdf2ae0dad0efc3f8c30273835a805278a7403ccec6675f89089f221920da494c286d74ae07b65b2066f5614ce008b119a7275d9ecd66c7b",
          "sha256": "621f79bdd0a552c4e33842b0720c532e8562ea801e773ddd64496c4ccce5269e",
          "sha1": "b63ca1e1042005f46e050459f20827de1d604d4f",
          "md5": "c21f0798ab7e8708b762f477a6f0c1ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88826,
          "sha512": "34816782f53564eabdf2ae0dad0efc3f8c30273835a805278a7403ccec6675f89089f221920da494c286d74ae07b65b2066f5614ce008b119a7275d9ecd66c7b",
          "sha256": "621f79bdd0a552c4e33842b0720c532e8562ea801e773ddd64496c4ccce5269e",
          "sha1": "b63ca1e1042005f46e050459f20827de1d604d4f",
          "md5": "c21f0798ab7e8708b762f477a6f0c1ac"
        }
      ]
    }
  ]
}
