{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "c287335e2dcb540b743622b728755f704af653e042b4c362b1528779a8e38756cc8dad5c5ddfddd2e89c812b870187afffdeda92c3cfdbc13f0d3292419833cf",
          "sha256": "7903d7e627abb048a6e93baf1f1b9ea400a34a0ef84febd8d2ad9046901dcee1",
          "sha1": "5fc309742a8122c18d0b121c3e559088e1667c93",
          "md5": "6bbca3d4ede7ee3f0c6d2e3accc634a0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "c287335e2dcb540b743622b728755f704af653e042b4c362b1528779a8e38756cc8dad5c5ddfddd2e89c812b870187afffdeda92c3cfdbc13f0d3292419833cf",
          "sha256": "7903d7e627abb048a6e93baf1f1b9ea400a34a0ef84febd8d2ad9046901dcee1",
          "sha1": "5fc309742a8122c18d0b121c3e559088e1667c93",
          "md5": "6bbca3d4ede7ee3f0c6d2e3accc634a0"
        }
      ]
    }
  ]
}
