{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "a69e745e708e21be9dc6197280aee03f216a3d301ed45fbe2e0f862f00ccb09e949618f2b429e3dc7fbfcaf3e45b66e9baa7f8c7ab2673bc3b38fcac5709d19f",
          "sha256": "8a6c32dade3663a0899c9e9a8dbf6ae8417872733104660659b61807b6842107",
          "sha1": "3bd985afcb65f7371fd212c4a8ae3880bae515d3",
          "md5": "36a5d6c5506888b6ca6f5d854b58e2c7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "a69e745e708e21be9dc6197280aee03f216a3d301ed45fbe2e0f862f00ccb09e949618f2b429e3dc7fbfcaf3e45b66e9baa7f8c7ab2673bc3b38fcac5709d19f",
          "sha256": "8a6c32dade3663a0899c9e9a8dbf6ae8417872733104660659b61807b6842107",
          "sha1": "3bd985afcb65f7371fd212c4a8ae3880bae515d3",
          "md5": "36a5d6c5506888b6ca6f5d854b58e2c7"
        }
      ]
    }
  ]
}
