{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "a76b42f80e424c91dab30a5fc930f38d43da1819515702da45bedfab5243476cec3661096df686b726b923ab8e6757ed1f37eb048ce1574ec3feed4369e890e6",
          "sha256": "87a20e9e5d50aa3ee97c2368d54da5a78dde6e5e3d2f067423eb0b72a430b07d",
          "sha1": "7796fd6e8d890d2f8d0930ab5105f4434da01921",
          "md5": "5ac524cf85b43dd1b4ffa63012e7a0b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2-SNAPSHOT.jar",
          "url": "http-api-1.0.2-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "a76b42f80e424c91dab30a5fc930f38d43da1819515702da45bedfab5243476cec3661096df686b726b923ab8e6757ed1f37eb048ce1574ec3feed4369e890e6",
          "sha256": "87a20e9e5d50aa3ee97c2368d54da5a78dde6e5e3d2f067423eb0b72a430b07d",
          "sha1": "7796fd6e8d890d2f8d0930ab5105f4434da01921",
          "md5": "5ac524cf85b43dd1b4ffa63012e7a0b4"
        }
      ]
    }
  ]
}
