{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.6-SNAPSHOT.jar",
          "url": "runelite-api-1.0.6-SNAPSHOT.jar",
          "size": 1378823,
          "sha512": "90d77a057e547be47d2a2931b4b453027e1d704e03e96d7c26fb230024baf22cc3e82ad5115f0096e29bcceec4f6511a26045f6254610ea59091a594e0769de7",
          "sha256": "94d94d5480b177868cbf5fd62eb435b8e647750b59b036ef6258796555b826d7",
          "sha1": "a5905e21b58ecbbc7656be474c6c79430def81eb",
          "md5": "7c44e2fedf5894ec2fd2e0bf2d406a09"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.6-SNAPSHOT.jar",
          "url": "runelite-api-1.0.6-SNAPSHOT.jar",
          "size": 1378823,
          "sha512": "90d77a057e547be47d2a2931b4b453027e1d704e03e96d7c26fb230024baf22cc3e82ad5115f0096e29bcceec4f6511a26045f6254610ea59091a594e0769de7",
          "sha256": "94d94d5480b177868cbf5fd62eb435b8e647750b59b036ef6258796555b826d7",
          "sha1": "a5905e21b58ecbbc7656be474c6c79430def81eb",
          "md5": "7c44e2fedf5894ec2fd2e0bf2d406a09"
        }
      ]
    }
  ]
}
