{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88825,
          "sha512": "20fd69afb0479d50b6917ed0856a75d2c042ac5c89eecbc5f92aa6ca2732dd5c0a1a760d66d93377e7aef93c55be9ac0274eb2d5452c76a3cf331083d1f7ecf9",
          "sha256": "6fefc899ad382e6804ea64d0cbb2e6ae3d2b37d8bf5254735b313bac0b4a8d13",
          "sha1": "338354dd615f6fc6b59bc5b24d978893529ca05b",
          "md5": "92ffe06b3b9300b2c95a941a8f5eec84"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88825,
          "sha512": "20fd69afb0479d50b6917ed0856a75d2c042ac5c89eecbc5f92aa6ca2732dd5c0a1a760d66d93377e7aef93c55be9ac0274eb2d5452c76a3cf331083d1f7ecf9",
          "sha256": "6fefc899ad382e6804ea64d0cbb2e6ae3d2b37d8bf5254735b313bac0b4a8d13",
          "sha1": "338354dd615f6fc6b59bc5b24d978893529ca05b",
          "md5": "92ffe06b3b9300b2c95a941a8f5eec84"
        }
      ]
    }
  ]
}
