{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88825,
          "sha512": "03648218a19e153b52780c4326876054697347bd642de553525cb919f7aa181098da724ee7663692e8a2e730d06df5a2956611a9e72cfc112e09b9d149222bd7",
          "sha256": "cf1b8038deb6203314eed59e7d35a99a15e8172da5959c94c01bdab55edd4609",
          "sha1": "d2316e44664cf3103e8ab73ff85fe7f8aa952191",
          "md5": "49a23e980f1ddb0aeb91e7b0ff86909a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88825,
          "sha512": "03648218a19e153b52780c4326876054697347bd642de553525cb919f7aa181098da724ee7663692e8a2e730d06df5a2956611a9e72cfc112e09b9d149222bd7",
          "sha256": "cf1b8038deb6203314eed59e7d35a99a15e8172da5959c94c01bdab55edd4609",
          "sha1": "d2316e44664cf3103e8ab73ff85fe7f8aa952191",
          "md5": "49a23e980f1ddb0aeb91e7b0ff86909a"
        }
      ]
    }
  ]
}
