{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88826,
          "sha512": "df31c2d4151cc2f7ce7fbadba63ea13325fbb5b04de80e5fa8744beff01c6442d52ab425657ffb88b32cc2656c166d759bc0a1cbfe1ffafa151fdfc49751f9da",
          "sha256": "e5aaab0e3b7dbb8cbb0279eb09fcf0cf8c0af528e231c5f4e19c3f10d890d752",
          "sha1": "09cb9bdc81bc29f59514c4fa4d14e24a0decfbb5",
          "md5": "4a3d63901512b462e9d3e31caa8f7d41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88826,
          "sha512": "df31c2d4151cc2f7ce7fbadba63ea13325fbb5b04de80e5fa8744beff01c6442d52ab425657ffb88b32cc2656c166d759bc0a1cbfe1ffafa151fdfc49751f9da",
          "sha256": "e5aaab0e3b7dbb8cbb0279eb09fcf0cf8c0af528e231c5f4e19c3f10d890d752",
          "sha1": "09cb9bdc81bc29f59514c4fa4d14e24a0decfbb5",
          "md5": "4a3d63901512b462e9d3e31caa8f7d41"
        }
      ]
    }
  ]
}
