{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 88435,
          "sha512": "5104d996358aa999029c6f8cd699e2839b9e55d96cb323fca4d7728e3db80c54735cf8ff8598a87c2f3f3bbfd8876a0cc748f065f3a6dcc67f56e9b72a6827b4",
          "sha256": "5334b15776296ac53e2266272af4f36187352bd721e677361c615d4200ad0e46",
          "sha1": "846b81ed9aa655c3ccec00638d8cf54ce2ffc503",
          "md5": "251890beda848997fe2a57a9cac9ebe8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 88435,
          "sha512": "5104d996358aa999029c6f8cd699e2839b9e55d96cb323fca4d7728e3db80c54735cf8ff8598a87c2f3f3bbfd8876a0cc748f065f3a6dcc67f56e9b72a6827b4",
          "sha256": "5334b15776296ac53e2266272af4f36187352bd721e677361c615d4200ad0e46",
          "sha1": "846b81ed9aa655c3ccec00638d8cf54ce2ffc503",
          "md5": "251890beda848997fe2a57a9cac9ebe8"
        }
      ]
    }
  ]
}
