{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "dee51c533b44a44dffcad01ec46957fec7ad6ac2ebb2bdc382234c7c88894bbaf16a9b75b143ae73435106c595e7a7342b0627b282932360cd00e951014e3fb1",
          "sha256": "a9f0cdf51660460ca6d8a5bbfe94080af8dd65ef4a1748f52751dbc6377932c5",
          "sha1": "40703eaa822f27b5b82a3da5793064c092ac5257",
          "md5": "fe219997c83d57fb4902dc71f3f4f098"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "dee51c533b44a44dffcad01ec46957fec7ad6ac2ebb2bdc382234c7c88894bbaf16a9b75b143ae73435106c595e7a7342b0627b282932360cd00e951014e3fb1",
          "sha256": "a9f0cdf51660460ca6d8a5bbfe94080af8dd65ef4a1748f52751dbc6377932c5",
          "sha1": "40703eaa822f27b5b82a3da5793064c092ac5257",
          "md5": "fe219997c83d57fb4902dc71f3f4f098"
        }
      ]
    }
  ]
}
