{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "ce079e1667f4b1dad15317b794dcd305e35fd56674b890fc38fbb9e8e9293dabd13198d6c1b998f3f955c1197b647950301a94388ba9d62e8d163aaf3f1a4eb0",
          "sha256": "0f4e0de711c4f40c241dbddbe55bb0f7c968f86c59131237dcd4d3b24a97947c",
          "sha1": "3b64ca7caba19a7ed2fa1a84f56f46711d6060c0",
          "md5": "5689225e8077365f125a829fe9a23cf7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "ce079e1667f4b1dad15317b794dcd305e35fd56674b890fc38fbb9e8e9293dabd13198d6c1b998f3f955c1197b647950301a94388ba9d62e8d163aaf3f1a4eb0",
          "sha256": "0f4e0de711c4f40c241dbddbe55bb0f7c968f86c59131237dcd4d3b24a97947c",
          "sha1": "3b64ca7caba19a7ed2fa1a84f56f46711d6060c0",
          "md5": "5689225e8077365f125a829fe9a23cf7"
        }
      ]
    }
  ]
}
