{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "ad1b6422eb882ae63578cdfca4bc302f911c005934435fce09a2eb6f64a38da06f4047232dee89692a7d1dbb5d8055e43a9bb8fd939e3735d06885e0b42f8ecc",
          "sha256": "cf4ae12a9f8ce1bbb77ec134357c0c14400e3dfb64ee5ec6e639d269957f2c96",
          "sha1": "c504525ad224fd63f78ebcf4a10b4b5c6cf19d74",
          "md5": "e8af31fd9a2aaddc57a5fc6a968b4fe9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "ad1b6422eb882ae63578cdfca4bc302f911c005934435fce09a2eb6f64a38da06f4047232dee89692a7d1dbb5d8055e43a9bb8fd939e3735d06885e0b42f8ecc",
          "sha256": "cf4ae12a9f8ce1bbb77ec134357c0c14400e3dfb64ee5ec6e639d269957f2c96",
          "sha1": "c504525ad224fd63f78ebcf4a10b4b5c6cf19d74",
          "md5": "e8af31fd9a2aaddc57a5fc6a968b4fe9"
        }
      ]
    }
  ]
}
