{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91328,
          "sha512": "820d4fbdae5c7ce015022f3e007b7d580acaf9e6e030a8e1e2c30be15e5780f23a6703be1c338d3b81acfdbde16a5038c799c8f93dc69fcdbe6bcbf7a713cba5",
          "sha256": "ffe8328b8d8afadadd6672d7915ebd8197798b79a4b4756075a16aef23121870",
          "sha1": "d47272ab85cf47a46c9f3b730eb47688f0c3df3e",
          "md5": "046841ef4c1fdf6af4488693476f8417"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91328,
          "sha512": "820d4fbdae5c7ce015022f3e007b7d580acaf9e6e030a8e1e2c30be15e5780f23a6703be1c338d3b81acfdbde16a5038c799c8f93dc69fcdbe6bcbf7a713cba5",
          "sha256": "ffe8328b8d8afadadd6672d7915ebd8197798b79a4b4756075a16aef23121870",
          "sha1": "d47272ab85cf47a46c9f3b730eb47688f0c3df3e",
          "md5": "046841ef4c1fdf6af4488693476f8417"
        }
      ]
    }
  ]
}
