{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 88435,
          "sha512": "85fa134aa4bd19f75a2df9f357fa0ed8425d3b7a535bbf7a138880f7ad2eac2e355c5e263d00bf31bcce14ec1f4b9c95ae95dea355fa9199597185f4a3ad5cf9",
          "sha256": "58a9b54441ac4a7d8a67283d23390f22221d55e9f6517415ab8d38ce8ad3b834",
          "sha1": "b57584f54e45c253a7c5861eb8d6dc2de667a371",
          "md5": "59e0388626ce34bbd057e8c3ba1e34cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 88435,
          "sha512": "85fa134aa4bd19f75a2df9f357fa0ed8425d3b7a535bbf7a138880f7ad2eac2e355c5e263d00bf31bcce14ec1f4b9c95ae95dea355fa9199597185f4a3ad5cf9",
          "sha256": "58a9b54441ac4a7d8a67283d23390f22221d55e9f6517415ab8d38ce8ad3b834",
          "sha1": "b57584f54e45c253a7c5861eb8d6dc2de667a371",
          "md5": "59e0388626ce34bbd057e8c3ba1e34cc"
        }
      ]
    }
  ]
}
