{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91328,
          "sha512": "5b5f4bfc36f0dac3110eb46b2d5c4c24c38e4e9102ebe728a810da4722512c97d70df6a9e4f993a98d253d7544e44d757f59568c27c513edfb5711f65082c105",
          "sha256": "be7ea7589b02e8d41cde950e909b4d96f375a049be998e8a6fd55563a4c9540e",
          "sha1": "8603e1e54889757b06ec7f0e1db884aacf167b71",
          "md5": "c7bd46193266d73634d33a12cd1d211e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91328,
          "sha512": "5b5f4bfc36f0dac3110eb46b2d5c4c24c38e4e9102ebe728a810da4722512c97d70df6a9e4f993a98d253d7544e44d757f59568c27c513edfb5711f65082c105",
          "sha256": "be7ea7589b02e8d41cde950e909b4d96f375a049be998e8a6fd55563a4c9540e",
          "sha1": "8603e1e54889757b06ec7f0e1db884aacf167b71",
          "md5": "c7bd46193266d73634d33a12cd1d211e"
        }
      ]
    }
  ]
}
