{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 88434,
          "sha512": "ceca78c27db265e3569ce15896b918db322fcbf22a6664263da2ddcfa579f4c02230c683df50b2417f4bf502ca3be5d0d2e26a442249a50dad6fefffd818f35a",
          "sha256": "8480e304b14f524b0fbf7697c18e1a0155a2f37cac6416e44414651a049a9ae4",
          "sha1": "34a5b3588679bded703ea7edd6c273c760444502",
          "md5": "2007fcf126c77aa8c035e4a3c729ef96"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 88434,
          "sha512": "ceca78c27db265e3569ce15896b918db322fcbf22a6664263da2ddcfa579f4c02230c683df50b2417f4bf502ca3be5d0d2e26a442249a50dad6fefffd818f35a",
          "sha256": "8480e304b14f524b0fbf7697c18e1a0155a2f37cac6416e44414651a049a9ae4",
          "sha1": "34a5b3588679bded703ea7edd6c273c760444502",
          "md5": "2007fcf126c77aa8c035e4a3c729ef96"
        }
      ]
    }
  ]
}
