{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 88475,
          "sha512": "e20e79477cb8df5e60878acf5c7ed48bba4e059691654c82917979ae37238e666ffc3c12eee59b241f8f5facf159fb08da930319113760cb786de5af24dc240c",
          "sha256": "73771441d4705f4ff4736c46e9c839030de6a1ce1fe6093b758dce6b0c2fd0c4",
          "sha1": "ce7ab81fe9ecdc6250e77139728b3c15e74bb557",
          "md5": "1bc5895832c1a42fb95fed9f12c419ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 88475,
          "sha512": "e20e79477cb8df5e60878acf5c7ed48bba4e059691654c82917979ae37238e666ffc3c12eee59b241f8f5facf159fb08da930319113760cb786de5af24dc240c",
          "sha256": "73771441d4705f4ff4736c46e9c839030de6a1ce1fe6093b758dce6b0c2fd0c4",
          "sha1": "ce7ab81fe9ecdc6250e77139728b3c15e74bb557",
          "md5": "1bc5895832c1a42fb95fed9f12c419ca"
        }
      ]
    }
  ]
}
