{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91328,
          "sha512": "3124cef6abe9cd794878a363065ff32d2ca7f850ee3ecbc6eb3e6aae862e4ecd557e733925134821537477bd26ddbdf4b5d8a533de777075f5d09a84670ccd61",
          "sha256": "b42dc8ab1d0408dad86d79302f52ded0362905b31cbd9f428f5996f528c93a8b",
          "sha1": "a73f1569fd8d91a8a8d1d5d9a8c65d01c537e380",
          "md5": "ce77416fb1959b1070b48bc11ef76472"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91328,
          "sha512": "3124cef6abe9cd794878a363065ff32d2ca7f850ee3ecbc6eb3e6aae862e4ecd557e733925134821537477bd26ddbdf4b5d8a533de777075f5d09a84670ccd61",
          "sha256": "b42dc8ab1d0408dad86d79302f52ded0362905b31cbd9f428f5996f528c93a8b",
          "sha1": "a73f1569fd8d91a8a8d1d5d9a8c65d01c537e380",
          "md5": "ce77416fb1959b1070b48bc11ef76472"
        }
      ]
    }
  ]
}
