{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "36c41ccc49a3f1a8755d6b92e2af844c975b07968421080fe042ba46b8cd28a57748a5addb12d8c6bd60e07cc5ab04c3a89827f7a34f21c99bd0592a743dbfd8",
          "sha256": "121fc8681bbbd91834ffa4e810fa2772dace6ce811fb9e7f424598a7a2e78a82",
          "sha1": "ea9ef7bcee4f8aec2af263d2d7a0e1e5aa822b91",
          "md5": "1c2b122dac46a4f0df9857b9a13041a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-SNAPSHOT.jar",
          "url": "http-api-1.0.6-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "36c41ccc49a3f1a8755d6b92e2af844c975b07968421080fe042ba46b8cd28a57748a5addb12d8c6bd60e07cc5ab04c3a89827f7a34f21c99bd0592a743dbfd8",
          "sha256": "121fc8681bbbd91834ffa4e810fa2772dace6ce811fb9e7f424598a7a2e78a82",
          "sha1": "ea9ef7bcee4f8aec2af263d2d7a0e1e5aa822b91",
          "md5": "1c2b122dac46a4f0df9857b9a13041a7"
        }
      ]
    }
  ]
}
