{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0-SNAPSHOT.jar",
          "url": "runescape-api-4.28.0-SNAPSHOT.jar",
          "size": 122349,
          "sha512": "021e5166914bbf72bef50fcc6a530230fdbce8cd2bd3dd3ba9390d026d61310f856f67d92bf375551f06013e1a5018b4b2717c4acaa50e281671cd7152818540",
          "sha256": "2207c3be7d7fb14c14e1181b1a9b1247219c4e655a789d69441bd9ec27da1bff",
          "sha1": "e0df40d42bf54777f2979a50a409bad4fa0da054",
          "md5": "0ddc6401d01959040a2e6151454a5620"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.28.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.28.0-SNAPSHOT.jar",
          "url": "runescape-api-4.28.0-SNAPSHOT.jar",
          "size": 122349,
          "sha512": "021e5166914bbf72bef50fcc6a530230fdbce8cd2bd3dd3ba9390d026d61310f856f67d92bf375551f06013e1a5018b4b2717c4acaa50e281671cd7152818540",
          "sha256": "2207c3be7d7fb14c14e1181b1a9b1247219c4e655a789d69441bd9ec27da1bff",
          "sha1": "e0df40d42bf54777f2979a50a409bad4fa0da054",
          "md5": "0ddc6401d01959040a2e6151454a5620"
        }
      ]
    }
  ]
}
