{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88796,
          "sha512": "2f4d1913c4ca040242778bd516902455eed22989dd4110502973844f8775fdd78abb9b1b0d37ef3e460c300b87801f1dccad1f6853de1a60b77379556ab7afd1",
          "sha256": "478bef7a90b0e5eb8b23d3a11c178ae89c8d4d1a37fbe8926771d26c034c0820",
          "sha1": "3818972f1ab90e8adce86665b6d17342b1b5b013",
          "md5": "d48eb05941a13e3a483ced9828102c63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88796,
          "sha512": "2f4d1913c4ca040242778bd516902455eed22989dd4110502973844f8775fdd78abb9b1b0d37ef3e460c300b87801f1dccad1f6853de1a60b77379556ab7afd1",
          "sha256": "478bef7a90b0e5eb8b23d3a11c178ae89c8d4d1a37fbe8926771d26c034c0820",
          "sha1": "3818972f1ab90e8adce86665b6d17342b1b5b013",
          "md5": "d48eb05941a13e3a483ced9828102c63"
        }
      ]
    }
  ]
}
