{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.1.jar",
          "url": "runelite-api-1.0.1.jar",
          "size": 1378005,
          "sha512": "bb61c7c44f43354132f61b3d353711c09c4629ec0fac591b571c77efb611fa7351d5fe864fee4a30718656a0d587595b39a638fba6c52a5c74324894e7fdb714",
          "sha256": "39b2dbb237d613b33bb6c7a029868dca0dfac3ca91f12ea444ea456e51e63265",
          "sha1": "7b4dccd5b4387a4c0c285ae13e3acc0d59a16321",
          "md5": "63bf1802ac9a525a548da6e859594a72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.1.jar",
          "url": "runelite-api-1.0.1.jar",
          "size": 1378005,
          "sha512": "bb61c7c44f43354132f61b3d353711c09c4629ec0fac591b571c77efb611fa7351d5fe864fee4a30718656a0d587595b39a638fba6c52a5c74324894e7fdb714",
          "sha256": "39b2dbb237d613b33bb6c7a029868dca0dfac3ca91f12ea444ea456e51e63265",
          "sha1": "7b4dccd5b4387a4c0c285ae13e3acc0d59a16321",
          "md5": "63bf1802ac9a525a548da6e859594a72"
        }
      ]
    }
  ]
}
