{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.5-SNAPSHOT.jar",
          "url": "runelite-api-1.0.5-SNAPSHOT.jar",
          "size": 1377647,
          "sha512": "395ab015ec516a2372cfdb85cde53d85e7f8d8a4b616fc68c37bf775e41f6479de380fa21cba57a92aa729474ae2f3b001fd23f1a87aeb9d0acad9a6115c4bac",
          "sha256": "d852a1ea6c561990d36313c1356ea58805f2e42a297e139bfcb702753b2e10f6",
          "sha1": "808b2c9698bb7cec213e4af560e42a0c4530c1ee",
          "md5": "6d97e327d45038320b4c0df74dc0bdaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.5-SNAPSHOT.jar",
          "url": "runelite-api-1.0.5-SNAPSHOT.jar",
          "size": 1377647,
          "sha512": "395ab015ec516a2372cfdb85cde53d85e7f8d8a4b616fc68c37bf775e41f6479de380fa21cba57a92aa729474ae2f3b001fd23f1a87aeb9d0acad9a6115c4bac",
          "sha256": "d852a1ea6c561990d36313c1356ea58805f2e42a297e139bfcb702753b2e10f6",
          "sha1": "808b2c9698bb7cec213e4af560e42a0c4530c1ee",
          "md5": "6d97e327d45038320b4c0df74dc0bdaa"
        }
      ]
    }
  ]
}
