{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.5-SNAPSHOT.jar",
          "url": "runelite-api-1.0.5-SNAPSHOT.jar",
          "size": 1377648,
          "sha512": "ba6715a73ca1cd167372764db6b6f0abbffd0bf572dbdcc9de9a0763616b66cd48d4221bf419c39a8674f57c3625c7c3f2e7e9a856530e7d8b219fbd13f2c6d1",
          "sha256": "3b0ae399f91a23a91036ce55b63ca3698f51441e581fc75d0e1569bd0dcf8236",
          "sha1": "f1c8b9dccb0233a164a451b3a514f752904ec8ac",
          "md5": "1fb06127bd8195d34eb73620f8033cb6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.5-SNAPSHOT.jar",
          "url": "runelite-api-1.0.5-SNAPSHOT.jar",
          "size": 1377648,
          "sha512": "ba6715a73ca1cd167372764db6b6f0abbffd0bf572dbdcc9de9a0763616b66cd48d4221bf419c39a8674f57c3625c7c3f2e7e9a856530e7d8b219fbd13f2c6d1",
          "sha256": "3b0ae399f91a23a91036ce55b63ca3698f51441e581fc75d0e1569bd0dcf8236",
          "sha1": "f1c8b9dccb0233a164a451b3a514f752904ec8ac",
          "md5": "1fb06127bd8195d34eb73620f8033cb6"
        }
      ]
    }
  ]
}
