{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "a67e7fecac0453bf6fd53f4b065e3a40ca70b66f011262a5492ec781a33a92521277262eae4a2e57e9b4be09fa9eef79a24a3d5fc06c3057ebfb7b79b4754102",
          "sha256": "f493127d52f0ed091362bcea0b9e10a7cc8005841d1a45644448d67cfd482320",
          "sha1": "dd2e3752e5dc659274fd63ccff74c686e2dc0f97",
          "md5": "6651283ed36a6c2d3acef268dc85c6fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.2-SNAPSHOT.jar",
          "url": "http-api-4.25.2-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "a67e7fecac0453bf6fd53f4b065e3a40ca70b66f011262a5492ec781a33a92521277262eae4a2e57e9b4be09fa9eef79a24a3d5fc06c3057ebfb7b79b4754102",
          "sha256": "f493127d52f0ed091362bcea0b9e10a7cc8005841d1a45644448d67cfd482320",
          "sha1": "dd2e3752e5dc659274fd63ccff74c686e2dc0f97",
          "md5": "6651283ed36a6c2d3acef268dc85c6fb"
        }
      ]
    }
  ]
}
