{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 88796,
          "sha512": "a91e9f157d13919b92c2045f4561925de68a628ec47ecce64995968cab2ec79b28c7ede3b6888ede02af6bd699168dcb36ad17073ebbef22cde750cf6fa6a6c9",
          "sha256": "d3f10256d899d020991d421503d37a524aac32ecc17e249ac1f1bd060f9a497c",
          "sha1": "e9fea57850d2ada082b57356135c9b0dd47b84a3",
          "md5": "7ea3da749da7142c9507d13cc9218300"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 88796,
          "sha512": "a91e9f157d13919b92c2045f4561925de68a628ec47ecce64995968cab2ec79b28c7ede3b6888ede02af6bd699168dcb36ad17073ebbef22cde750cf6fa6a6c9",
          "sha256": "d3f10256d899d020991d421503d37a524aac32ecc17e249ac1f1bd060f9a497c",
          "sha1": "e9fea57850d2ada082b57356135c9b0dd47b84a3",
          "md5": "7ea3da749da7142c9507d13cc9218300"
        }
      ]
    }
  ]
}
