{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8.jar",
          "url": "http-api-1.0.8.jar",
          "size": 91329,
          "sha512": "cb806914ea94531b2ff4252bd091d9fd335878106dac4436189d6db2db6a00960a65ff5bd77120223057c912b6e1e472efd0dc457b6e00b61d2d6b5a30980d31",
          "sha256": "ad62916186f0a5ae81e2e1ce31b1a2549adf318503f7e52e8aaa41181de97d58",
          "sha1": "a2dcff497235c8ca1b25996f509714741bb624e2",
          "md5": "fe24fb566ff2fea183de4d3c30ccd7c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8.jar",
          "url": "http-api-1.0.8.jar",
          "size": 91329,
          "sha512": "cb806914ea94531b2ff4252bd091d9fd335878106dac4436189d6db2db6a00960a65ff5bd77120223057c912b6e1e472efd0dc457b6e00b61d2d6b5a30980d31",
          "sha256": "ad62916186f0a5ae81e2e1ce31b1a2549adf318503f7e52e8aaa41181de97d58",
          "sha1": "a2dcff497235c8ca1b25996f509714741bb624e2",
          "md5": "fe24fb566ff2fea183de4d3c30ccd7c5"
        }
      ]
    }
  ]
}
