{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-client",
    "version": "1.0.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.9-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-1.0.9-SNAPSHOT.jar",
          "url": "runelite-client-1.0.9-SNAPSHOT.jar",
          "size": 11537486,
          "sha512": "0c0bf8d957c9c87d55043b42fa0bc6c43ee99240098f2fecad55bd77163f9da25fa619a687d06c11f967b7cf8307f2ca25d01c878dd8f9b99d29e8ba28187272",
          "sha256": "606420ca3f817338333eaf6369218ddc2efe777321fb8cbad7be6fe6eee5e8be",
          "sha1": "46965a307f5a2c6336ce6755249a7ff79be105dd",
          "md5": "398a58f424f7b981279b8167cf3c270a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "http-api",
          "version": {
            "requires": "1.0.9-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "runelite-jshell",
          "version": {
            "requires": "1.0.9-SNAPSHOT"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.2.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.21.1"
          }
        },
        {
          "group": "com.jakewharton.rxrelay3",
          "module": "rxrelay",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.1.2"
          }
        },
        {
          "group": "org.jgroups",
          "module": "jgroups",
          "version": {
            "requires": "5.2.2.Final"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.9.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "discord",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "net.runelite",
          "module": "rlawt",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "substance",
          "version": {
            "requires": "8.0.02"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        },
        {
          "group": "org.madlonkay",
          "module": "desktopsupport",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.github.zafarkhaja",
          "module": "java-semver",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.pf4j",
          "module": "pf4j",
          "version": {
            "requires": "3.6.0"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.pf4j",
          "module": "pf4j-update",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "net.runelite.gluegen",
          "module": "gluegen-rt",
          "version": {
            "requires": "2.4.0-rc-20220318"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-bom",
          "version": {
            "requires": "3.3.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl"
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl"
        },
        {
          "group": "com.miglayout",
          "module": "miglayout",
          "version": {
            "requires": "3.7.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jboss.aerogear",
          "module": "aerogear-otp-java",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "engine.io-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.github.kwhat",
          "module": "jnativehook",
          "version": {
            "requires": "2.2.2"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.9-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite.rs",
          "module": "runescape-api",
          "version": {
            "requires": "1.0.9-SNAPSHOT"
          }
        },
        {
          "group": "net.runelite.pushingpixels",
          "module": "trident",
          "version": {
            "requires": "1.5.00"
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-x64"
            }
          }
        },
        {
          "group": "net.runelite.jocl",
          "module": "jocl",
          "version": {
            "requires": "1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "jocl",
              "type": "jar",
              "extension": "jar",
              "classifier": "macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-x86"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-linux"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-macos-arm64"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows-x86"
            }
          }
        },
        {
          "group": "org.lwjgl",
          "module": "lwjgl-opengl",
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "lwjgl-opengl",
              "type": "jar",
              "extension": "jar",
              "classifier": "natives-windows"
            }
          }
        }
      ],
      "files": [
        {
          "name": "runelite-client-1.0.9-SNAPSHOT.jar",
          "url": "runelite-client-1.0.9-SNAPSHOT.jar",
          "size": 11537486,
          "sha512": "0c0bf8d957c9c87d55043b42fa0bc6c43ee99240098f2fecad55bd77163f9da25fa619a687d06c11f967b7cf8307f2ca25d01c878dd8f9b99d29e8ba28187272",
          "sha256": "606420ca3f817338333eaf6369218ddc2efe777321fb8cbad7be6fe6eee5e8be",
          "sha1": "46965a307f5a2c6336ce6755249a7ff79be105dd",
          "md5": "398a58f424f7b981279b8167cf3c270a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "runelite-client-1.0.9-SNAPSHOT-shaded.jar",
          "url": "runelite-client-1.0.9-SNAPSHOT-shaded.jar",
          "size": 39100603,
          "sha512": "e9913dfab6707129529bd50c563fd8eef5191b7ae9590d50b948501191d2a0102514359d8d11277620627024123795736699e6eee9a1a1d893882bda5bc8db22",
          "sha256": "fad2b901bd267cb81eff4868ee1c5654def6c6f92c6e31a0b232ec61ea7f9bd5",
          "sha1": "6c860a8e1307b3adad0590d0ff820e9668468e94",
          "md5": "ff6b1157e0ffc041783f605aef921c9b"
        }
      ]
    }
  ]
}
