{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "cache",
    "version": "4.31.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "files": [
        {
          "name": "cache-4.31.1.jar",
          "url": "cache-4.31.1.jar",
          "size": 405660,
          "sha512": "5f91465509343570620ab034e1a593596152fea1ae11efea66a2ed945d6f3b7d7ceee8e1086a25e983fb8633db52808f91efc437a4241346b9fe271f1803d736",
          "sha256": "5aba7511ec7251baf9414b13ccbbc6570fe3c166c33bf95ec2c1c8fda47cce7a",
          "sha1": "cdb47328d42c14345605974654781619379e38bc",
          "md5": "ac281937d72dd80e8475ed9b2bbcef8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "commons-cli",
          "module": "commons-cli",
          "version": {
            "requires": "1.4"
          }
        },
        {
          "group": "io.netty",
          "module": "netty-buffer",
          "version": {
            "requires": "4.1.54.Final"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.8-1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "com.openosrs",
          "module": "http-api",
          "version": {
            "requires": "4.31.1"
          }
        }
      ],
      "files": [
        {
          "name": "cache-4.31.1.jar",
          "url": "cache-4.31.1.jar",
          "size": 405660,
          "sha512": "5f91465509343570620ab034e1a593596152fea1ae11efea66a2ed945d6f3b7d7ceee8e1086a25e983fb8633db52808f91efc437a4241346b9fe271f1803d736",
          "sha256": "5aba7511ec7251baf9414b13ccbbc6570fe3c166c33bf95ec2c1c8fda47cce7a",
          "sha1": "cdb47328d42c14345605974654781619379e38bc",
          "md5": "ac281937d72dd80e8475ed9b2bbcef8e"
        }
      ]
    }
  ]
}
