{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.6-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "size": 1377652,
          "sha512": "c3f662b5711b5494bba8fb3c675e13dda5d3461d03c0c8b501ac7ba1d6f0338734dd5352637f2d5998eeeeb3e618907d4fb55f40fc3218b027e81d59b31ffbfe",
          "sha256": "dccc1d2afae99581e883f9f32455dc7b3cde6c34810da0fb0ef1ac687c2576ce",
          "sha1": "52255251555992b5bb4dd2da1593c43c9cb795c9",
          "md5": "f3614e1d7f40ff36b111e57746307931"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "size": 1377652,
          "sha512": "c3f662b5711b5494bba8fb3c675e13dda5d3461d03c0c8b501ac7ba1d6f0338734dd5352637f2d5998eeeeb3e618907d4fb55f40fc3218b027e81d59b31ffbfe",
          "sha256": "dccc1d2afae99581e883f9f32455dc7b3cde6c34810da0fb0ef1ac687c2576ce",
          "sha1": "52255251555992b5bb4dd2da1593c43c9cb795c9",
          "md5": "f3614e1d7f40ff36b111e57746307931"
        }
      ]
    }
  ]
}
