{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.6-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "size": 1379129,
          "sha512": "2a765fae0c263531ef145adbc31e6d8814d1f217ad0c541723498f756bb040bc9ce66ea29eb7e556f7b5b96b0370fc9eac2b6e7a55b00215b03b19e0b57e2e37",
          "sha256": "9c16c90996df2a310ca3bdf690d80eeb2a3dce684bc41858553b40a4b14b6625",
          "sha1": "f37bfd6ff4dcb972a88311ee0f305a5af730a93c",
          "md5": "7f55d8779dbf9eb4c6d6737d5ad6e9a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "size": 1379129,
          "sha512": "2a765fae0c263531ef145adbc31e6d8814d1f217ad0c541723498f756bb040bc9ce66ea29eb7e556f7b5b96b0370fc9eac2b6e7a55b00215b03b19e0b57e2e37",
          "sha256": "9c16c90996df2a310ca3bdf690d80eeb2a3dce684bc41858553b40a4b14b6625",
          "sha1": "f37bfd6ff4dcb972a88311ee0f305a5af730a93c",
          "md5": "7f55d8779dbf9eb4c6d6737d5ad6e9a3"
        }
      ]
    }
  ]
}
