{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.6-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "size": 1379885,
          "sha512": "e8771bab0400078e8c0dcbd6c64cf54e433daf8e490f909cec9ee0348b46a7495eac8d496e05e94e76d0121ef080801df94e7e6acb672d17e0cdd4907f17964e",
          "sha256": "196ad5ce1504a50dc051a7e00f62b49bf2f897112d9f7782ffb915cecf98e17e",
          "sha1": "41343d8ba428dce92c72afbb76d68ebdcf3732bc",
          "md5": "bc5f9ad0ccd5fedb8aabe1489e5c1899"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.6-EXPERIMENTAL.jar",
          "size": 1379885,
          "sha512": "e8771bab0400078e8c0dcbd6c64cf54e433daf8e490f909cec9ee0348b46a7495eac8d496e05e94e76d0121ef080801df94e7e6acb672d17e0cdd4907f17964e",
          "sha256": "196ad5ce1504a50dc051a7e00f62b49bf2f897112d9f7782ffb915cecf98e17e",
          "sha1": "41343d8ba428dce92c72afbb76d68ebdcf3732bc",
          "md5": "bc5f9ad0ccd5fedb8aabe1489e5c1899"
        }
      ]
    }
  ]
}
