{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.2.jar",
          "url": "runelite-api-1.0.2.jar",
          "size": 1372690,
          "sha512": "867e64811f7603dc66ded4088dbb93ab4d430b5ad72f847ce1e45f9479750042fab0b8c60f3da16f625739e92c73bcad10c22c6d0911e3de15ee3ca675f81175",
          "sha256": "31e3a747c74f0e576cb6689e78cf0c940d30ada4cc72c55969713914b7563c59",
          "sha1": "73a0ebd74a8d1eae38f36261fb6dc339f1da4261",
          "md5": "c84c629c8c4dc9f08a6f1db1591abd5a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.2.jar",
          "url": "runelite-api-1.0.2.jar",
          "size": 1372690,
          "sha512": "867e64811f7603dc66ded4088dbb93ab4d430b5ad72f847ce1e45f9479750042fab0b8c60f3da16f625739e92c73bcad10c22c6d0911e3de15ee3ca675f81175",
          "sha256": "31e3a747c74f0e576cb6689e78cf0c940d30ada4cc72c55969713914b7563c59",
          "sha1": "73a0ebd74a8d1eae38f36261fb6dc339f1da4261",
          "md5": "c84c629c8c4dc9f08a6f1db1591abd5a"
        }
      ]
    }
  ]
}
