{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.2.jar",
          "url": "runelite-api-1.0.2.jar",
          "size": 1378290,
          "sha512": "b58aadcdef98d3055317b46ab0a01b21c3f58548613bd1e2f8bdae12d06afea4ae1a8aeb6aff3b9bb4cbf58cc385c158f7d3a320e87aac28392e1439028d11b7",
          "sha256": "c3de7fb2f15545fff8344c6f1aa55bfa10bbbcb37a2c2322a78dbd9db294452d",
          "sha1": "58ae15a8eabfc90c27b7e7b370434c4ab9c7e490",
          "md5": "b0c31b58cb35e7d815aa529685f64357"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.2.jar",
          "url": "runelite-api-1.0.2.jar",
          "size": 1378290,
          "sha512": "b58aadcdef98d3055317b46ab0a01b21c3f58548613bd1e2f8bdae12d06afea4ae1a8aeb6aff3b9bb4cbf58cc385c158f7d3a320e87aac28392e1439028d11b7",
          "sha256": "c3de7fb2f15545fff8344c6f1aa55bfa10bbbcb37a2c2322a78dbd9db294452d",
          "sha1": "58ae15a8eabfc90c27b7e7b370434c4ab9c7e490",
          "md5": "b0c31b58cb35e7d815aa529685f64357"
        }
      ]
    }
  ]
}
