{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.0.1",
      "buildId": "46dnl4fwxnhrbe3sw23fax7rty"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "injector-plugin-1.1.2.jar",
          "url": "injector-plugin-1.1.2.jar",
          "size": 104287,
          "sha512": "3e95c890439d0336b4fff9c856169fcc46a291ada2901ea60ae3b0e1bb33ac36a1c8d2fed2255025735f5eadf5d8bb2403666437b2734cbb662a9338a5b677e3",
          "sha256": "bc59478d2ea3af0380e521a20f82b5d8c1520b34d771ca7bac710c966aab9fbf",
          "sha1": "65a4970b66211293cd9e169c3346e9966afdee98",
          "md5": "f8f731dab01d0c776aaae399fb9f694e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "injector-plugin-1.1.2.jar",
          "url": "injector-plugin-1.1.2.jar",
          "size": 104287,
          "sha512": "3e95c890439d0336b4fff9c856169fcc46a291ada2901ea60ae3b0e1bb33ac36a1c8d2fed2255025735f5eadf5d8bb2403666437b2734cbb662a9338a5b677e3",
          "sha256": "bc59478d2ea3af0380e521a20f82b5d8c1520b34d771ca7bac710c966aab9fbf",
          "sha1": "65a4970b66211293cd9e169c3346e9966afdee98",
          "md5": "f8f731dab01d0c776aaae399fb9f694e"
        }
      ]
    }
  ]
}
