{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91328,
          "sha512": "0ccb8d8a521b298dfbae3cbb1e6cdd34f60dfe07696f4cc6118df1031318cf2a941316c2edea19527ee27caf74bc53dc483e7eadaaf7a7d7aececef68fea7474",
          "sha256": "e7333478f5e5e1ab3d32ca58f789301eeed0554b7b44f28a78110ae372bb49bb",
          "sha1": "5cde9329361b3e8ae5717805426c3fc9cb887e36",
          "md5": "d8fd2fc55580c465c7475d5467fa6359"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91328,
          "sha512": "0ccb8d8a521b298dfbae3cbb1e6cdd34f60dfe07696f4cc6118df1031318cf2a941316c2edea19527ee27caf74bc53dc483e7eadaaf7a7d7aececef68fea7474",
          "sha256": "e7333478f5e5e1ab3d32ca58f789301eeed0554b7b44f28a78110ae372bb49bb",
          "sha1": "5cde9329361b3e8ae5717805426c3fc9cb887e36",
          "md5": "d8fd2fc55580c465c7475d5467fa6359"
        }
      ]
    }
  ]
}
