{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "b8ab6990cdf946c28a4d20d2192169da4950322ef9f04be7549b68423522deb27f91722563bda198b71bdc2527c468271bb2e9fb32d4cecd3eb427fad8bb8898",
          "sha256": "26752e85652c23e4fa910e48899dfa3d046f5fd72bd15ee33d54e54157fbca5c",
          "sha1": "728073c151a3e47bc47f62723810aa0b1f3989ac",
          "md5": "a5b1add0977794339ff609a8dbc1f613"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "b8ab6990cdf946c28a4d20d2192169da4950322ef9f04be7549b68423522deb27f91722563bda198b71bdc2527c468271bb2e9fb32d4cecd3eb427fad8bb8898",
          "sha256": "26752e85652c23e4fa910e48899dfa3d046f5fd72bd15ee33d54e54157fbca5c",
          "sha1": "728073c151a3e47bc47f62723810aa0b1f3989ac",
          "md5": "a5b1add0977794339ff609a8dbc1f613"
        }
      ]
    }
  ]
}
