{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "267f8ef1e348a29925308c2f12738d927f6c3abb5c9177d7de0b3ccf76792ce269ed8cd6250a45b7aa874d454b8b1af28bbe16f985f949462a5695ad6d0a4317",
          "sha256": "d216aee19eca2d32f55dceab5d460559bc4db66f08e937096a809159f125608f",
          "sha1": "c179be8adaf1d73152e251129652bc5cc7de19e2",
          "md5": "7960cdd70b89ba339bea96a76a470aa0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "267f8ef1e348a29925308c2f12738d927f6c3abb5c9177d7de0b3ccf76792ce269ed8cd6250a45b7aa874d454b8b1af28bbe16f985f949462a5695ad6d0a4317",
          "sha256": "d216aee19eca2d32f55dceab5d460559bc4db66f08e937096a809159f125608f",
          "sha1": "c179be8adaf1d73152e251129652bc5cc7de19e2",
          "md5": "7960cdd70b89ba339bea96a76a470aa0"
        }
      ]
    }
  ]
}
