{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "897906f1161afaacf6a90412889ed78d118186f1781ee45ae0a5d2c152f87c78696bdf4ccaf96d950561ba3367fd218724e6e8f50d3f2f8e74d2bd732ba08102",
          "sha256": "769f8cf76fc5a34d7be43457e2a14f42290468b109216b5eba35677695ffc616",
          "sha1": "1084534590c9bd66b75a4c691a3457c60906c55a",
          "md5": "32338ffdd08606e6d222a2dab084818c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "897906f1161afaacf6a90412889ed78d118186f1781ee45ae0a5d2c152f87c78696bdf4ccaf96d950561ba3367fd218724e6e8f50d3f2f8e74d2bd732ba08102",
          "sha256": "769f8cf76fc5a34d7be43457e2a14f42290468b109216b5eba35677695ffc616",
          "sha1": "1084534590c9bd66b75a4c691a3457c60906c55a",
          "md5": "32338ffdd08606e6d222a2dab084818c"
        }
      ]
    }
  ]
}
