{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91330,
          "sha512": "dd9d28a4c32c2f3f8e178333e7ae38e5ce145103a8115022f4fc74d06c1121b3a2e6522e775835b174c9bc5cf2729e19ebab8b44c183438b6ccc6fbb451c646b",
          "sha256": "f6be651dea45dad25a2621f94233072a935d90c0284f3fd15636f05f8b67641f",
          "sha1": "b11ac3accf239753636dfc712336e5c60617d8e8",
          "md5": "65eedd271029dc5d6f135e44dc273b1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91330,
          "sha512": "dd9d28a4c32c2f3f8e178333e7ae38e5ce145103a8115022f4fc74d06c1121b3a2e6522e775835b174c9bc5cf2729e19ebab8b44c183438b6ccc6fbb451c646b",
          "sha256": "f6be651dea45dad25a2621f94233072a935d90c0284f3fd15636f05f8b67641f",
          "sha1": "b11ac3accf239753636dfc712336e5c60617d8e8",
          "md5": "65eedd271029dc5d6f135e44dc273b1f"
        }
      ]
    }
  ]
}
