{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "6636b261b8a66150849f17b0097250139cbfe5e7d74d58d912c2074c80385314880dd6b26cb926903c10d323b7709a1e13ecabf4621654d0e183e3dfd7deafd4",
          "sha256": "19f4932d2f13ee4b81285f003aedd81c9274204dd746a3b67e1159ae8d145d06",
          "sha1": "1a62a3a4d6eab8ea82f724f8ebb5fdaef0af0498",
          "md5": "40cd9723dc0912c0008f02cf7eb22ad4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "6636b261b8a66150849f17b0097250139cbfe5e7d74d58d912c2074c80385314880dd6b26cb926903c10d323b7709a1e13ecabf4621654d0e183e3dfd7deafd4",
          "sha256": "19f4932d2f13ee4b81285f003aedd81c9274204dd746a3b67e1159ae8d145d06",
          "sha1": "1a62a3a4d6eab8ea82f724f8ebb5fdaef0af0498",
          "md5": "40cd9723dc0912c0008f02cf7eb22ad4"
        }
      ]
    }
  ]
}
