{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91330,
          "sha512": "becb248b7d4d6020eb070b31ca89a6775c0789792c32be7c9ee7d384f0ce6a99349395df0fc5ba4fd7a2c0f384932049a0cbab7f7a3b7899b46c54eb8a21af78",
          "sha256": "730cddb57d2f1a2b2e3dbee7d3506f3fabe0621932b565aeea550ecd6e92592c",
          "sha1": "2a87ae2305d87bd6d20961b56b9e0962ae594006",
          "md5": "7a68d4c56141000d91aef27eb4e1214b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91330,
          "sha512": "becb248b7d4d6020eb070b31ca89a6775c0789792c32be7c9ee7d384f0ce6a99349395df0fc5ba4fd7a2c0f384932049a0cbab7f7a3b7899b46c54eb8a21af78",
          "sha256": "730cddb57d2f1a2b2e3dbee7d3506f3fabe0621932b565aeea550ecd6e92592c",
          "sha1": "2a87ae2305d87bd6d20961b56b9e0962ae594006",
          "md5": "7a68d4c56141000d91aef27eb4e1214b"
        }
      ]
    }
  ]
}
