{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91330,
          "sha512": "0ba221184733ef88c47fa38009cf97653f47f8325005d46d28bf573befdc1de617482ab330d152ce8cf4f13b3bebfe3da306f281fc86895dbfcd38c34558d878",
          "sha256": "ff09d7adad847996f743efa23ba68acf76400a6531a8ae3da7b913c2dad1a073",
          "sha1": "f63f913fb74827428a62ad03224848a7c0999969",
          "md5": "ea542febdcdef5e461785b7bfbadea79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91330,
          "sha512": "0ba221184733ef88c47fa38009cf97653f47f8325005d46d28bf573befdc1de617482ab330d152ce8cf4f13b3bebfe3da306f281fc86895dbfcd38c34558d878",
          "sha256": "ff09d7adad847996f743efa23ba68acf76400a6531a8ae3da7b913c2dad1a073",
          "sha1": "f63f913fb74827428a62ad03224848a7c0999969",
          "md5": "ea542febdcdef5e461785b7bfbadea79"
        }
      ]
    }
  ]
}
