{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "3a8652fc161fd1094c74c4f194a5861e7cc32d5e3bd06c706fb24a99d30ebaa23e9779573165ab9bc31fed465136a1e6ffaad951d2cfe4f03f0a2a0a90dea15d",
          "sha256": "f08f43feeb4d9981dcd26518d72e29144c3f0ebd50b5361018b6a12ab59a7cb1",
          "sha1": "110e56f9060f0b40778f3cf8cf052266908d78ac",
          "md5": "b26b133352e62c704a263a914944b0bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "3a8652fc161fd1094c74c4f194a5861e7cc32d5e3bd06c706fb24a99d30ebaa23e9779573165ab9bc31fed465136a1e6ffaad951d2cfe4f03f0a2a0a90dea15d",
          "sha256": "f08f43feeb4d9981dcd26518d72e29144c3f0ebd50b5361018b6a12ab59a7cb1",
          "sha1": "110e56f9060f0b40778f3cf8cf052266908d78ac",
          "md5": "b26b133352e62c704a263a914944b0bf"
        }
      ]
    }
  ]
}
