{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91330,
          "sha512": "29b1b9348c6656e33eceba46c321621d8a41fb40e4cfc994a73b5088b5539130a0dce74685f0dc18a4db2d54dc34b3def76760c7fca2b48054ee101c380b7ca8",
          "sha256": "7e1e907ef1ced53f79def3a7dd5cae197b62694d30210e0e771ffdb0b40cff62",
          "sha1": "6f0a2376f3082b02028aa4c24ac43b4d7c6da064",
          "md5": "4cce0948a750284cb3c5f27f3d025054"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91330,
          "sha512": "29b1b9348c6656e33eceba46c321621d8a41fb40e4cfc994a73b5088b5539130a0dce74685f0dc18a4db2d54dc34b3def76760c7fca2b48054ee101c380b7ca8",
          "sha256": "7e1e907ef1ced53f79def3a7dd5cae197b62694d30210e0e771ffdb0b40cff62",
          "sha1": "6f0a2376f3082b02028aa4c24ac43b4d7c6da064",
          "md5": "4cce0948a750284cb3c5f27f3d025054"
        }
      ]
    }
  ]
}
