{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "da00133618b3a6f5de76f875d44cc759542aa683028ada0c29169df7558774d7dc9066f0bb92b93b568dec4ddfd0794750690c06ab4cb50fc34f0ab8ee47b83c",
          "sha256": "58e1afdcc4623f11db11f5914c9a62d3c0ea96fc5dcc26594069e6a94e7ce977",
          "sha1": "9d4753a679330ef613821b0c6f170e7ea0b1f2c2",
          "md5": "be8e6e0d15201d4f821fab5165b41e01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "da00133618b3a6f5de76f875d44cc759542aa683028ada0c29169df7558774d7dc9066f0bb92b93b568dec4ddfd0794750690c06ab4cb50fc34f0ab8ee47b83c",
          "sha256": "58e1afdcc4623f11db11f5914c9a62d3c0ea96fc5dcc26594069e6a94e7ce977",
          "sha1": "9d4753a679330ef613821b0c6f170e7ea0b1f2c2",
          "md5": "be8e6e0d15201d4f821fab5165b41e01"
        }
      ]
    }
  ]
}
