{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "5824baa37d4ffbf1a16507f7f38ba408db7af7a17be1362cad9b449fcef0f8eab3791465af1b7a5a132ed3b6d3ca230c4b16f3fea05b5666a33e068c38a90cdf",
          "sha256": "4c52ec2c155c7ca6e9b9d30e856632fc7cbe5f2c184230b89bcac98b114a4cce",
          "sha1": "8d288d2a13734a701ec5c4c079618653480a99d3",
          "md5": "4c8c78d452a6bc2896e08df3927898cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.8-SNAPSHOT.jar",
          "url": "http-api-1.0.8-SNAPSHOT.jar",
          "size": 91329,
          "sha512": "5824baa37d4ffbf1a16507f7f38ba408db7af7a17be1362cad9b449fcef0f8eab3791465af1b7a5a132ed3b6d3ca230c4b16f3fea05b5666a33e068c38a90cdf",
          "sha256": "4c52ec2c155c7ca6e9b9d30e856632fc7cbe5f2c184230b89bcac98b114a4cce",
          "sha1": "8d288d2a13734a701ec5c4c079618653480a99d3",
          "md5": "4c8c78d452a6bc2896e08df3927898cc"
        }
      ]
    }
  ]
}
