{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4.jar",
          "url": "http-api-1.0.4.jar",
          "size": 85931,
          "sha512": "980d97464aaeebf1a44547b9a3c900315e93fd26afe7306790f256ffa1a75b39dc71733d62c312212672d7ba44ed3b2ca90ef3e2a911372319e39d4fbb259295",
          "sha256": "e5bb32b3a0d2b3cfd860aaf159320cf4d78ea085caa5eb3c07c89ec9da0b17d9",
          "sha1": "524bc4d43fb76cc17294cd699b38fa685eda9281",
          "md5": "c42debca3fca51bf250ae10257d94b30"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4.jar",
          "url": "http-api-1.0.4.jar",
          "size": 85931,
          "sha512": "980d97464aaeebf1a44547b9a3c900315e93fd26afe7306790f256ffa1a75b39dc71733d62c312212672d7ba44ed3b2ca90ef3e2a911372319e39d4fbb259295",
          "sha256": "e5bb32b3a0d2b3cfd860aaf159320cf4d78ea085caa5eb3c07c89ec9da0b17d9",
          "sha1": "524bc4d43fb76cc17294cd699b38fa685eda9281",
          "md5": "c42debca3fca51bf250ae10257d94b30"
        }
      ]
    }
  ]
}
