{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4.jar",
          "url": "http-api-1.0.4.jar",
          "size": 85931,
          "sha512": "e3923d18144dd281a32a1173ae7feebe9d99250ceded6b720d611863d662814988332753fab46b68643768f672056f0f2bb3d294e356a2fbf6daa03cbaa15a20",
          "sha256": "853da20fcb16b24572a82eb7b0cebbb21d26beece4e24f27e4df7da2982b1163",
          "sha1": "342126fdf0629db1cc900028d9d55c70044a16ca",
          "md5": "a524cf9f0e5367ac8014b7dfdc122821"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4.jar",
          "url": "http-api-1.0.4.jar",
          "size": 85931,
          "sha512": "e3923d18144dd281a32a1173ae7feebe9d99250ceded6b720d611863d662814988332753fab46b68643768f672056f0f2bb3d294e356a2fbf6daa03cbaa15a20",
          "sha256": "853da20fcb16b24572a82eb7b0cebbb21d26beece4e24f27e4df7da2982b1163",
          "sha1": "342126fdf0629db1cc900028d9d55c70044a16ca",
          "md5": "a524cf9f0e5367ac8014b7dfdc122821"
        }
      ]
    }
  ]
}
