{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1359670,
          "sha512": "730e9020b666ac27502c1dc3abb3bb9b402f772624c58c0ab2bf3350be82e07ffc054d92484135f182d89dbafd2886876fadc02f15cb279055560b4bb213a5a5",
          "sha256": "fcd13c733706a94127ac5dbb4a6fd1cf2af331b11b49853e03048536159ab2f4",
          "sha1": "9f24ce4bdf8eaa60a351eca52bedc52c065f5672",
          "md5": "85ce03570f2f253fca0fec51b8f3f489"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1359670,
          "sha512": "730e9020b666ac27502c1dc3abb3bb9b402f772624c58c0ab2bf3350be82e07ffc054d92484135f182d89dbafd2886876fadc02f15cb279055560b4bb213a5a5",
          "sha256": "fcd13c733706a94127ac5dbb4a6fd1cf2af331b11b49853e03048536159ab2f4",
          "sha1": "9f24ce4bdf8eaa60a351eca52bedc52c065f5672",
          "md5": "85ce03570f2f253fca0fec51b8f3f489"
        }
      ]
    }
  ]
}
