{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1357641,
          "sha512": "23668e30ede36d44a5a83aa9c80a25b0db53ec15e0366884560003eb82e12dfdbdee86de8a4d8a94837c1d94f3a1a6fe6b608222c6a960e283c351c48334dbed",
          "sha256": "f9afbd3e5b7cc8ce4c48f98ab79d297bc09dfd98fe1ab0bcbf56ea5b5eaf357c",
          "sha1": "109d683f94292dd290d846487342c49484d45cdd",
          "md5": "29bc15c402cf92c2a9b43c1c2ae009e4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1357641,
          "sha512": "23668e30ede36d44a5a83aa9c80a25b0db53ec15e0366884560003eb82e12dfdbdee86de8a4d8a94837c1d94f3a1a6fe6b608222c6a960e283c351c48334dbed",
          "sha256": "f9afbd3e5b7cc8ce4c48f98ab79d297bc09dfd98fe1ab0bcbf56ea5b5eaf357c",
          "sha1": "109d683f94292dd290d846487342c49484d45cdd",
          "md5": "29bc15c402cf92c2a9b43c1c2ae009e4"
        }
      ]
    }
  ]
}
