{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1356054,
          "sha512": "c2d52288d2b67c63bfba5e80ba46acca14b95a6d82b750587bb79e1388b07887e8e85231ef3aaeb33ebe734773b84e9fc4954e54fcaeaee0d35e208323ace74b",
          "sha256": "c892ccfc0d22ce02f3b71f51db81cdc71ddde812362fcd09acf38abd26526d4d",
          "sha1": "ecc90d04b5ff3099c432c6f7e049e475c6cae13f",
          "md5": "7af74cfc8a12347b77709bea2c2876f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1356054,
          "sha512": "c2d52288d2b67c63bfba5e80ba46acca14b95a6d82b750587bb79e1388b07887e8e85231ef3aaeb33ebe734773b84e9fc4954e54fcaeaee0d35e208323ace74b",
          "sha256": "c892ccfc0d22ce02f3b71f51db81cdc71ddde812362fcd09acf38abd26526d4d",
          "sha1": "ecc90d04b5ff3099c432c6f7e049e475c6cae13f",
          "md5": "7af74cfc8a12347b77709bea2c2876f9"
        }
      ]
    }
  ]
}
