{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1357588,
          "sha512": "f8a33e7e3909fc3909b69e324eb32140000a69ec993a4d44786f803723a6a201cfe9d3287e9d3ef3f6be722d3afde9a9e027f0c5b1efd9451a3585fc6f3ee6d7",
          "sha256": "b7e0b27aea47f2975f61cbbec7d4046f1808d17a0c99ed181205729d3f3691b6",
          "sha1": "31fa14866d635a6b9d014f2ce0fb3255b6396a06",
          "md5": "516b49a20ead19a4e10296bf662289a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1357588,
          "sha512": "f8a33e7e3909fc3909b69e324eb32140000a69ec993a4d44786f803723a6a201cfe9d3287e9d3ef3f6be722d3afde9a9e027f0c5b1efd9451a3585fc6f3ee6d7",
          "sha256": "b7e0b27aea47f2975f61cbbec7d4046f1808d17a0c99ed181205729d3f3691b6",
          "sha1": "31fa14866d635a6b9d014f2ce0fb3255b6396a06",
          "md5": "516b49a20ead19a4e10296bf662289a2"
        }
      ]
    }
  ]
}
