{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1357451,
          "sha512": "e36351689793eb630c2e0fc4f8fdcf2aa0f8b39855c8d2811703e0ad8d13c731de6f921ee3f693eb73f8f63018ca8fd1a12e9ed06566509ecfc33aab0b68f1fb",
          "sha256": "7ed3453f8a116939851dd0a3206435e2991ef5031b41784414b27f4ee828fd7c",
          "sha1": "eacc83bc4ba11e1882aef6f1a3775890a973e091",
          "md5": "56f110a85491e4d0465f78ff36775c45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1357451,
          "sha512": "e36351689793eb630c2e0fc4f8fdcf2aa0f8b39855c8d2811703e0ad8d13c731de6f921ee3f693eb73f8f63018ca8fd1a12e9ed06566509ecfc33aab0b68f1fb",
          "sha256": "7ed3453f8a116939851dd0a3206435e2991ef5031b41784414b27f4ee828fd7c",
          "sha1": "eacc83bc4ba11e1882aef6f1a3775890a973e091",
          "md5": "56f110a85491e4d0465f78ff36775c45"
        }
      ]
    }
  ]
}
