{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1357345,
          "sha512": "b62b7ace4c38d4f33ec544970b868f46279909a947acad1f09c63610986dbf29209b74c4dead2b431e461bc9d99ce56cfaef1490a55a5a94d975bf79ecbdad48",
          "sha256": "aae2cd36905009f76d5798a5bef69d4b5d8aaeea6a1b6d81afdf0d95620ef7a0",
          "sha1": "b64e834b1e650d6754e5753bdb96ee4a7831598f",
          "md5": "82fa00457bb5078d1f75ef6c08a96d7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.26.1-SNAPSHOT.jar",
          "url": "runelite-api-4.26.1-SNAPSHOT.jar",
          "size": 1357345,
          "sha512": "b62b7ace4c38d4f33ec544970b868f46279909a947acad1f09c63610986dbf29209b74c4dead2b431e461bc9d99ce56cfaef1490a55a5a94d975bf79ecbdad48",
          "sha256": "aae2cd36905009f76d5798a5bef69d4b5d8aaeea6a1b6d81afdf0d95620ef7a0",
          "sha1": "b64e834b1e650d6754e5753bdb96ee4a7831598f",
          "md5": "82fa00457bb5078d1f75ef6c08a96d7c"
        }
      ]
    }
  ]
}
