{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 88825,
          "sha512": "e3188bd5462bb119eb227de134363cf862672290b0794477432b23a5c71c2b5569c494cad77613381fb9b9e8ddbff4fe5a86992713b801fd3cc36e8e94f57fda",
          "sha256": "6efcafa563512059809e67550f04d70471cfd515653fb91980cf704a1ca08852",
          "sha1": "07405fdecfe7daffe1e6d13f3628f4285e4705d9",
          "md5": "c03a7abfa8d757e9a83329b8707a858b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 88825,
          "sha512": "e3188bd5462bb119eb227de134363cf862672290b0794477432b23a5c71c2b5569c494cad77613381fb9b9e8ddbff4fe5a86992713b801fd3cc36e8e94f57fda",
          "sha256": "6efcafa563512059809e67550f04d70471cfd515653fb91980cf704a1ca08852",
          "sha1": "07405fdecfe7daffe1e6d13f3628f4285e4705d9",
          "md5": "c03a7abfa8d757e9a83329b8707a858b"
        }
      ]
    }
  ]
}
