{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "d672fbe5b434a4aae37bb8237b00683b1db3884ba1072d0cb57dd58f9645e55bcd1e460808ba8a83bee9a7f7ae0a68108f3185824b874422033420c97711d912",
          "sha256": "79873ee79d99ad93088bccafead318d72a1cbe3600ebec40b7ad80b66c939114",
          "sha1": "8d36be0775835fff166dba2666fb6c9ebf78365b",
          "md5": "abf65bb834ef47e7daab02fe99d571d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "d672fbe5b434a4aae37bb8237b00683b1db3884ba1072d0cb57dd58f9645e55bcd1e460808ba8a83bee9a7f7ae0a68108f3185824b874422033420c97711d912",
          "sha256": "79873ee79d99ad93088bccafead318d72a1cbe3600ebec40b7ad80b66c939114",
          "sha1": "8d36be0775835fff166dba2666fb6c9ebf78365b",
          "md5": "abf65bb834ef47e7daab02fe99d571d8"
        }
      ]
    }
  ]
}
