{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "86461912e90a91b08570075fa9d08a41ce628f68cf54155306e696c6aed09ddcd452d8de78f2481ca60f042e06f5290cbf52f5b2091eaace6dce008b603ffa7d",
          "sha256": "f3334b7ee5f422e5e768b79309293a87e5aaea7c012183c9eb3f2d7a82c74561",
          "sha1": "0acbe340341686f0544d213b99e4053e75ed1cde",
          "md5": "ddf5de914908146fb55568921e41996c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "86461912e90a91b08570075fa9d08a41ce628f68cf54155306e696c6aed09ddcd452d8de78f2481ca60f042e06f5290cbf52f5b2091eaace6dce008b603ffa7d",
          "sha256": "f3334b7ee5f422e5e768b79309293a87e5aaea7c012183c9eb3f2d7a82c74561",
          "sha1": "0acbe340341686f0544d213b99e4053e75ed1cde",
          "md5": "ddf5de914908146fb55568921e41996c"
        }
      ]
    }
  ]
}
