{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "19188e681e963f75c7abd9a7e12be75a8a332bfb807e89bbb08ced0575b69cb8256dadb3daa456e4f1cf6b87d081c8115b27c9e276a8cb902fea25f05343e3ba",
          "sha256": "ad5574ca2854abba2906f44c61891d40e2a9de11d2e36cc53ac236cd42ff1770",
          "sha1": "fc37a64b487b13554af1111101b704b18b86dee2",
          "md5": "be77ec262e02ffa7cc5ff89edc0187d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "19188e681e963f75c7abd9a7e12be75a8a332bfb807e89bbb08ced0575b69cb8256dadb3daa456e4f1cf6b87d081c8115b27c9e276a8cb902fea25f05343e3ba",
          "sha256": "ad5574ca2854abba2906f44c61891d40e2a9de11d2e36cc53ac236cd42ff1770",
          "sha1": "fc37a64b487b13554af1111101b704b18b86dee2",
          "md5": "be77ec262e02ffa7cc5ff89edc0187d9"
        }
      ]
    }
  ]
}
