{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "64509c7a2e40224bf0a47410a56d68f5b0de1c112e2927a0f2bc5d1ea33eaa241119c1c618ac7d6cb978aa1316f429decc6ad3badd9eaa06772db31bef3ecae6",
          "sha256": "7d57f51fb292e6f3147766f2bf5eca76829ea86d91c29b18c803ea38c7e9648a",
          "sha1": "7f16061be9add601a75950499f53dbaab2176fc2",
          "md5": "cbc4acc1be99aa7c4adacd354071c9b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "64509c7a2e40224bf0a47410a56d68f5b0de1c112e2927a0f2bc5d1ea33eaa241119c1c618ac7d6cb978aa1316f429decc6ad3badd9eaa06772db31bef3ecae6",
          "sha256": "7d57f51fb292e6f3147766f2bf5eca76829ea86d91c29b18c803ea38c7e9648a",
          "sha1": "7f16061be9add601a75950499f53dbaab2176fc2",
          "md5": "cbc4acc1be99aa7c4adacd354071c9b6"
        }
      ]
    }
  ]
}
