{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "e74752764cce10586845757d0445547f3bc7ceed456a1fc43a75119f5eec32be5b47373fde984c6aa5ff91ecc3a606ea08309cd3ba466238a2a7092f720de4a5",
          "sha256": "6b1cfbfaa9e3558a414de1324778c911500abdce1eccb47e08855b5655c2f874",
          "sha1": "315aa424dac0e33a3658f2b0ab889c8b0d5cac18",
          "md5": "d4a37438609bc4c06a8909fe150d84de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "e74752764cce10586845757d0445547f3bc7ceed456a1fc43a75119f5eec32be5b47373fde984c6aa5ff91ecc3a606ea08309cd3ba466238a2a7092f720de4a5",
          "sha256": "6b1cfbfaa9e3558a414de1324778c911500abdce1eccb47e08855b5655c2f874",
          "sha1": "315aa424dac0e33a3658f2b0ab889c8b0d5cac18",
          "md5": "d4a37438609bc4c06a8909fe150d84de"
        }
      ]
    }
  ]
}
