{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "4ce8ca5b873e1ed661358d443a3d9c7aa616410863b7cd40d11d5cc8e3c0e792357eb97c2da35b3db0b5a5a88651e4ce82b1d9aaff3c4f345b18ffb65c886207",
          "sha256": "d9f35441d8ae935707129f2c342405de3d52edfede5c83a9b75c718e78a7fc2a",
          "sha1": "d533436f5064f4b95523c2472154a206b1a774e4",
          "md5": "f027962b76e2af510c06f94199dd37f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "4ce8ca5b873e1ed661358d443a3d9c7aa616410863b7cd40d11d5cc8e3c0e792357eb97c2da35b3db0b5a5a88651e4ce82b1d9aaff3c4f345b18ffb65c886207",
          "sha256": "d9f35441d8ae935707129f2c342405de3d52edfede5c83a9b75c718e78a7fc2a",
          "sha1": "d533436f5064f4b95523c2472154a206b1a774e4",
          "md5": "f027962b76e2af510c06f94199dd37f0"
        }
      ]
    }
  ]
}
