{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "9dab582139e43aea7c882ce3cb0aa63237325fbea934546bc9328050d74203303b67e077da991747fd523a97ef9275fe3339878f5d6825a114cba775888edc54",
          "sha256": "46d1576328104700b7c17f882f74e1de022717cbfdc21f7a784ce51f74f4977f",
          "sha1": "9de9b9b2dacd27de42ee361616ea76a0e0c4a79d",
          "md5": "2e69b12b834eb5048377421b8b7b0ddb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "9dab582139e43aea7c882ce3cb0aa63237325fbea934546bc9328050d74203303b67e077da991747fd523a97ef9275fe3339878f5d6825a114cba775888edc54",
          "sha256": "46d1576328104700b7c17f882f74e1de022717cbfdc21f7a784ce51f74f4977f",
          "sha1": "9de9b9b2dacd27de42ee361616ea76a0e0c4a79d",
          "md5": "2e69b12b834eb5048377421b8b7b0ddb"
        }
      ]
    }
  ]
}
