{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "ea1724faf5cb17cc59beff29d883ae90b518786c06791c4b1e04acda1554886505d4738dfa9a4468bd6ff3a0742ebf9a6e4ed85bc3e02afa038d7584aa40f00c",
          "sha256": "dbe7a339939b315339eebb31cf72631da44f653e65caeab2472dd21157096e63",
          "sha1": "f965dd004bb2316d8d394ae62bd50bbd9d8a351c",
          "md5": "d6f3253067845515a36d0356df03d7f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "ea1724faf5cb17cc59beff29d883ae90b518786c06791c4b1e04acda1554886505d4738dfa9a4468bd6ff3a0742ebf9a6e4ed85bc3e02afa038d7584aa40f00c",
          "sha256": "dbe7a339939b315339eebb31cf72631da44f653e65caeab2472dd21157096e63",
          "sha1": "f965dd004bb2316d8d394ae62bd50bbd9d8a351c",
          "md5": "d6f3253067845515a36d0356df03d7f1"
        }
      ]
    }
  ]
}
