{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "d416e438ca5c1a70a77306dcc047b9f52d8eb12207127833e8106368acb319edacfd7238aef8d377d9c3e1906bd7ba82992386d11874ade3ef29d467aa7fca45",
          "sha256": "dbed32090ba4314f9b7b974123242c0d710e7ec242f5f9692431cd1b59458545",
          "sha1": "b4ba9d87ddb9ed5fdaaa828f5a5a183a85df45bd",
          "md5": "f067898e33362aa6785514469f32fd2c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "d416e438ca5c1a70a77306dcc047b9f52d8eb12207127833e8106368acb319edacfd7238aef8d377d9c3e1906bd7ba82992386d11874ade3ef29d467aa7fca45",
          "sha256": "dbed32090ba4314f9b7b974123242c0d710e7ec242f5f9692431cd1b59458545",
          "sha1": "b4ba9d87ddb9ed5fdaaa828f5a5a183a85df45bd",
          "md5": "f067898e33362aa6785514469f32fd2c"
        }
      ]
    }
  ]
}
