{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "90902c17d267ec8893f3b969cf1377a9390ac4863d8fedebeb85931c9701d745b39e9133ce640fb9ae2eed83227735609483e60c026aa840a0726c4f3d091d2e",
          "sha256": "6934177ffc20ca6d257ca8b0d9cbbfd57865c4e135247103f0982f0a66094d36",
          "sha1": "2e3673a0827d02e40908593f7552e6c0a3b7f5a2",
          "md5": "3838dbff204203024c0d009ed6f55e19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "90902c17d267ec8893f3b969cf1377a9390ac4863d8fedebeb85931c9701d745b39e9133ce640fb9ae2eed83227735609483e60c026aa840a0726c4f3d091d2e",
          "sha256": "6934177ffc20ca6d257ca8b0d9cbbfd57865c4e135247103f0982f0a66094d36",
          "sha1": "2e3673a0827d02e40908593f7552e6c0a3b7f5a2",
          "md5": "3838dbff204203024c0d009ed6f55e19"
        }
      ]
    }
  ]
}
