{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "72037187c13ad2e5d942329495a28e497b347fd19017352d9b8c47146f382a1560c8caf69b2ea79722d822367779f14e45c55a396a4f6bf68d798f4af4784512",
          "sha256": "5f4f5ba8713f6b458a031bcef7ee2d969291566326ed80e756d68209f917e91f",
          "sha1": "3d13f2caff50c9e398733f89248e11e82f5d5cbe",
          "md5": "ee5e504c41d7cdf042cf535f456f33f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "72037187c13ad2e5d942329495a28e497b347fd19017352d9b8c47146f382a1560c8caf69b2ea79722d822367779f14e45c55a396a4f6bf68d798f4af4784512",
          "sha256": "5f4f5ba8713f6b458a031bcef7ee2d969291566326ed80e756d68209f917e91f",
          "sha1": "3d13f2caff50c9e398733f89248e11e82f5d5cbe",
          "md5": "ee5e504c41d7cdf042cf535f456f33f4"
        }
      ]
    }
  ]
}
