{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "2b872a04aa17738c2785cb7941c1058bb03ed12f57dcc4b89eb1ade3353293c7bb2710cead6b386d6f4e153940d5fe238d36b1a38156c718a5dc51f91013984e",
          "sha256": "693c2a6fcf947a3599a8daed6ab50b5208274b1790364f636462f9acf62d6b79",
          "sha1": "9fe48ef21938b4149094c966960791637624260d",
          "md5": "5e6113e974a8e8e9ad0403971ac154f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "2b872a04aa17738c2785cb7941c1058bb03ed12f57dcc4b89eb1ade3353293c7bb2710cead6b386d6f4e153940d5fe238d36b1a38156c718a5dc51f91013984e",
          "sha256": "693c2a6fcf947a3599a8daed6ab50b5208274b1790364f636462f9acf62d6b79",
          "sha1": "9fe48ef21938b4149094c966960791637624260d",
          "md5": "5e6113e974a8e8e9ad0403971ac154f1"
        }
      ]
    }
  ]
}
