{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "25a6306f5a43c4a76632821c537a1d10bf43ffa0bbb8c3f7ff67cf3997fc574da694289064595425cef8011731dfedbff1b62af005936b0d6a284fdca3035661",
          "sha256": "6d184dc15545007b0783025e46de80ec0e6e7843c4e3ab1d1ad9b8c77cea0273",
          "sha1": "9a4e9f6682c14e3910b99dbaa72fabc7f57dca82",
          "md5": "7dc53cfaf6470ecdc304e6547803f7fa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "25a6306f5a43c4a76632821c537a1d10bf43ffa0bbb8c3f7ff67cf3997fc574da694289064595425cef8011731dfedbff1b62af005936b0d6a284fdca3035661",
          "sha256": "6d184dc15545007b0783025e46de80ec0e6e7843c4e3ab1d1ad9b8c77cea0273",
          "sha1": "9a4e9f6682c14e3910b99dbaa72fabc7f57dca82",
          "md5": "7dc53cfaf6470ecdc304e6547803f7fa"
        }
      ]
    }
  ]
}
