{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85930,
          "sha512": "a2c0f1a07917ee7fa2a74378b1c35733dcf56c2680d795309271c1348cfb9dc7599d10f262518e2d18f1e13fc0e90bf351b348c5fade7dedf0844f0292796d09",
          "sha256": "27b74cc880a334873c9851d7779e1672d9c7988b03f70a53917554ae86319711",
          "sha1": "c988c38e281343259ca4eb03e15c545ea0aff655",
          "md5": "5ce3a5450e7a9cad24e92bb342a61fb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85930,
          "sha512": "a2c0f1a07917ee7fa2a74378b1c35733dcf56c2680d795309271c1348cfb9dc7599d10f262518e2d18f1e13fc0e90bf351b348c5fade7dedf0844f0292796d09",
          "sha256": "27b74cc880a334873c9851d7779e1672d9c7988b03f70a53917554ae86319711",
          "sha1": "c988c38e281343259ca4eb03e15c545ea0aff655",
          "md5": "5ce3a5450e7a9cad24e92bb342a61fb2"
        }
      ]
    }
  ]
}
