{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "cfcf66fc7306374f064822af2d256402c7e27fa3f1ce4c94346b181438503563dc77dbfb58a4a3521d7ab25152d3701d85235d13eb298d7f8334419f30c40961",
          "sha256": "07c9e53712de29c9692c46a5388c1842ce49115a435bf955a8b61077bcc3ef5d",
          "sha1": "84e065d2da0a8f16130d3a277d2cdf5c4f6a18a9",
          "md5": "9e8a53e944595e626aef89a9d2c58b42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-SNAPSHOT.jar",
          "url": "http-api-1.0.4-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "cfcf66fc7306374f064822af2d256402c7e27fa3f1ce4c94346b181438503563dc77dbfb58a4a3521d7ab25152d3701d85235d13eb298d7f8334419f30c40961",
          "sha256": "07c9e53712de29c9692c46a5388c1842ce49115a435bf955a8b61077bcc3ef5d",
          "sha1": "84e065d2da0a8f16130d3a277d2cdf5c4f6a18a9",
          "md5": "9e8a53e944595e626aef89a9d2c58b42"
        }
      ]
    }
  ]
}
