{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "deobfuscator",
    "version": "4.31.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "deobfuscator-4.31.1.jar",
          "url": "deobfuscator-4.31.1.jar",
          "size": 557261,
          "sha512": "50ef47202ad67f13c4f302821d65747a34492af4eebc0563cda518e0d05b7d8c5f2d58fd2f3ecde8480517aff965daa142328f60c924cb7e5ed10141a7a5dbd6",
          "sha256": "5a30233cb15646980356a5a9b511022015a9c4293a4deadb5cdee5743fed3ee9",
          "sha1": "27dd6c6853b2022bf8954f1a345513b3d58b3e30",
          "md5": "16171d36008718217aaa5e09003fc69e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "com.openosrs.rs",
          "module": "runescape-api",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "net.runelite",
          "module": "fernflower",
          "version": {
            "requires": "07082019"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-simple",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "deobfuscator-4.31.1.jar",
          "url": "deobfuscator-4.31.1.jar",
          "size": 557261,
          "sha512": "50ef47202ad67f13c4f302821d65747a34492af4eebc0563cda518e0d05b7d8c5f2d58fd2f3ecde8480517aff965daa142328f60c924cb7e5ed10141a7a5dbd6",
          "sha256": "5a30233cb15646980356a5a9b511022015a9c4293a4deadb5cdee5743fed3ee9",
          "sha1": "27dd6c6853b2022bf8954f1a345513b3d58b3e30",
          "md5": "16171d36008718217aaa5e09003fc69e"
        }
      ]
    }
  ]
}
