{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "d85f8dec4fb4239d00ba08ec48e628b65afd0c256686eee3d326e6c0414446438e5fe1c37a5a1b81ba63bc1e7671ae2eb277ad4b227cf631b5418f26943e13e6",
          "sha256": "3d2980271134bc305717aa82fda1908613b510c711a22bc72e1a53a4572be700",
          "sha1": "4dbb7c7cfadee20db51537519a69b576af0d023e",
          "md5": "7699f83124efdd25c354eac026992349"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "d85f8dec4fb4239d00ba08ec48e628b65afd0c256686eee3d326e6c0414446438e5fe1c37a5a1b81ba63bc1e7671ae2eb277ad4b227cf631b5418f26943e13e6",
          "sha256": "3d2980271134bc305717aa82fda1908613b510c711a22bc72e1a53a4572be700",
          "sha1": "4dbb7c7cfadee20db51537519a69b576af0d023e",
          "md5": "7699f83124efdd25c354eac026992349"
        }
      ]
    }
  ]
}
