{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "c6eb84084fdffd197f8e539da204a2b6ce4721158dda98e5667fc7335799b60a0717e30aee567d6f4c50c06a490023e14b2ce204b2fcf70c157133e8ebca26cf",
          "sha256": "6a729d708aded10c68abeebdc7e459a2be0f6052cc49b063cc962da987b39ca5",
          "sha1": "a064b787647bcec6fc41587db36b6bd1008b5922",
          "md5": "cf391ea33ec9c4b7eacd8859b56fdbfd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "c6eb84084fdffd197f8e539da204a2b6ce4721158dda98e5667fc7335799b60a0717e30aee567d6f4c50c06a490023e14b2ce204b2fcf70c157133e8ebca26cf",
          "sha256": "6a729d708aded10c68abeebdc7e459a2be0f6052cc49b063cc962da987b39ca5",
          "sha1": "a064b787647bcec6fc41587db36b6bd1008b5922",
          "md5": "cf391ea33ec9c4b7eacd8859b56fdbfd"
        }
      ]
    }
  ]
}
