{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "003e334ce901928ac5244ae88745c708c0bb1f1052f4ea794bd670ebfd970dcc6e6bce403dd56334982059a7f4a2e9fe7e4f28c9b3725fef0d09d148e40abe68",
          "sha256": "d320287029ed159eb10db0bce10995e1dd4150223837ecaeac34420c5272a9f0",
          "sha1": "a261533bd4271b4187d08a4c360b7412a2c904cb",
          "md5": "6241081ce8061ce50cdfbe16ffe1de40"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "003e334ce901928ac5244ae88745c708c0bb1f1052f4ea794bd670ebfd970dcc6e6bce403dd56334982059a7f4a2e9fe7e4f28c9b3725fef0d09d148e40abe68",
          "sha256": "d320287029ed159eb10db0bce10995e1dd4150223837ecaeac34420c5272a9f0",
          "sha1": "a261533bd4271b4187d08a4c360b7412a2c904cb",
          "md5": "6241081ce8061ce50cdfbe16ffe1de40"
        }
      ]
    }
  ]
}
