{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "f7bf6f6518e222e4e1c96d0cd0611a48a86c25b279641332f77f94b0ee1efe221dd5ca2434d2eff8a153599c9cc11a85ad16c7a3b7f6e8c7bc8a53fbd596f0ce",
          "sha256": "9f3963a9b80a81e138000de3e54864ecca20a5fb8a1f795536ce5eb9be931a43",
          "sha1": "62873884271191616e311c05308bdea01c95ca70",
          "md5": "bc5922f49fb763c8f28403a33269a7ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "f7bf6f6518e222e4e1c96d0cd0611a48a86c25b279641332f77f94b0ee1efe221dd5ca2434d2eff8a153599c9cc11a85ad16c7a3b7f6e8c7bc8a53fbd596f0ce",
          "sha256": "9f3963a9b80a81e138000de3e54864ecca20a5fb8a1f795536ce5eb9be931a43",
          "sha1": "62873884271191616e311c05308bdea01c95ca70",
          "md5": "bc5922f49fb763c8f28403a33269a7ce"
        }
      ]
    }
  ]
}
