{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "d0c3c18d6dd126fffbbd4e4b0f914f33547e9ab45945e39c7f095266eead51735896ea7e524327241742049b8c7c0da5f66c68615b2a7863675afd7f3caf01a6",
          "sha256": "03e7fa0cb0f271d86ea1724a5c493a856821e835906faadd80784a8a204fac45",
          "sha1": "0076a3c91ec7a51395f2768b39383ad69b857cff",
          "md5": "4214efa71fe887b14d1d33689172639a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "d0c3c18d6dd126fffbbd4e4b0f914f33547e9ab45945e39c7f095266eead51735896ea7e524327241742049b8c7c0da5f66c68615b2a7863675afd7f3caf01a6",
          "sha256": "03e7fa0cb0f271d86ea1724a5c493a856821e835906faadd80784a8a204fac45",
          "sha1": "0076a3c91ec7a51395f2768b39383ad69b857cff",
          "md5": "4214efa71fe887b14d1d33689172639a"
        }
      ]
    }
  ]
}
