{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "b2a9962dd7da963f6f532a4221a024881dade76012d3f88f95be7548ba095dcc3d9251d3ad0065915dbc2ae15b6de683025d76e73dc5096c678ff3925e5b705c",
          "sha256": "68315f1866a4741b187e13d98e090f0a9a43fd6abae2c3f014967e55e64071f3",
          "sha1": "498ef92acfc387c43abb4d220752cf117079bad1",
          "md5": "3dff0560b9a882b58d081af100ae1905"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "b2a9962dd7da963f6f532a4221a024881dade76012d3f88f95be7548ba095dcc3d9251d3ad0065915dbc2ae15b6de683025d76e73dc5096c678ff3925e5b705c",
          "sha256": "68315f1866a4741b187e13d98e090f0a9a43fd6abae2c3f014967e55e64071f3",
          "sha1": "498ef92acfc387c43abb4d220752cf117079bad1",
          "md5": "3dff0560b9a882b58d081af100ae1905"
        }
      ]
    }
  ]
}
