{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "d6ff95dec94ea0c9a4c105cb1b4ebb99fb2c587568edc467e12ed145d234eaa1e8af6638d276990062774ca9e2af13f62beab176d85db448239cc7bf36dc5f3e",
          "sha256": "ad4dd1c27c11df0d8eb94f16132bc7bd22b3c63c98e527e972534966f78dd346",
          "sha1": "f29cce70032307de97e323d6924077a81e67e6a4",
          "md5": "068d4987f9b8b25e8a9df4b9c2fddf59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "d6ff95dec94ea0c9a4c105cb1b4ebb99fb2c587568edc467e12ed145d234eaa1e8af6638d276990062774ca9e2af13f62beab176d85db448239cc7bf36dc5f3e",
          "sha256": "ad4dd1c27c11df0d8eb94f16132bc7bd22b3c63c98e527e972534966f78dd346",
          "sha1": "f29cce70032307de97e323d6924077a81e67e6a4",
          "md5": "068d4987f9b8b25e8a9df4b9c2fddf59"
        }
      ]
    }
  ]
}
