{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "1dd421214075a5a76f278ad007bb2d019a8f7dca274040dd01602769dbf3d5a7e016dbc091a8b6e4d0902950aeec24188da9639179a7976d8f4213260249c399",
          "sha256": "901e36371c85ab6f13550ac71c8ec68bec2d83bb4caf49cdd6d6465d7a1f0d64",
          "sha1": "91e884c24726f92640aa0a37f4d545bd324baf9e",
          "md5": "b583b381923ca5d6dbdad845ea144b05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "1dd421214075a5a76f278ad007bb2d019a8f7dca274040dd01602769dbf3d5a7e016dbc091a8b6e4d0902950aeec24188da9639179a7976d8f4213260249c399",
          "sha256": "901e36371c85ab6f13550ac71c8ec68bec2d83bb4caf49cdd6d6465d7a1f0d64",
          "sha1": "91e884c24726f92640aa0a37f4d545bd324baf9e",
          "md5": "b583b381923ca5d6dbdad845ea144b05"
        }
      ]
    }
  ]
}
