{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "35e49ad9802a8ae69879e4a31d6a0e86484c6991406a3e478006623884b5b2b9cf3d5e3a03cd1e6ed2763bee0372ccf46e5041cdad5604ccb724f86a74f851e9",
          "sha256": "e13795b6ac232f0b13ab5a602564a6adf42bde10e09eb971890dd9262fabdf6f",
          "sha1": "2fee7c34c8b6ee87c5a000f830bc6e5a09f27973",
          "md5": "a4afa2bc746f4c568588147ccecc5e49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "35e49ad9802a8ae69879e4a31d6a0e86484c6991406a3e478006623884b5b2b9cf3d5e3a03cd1e6ed2763bee0372ccf46e5041cdad5604ccb724f86a74f851e9",
          "sha256": "e13795b6ac232f0b13ab5a602564a6adf42bde10e09eb971890dd9262fabdf6f",
          "sha1": "2fee7c34c8b6ee87c5a000f830bc6e5a09f27973",
          "md5": "a4afa2bc746f4c568588147ccecc5e49"
        }
      ]
    }
  ]
}
