{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "17e2258ddfe6599cd935938f26526fcd3e105de98f3d9e3bb11aeea9a1a20b110d9651e2cc2a37e37ff24f239d44d4b2ba4ae2a76532bb49b20232052ffe7768",
          "sha256": "0358542ba116108adf098ee3d4b78b75806c9c05af7d6ad7938b28f792f66c0b",
          "sha1": "82ddd3f2dbe9b451d215e7d51275bdc5f25f876a",
          "md5": "886b56e2189745a6d4cee0186d1f0cd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "17e2258ddfe6599cd935938f26526fcd3e105de98f3d9e3bb11aeea9a1a20b110d9651e2cc2a37e37ff24f239d44d4b2ba4ae2a76532bb49b20232052ffe7768",
          "sha256": "0358542ba116108adf098ee3d4b78b75806c9c05af7d6ad7938b28f792f66c0b",
          "sha1": "82ddd3f2dbe9b451d215e7d51275bdc5f25f876a",
          "md5": "886b56e2189745a6d4cee0186d1f0cd1"
        }
      ]
    }
  ]
}
