{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "77259f4939a044f1c73ab8ca5dc9d12f53b9f50c7f7d0ce493966bb1e0815bf4ae1249baa0647a24440b2098128913aa6f9088f051d5c0b65eadbe47ed63b2a8",
          "sha256": "41ef315d5bce23570cce702b7c8a01894f4d50a59bbfd49471954574bd9b0717",
          "sha1": "9abab125661142889704d384115b741b211499d9",
          "md5": "8e4b69917e5b729e2f21b0a8a9087708"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "77259f4939a044f1c73ab8ca5dc9d12f53b9f50c7f7d0ce493966bb1e0815bf4ae1249baa0647a24440b2098128913aa6f9088f051d5c0b65eadbe47ed63b2a8",
          "sha256": "41ef315d5bce23570cce702b7c8a01894f4d50a59bbfd49471954574bd9b0717",
          "sha1": "9abab125661142889704d384115b741b211499d9",
          "md5": "8e4b69917e5b729e2f21b0a8a9087708"
        }
      ]
    }
  ]
}
