{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "ba248300dd0e3cbe73b22e08a9b623d93d9a1a8f42073a9b4d73d9c3be4ca2f3730ce81c99a614a4a7f8c9ca144567430752b4ffead917c7e942c5c257e7e0ef",
          "sha256": "96c79028469899a04433f946033a5f3154ae5012a0a7e25bf424c1fa1e610490",
          "sha1": "25e82ce16fa502760a49cc9d878f226d9944f653",
          "md5": "ccf85848d1e58ddfc6d5abd8282b8f13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.27.0-SNAPSHOT.jar",
          "url": "http-api-4.27.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "ba248300dd0e3cbe73b22e08a9b623d93d9a1a8f42073a9b4d73d9c3be4ca2f3730ce81c99a614a4a7f8c9ca144567430752b4ffead917c7e942c5c257e7e0ef",
          "sha256": "96c79028469899a04433f946033a5f3154ae5012a0a7e25bf424c1fa1e610490",
          "sha1": "25e82ce16fa502760a49cc9d878f226d9944f653",
          "md5": "ccf85848d1e58ddfc6d5abd8282b8f13"
        }
      ]
    }
  ]
}
