{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.31.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.31.0.jar",
          "url": "http-api-4.31.0.jar",
          "size": 88795,
          "sha512": "8144f12064d37cbda935c506ed817220083606aba00d52436547741cee372ece2b7c6e0d8a44c79946537e0a805902089c95bfdec1313f44d62deab5d96a0a61",
          "sha256": "b657badeb40e93371e618a3ab558f8496aece8d22b21bc80b860f8a5edb2f4c4",
          "sha1": "6d8c27b3f8c6fac9d52fb1ff4e46d664afc5b75c",
          "md5": "62345f6ee0b58683276279842e61fba8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.31.0.jar",
          "url": "http-api-4.31.0.jar",
          "size": 88795,
          "sha512": "8144f12064d37cbda935c506ed817220083606aba00d52436547741cee372ece2b7c6e0d8a44c79946537e0a805902089c95bfdec1313f44d62deab5d96a0a61",
          "sha256": "b657badeb40e93371e618a3ab558f8496aece8d22b21bc80b860f8a5edb2f4c4",
          "sha1": "6d8c27b3f8c6fac9d52fb1ff4e46d664afc5b75c",
          "md5": "62345f6ee0b58683276279842e61fba8"
        }
      ]
    }
  ]
}
