{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.2-SNAPSHOT.jar",
          "url": "runescape-api-1.0.2-SNAPSHOT.jar",
          "size": 126811,
          "sha512": "a014b3090ef21a53c747a8bf12230e13af26e66693e4cb64ebedefc896c3a84f8e052f3fd2ba016c1aafac2d6a500fa919df674885c6eb6731a72709c46f61f1",
          "sha256": "0a2690625290aa18aebb745cc49286a97498c2f44010984c037cb84fd8f2f451",
          "sha1": "ccc6fe31dcba3549fc0d80aa90c859a1c612cc4a",
          "md5": "f1c3868d7ce3fdf29e8895079b0caea7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.2-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.2-SNAPSHOT.jar",
          "url": "runescape-api-1.0.2-SNAPSHOT.jar",
          "size": 126811,
          "sha512": "a014b3090ef21a53c747a8bf12230e13af26e66693e4cb64ebedefc896c3a84f8e052f3fd2ba016c1aafac2d6a500fa919df674885c6eb6731a72709c46f61f1",
          "sha256": "0a2690625290aa18aebb745cc49286a97498c2f44010984c037cb84fd8f2f451",
          "sha1": "ccc6fe31dcba3549fc0d80aa90c859a1c612cc4a",
          "md5": "f1c3868d7ce3fdf29e8895079b0caea7"
        }
      ]
    }
  ]
}
