{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.0.jar",
          "url": "runelite-api-1.0.0.jar",
          "size": 1376392,
          "sha512": "2b1e331b4f2fca664135b408be88701609e081379bcf82dfebd9044cbaf29361f13b7de5b1d5d33adfcbe370834c838ab436751e89ec626015d2d03917b384a4",
          "sha256": "d92f857f0908e3d9fa759f918d7f8a1e56e987a549fa07d79cc9a245b1c5633b",
          "sha1": "1a49c56e6b7420d3bf24e0440e1593a7b78a9261",
          "md5": "d457f9c359f052b5b6ad9f63d5f4f763"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.0.jar",
          "url": "runelite-api-1.0.0.jar",
          "size": 1376392,
          "sha512": "2b1e331b4f2fca664135b408be88701609e081379bcf82dfebd9044cbaf29361f13b7de5b1d5d33adfcbe370834c838ab436751e89ec626015d2d03917b384a4",
          "sha256": "d92f857f0908e3d9fa759f918d7f8a1e56e987a549fa07d79cc9a245b1c5633b",
          "sha1": "1a49c56e6b7420d3bf24e0440e1593a7b78a9261",
          "md5": "d457f9c359f052b5b6ad9f63d5f4f763"
        }
      ]
    }
  ]
}
