{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "8837f822eaba9fa71f045846472e39bc77774e43df1cb318c2a56c1a1a7bd8876cc20d1adf4e5e1993b977b5fd7281927a0882678b4c3ea16037bc937aa9032b",
          "sha256": "bb30d7a41d5186601fa9961dc461ae78ddccde5d0798d74ff85c0e85b4a19157",
          "sha1": "15b40b4254c6408125bf8c8d5f2e33e5f7c786f0",
          "md5": "3aa03d01c46a4b2625024dc78b768c80"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "8837f822eaba9fa71f045846472e39bc77774e43df1cb318c2a56c1a1a7bd8876cc20d1adf4e5e1993b977b5fd7281927a0882678b4c3ea16037bc937aa9032b",
          "sha256": "bb30d7a41d5186601fa9961dc461ae78ddccde5d0798d74ff85c0e85b4a19157",
          "sha1": "15b40b4254c6408125bf8c8d5f2e33e5f7c786f0",
          "md5": "3aa03d01c46a4b2625024dc78b768c80"
        }
      ]
    }
  ]
}
