{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "5ae48e0bb6df36a5c0c47b05ccbfc55379c40361ecf1acbf37b30ee8f22b4f813938514639713feaef45f845701fa50d2a04bf1322b33fc911a776bb85e60300",
          "sha256": "c8c656bba593141f32f7a2500d83c8e683f313668479219940d9bef1ce03d175",
          "sha1": "1a1631b27e1278f8d88aa9d624e22dcde18a9b4c",
          "md5": "3c7da8b7a9268b23cf894a311f6fcb6b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "5ae48e0bb6df36a5c0c47b05ccbfc55379c40361ecf1acbf37b30ee8f22b4f813938514639713feaef45f845701fa50d2a04bf1322b33fc911a776bb85e60300",
          "sha256": "c8c656bba593141f32f7a2500d83c8e683f313668479219940d9bef1ce03d175",
          "sha1": "1a1631b27e1278f8d88aa9d624e22dcde18a9b4c",
          "md5": "3c7da8b7a9268b23cf894a311f6fcb6b"
        }
      ]
    }
  ]
}
