{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "45a6006e0ffba0b15556f7c9e6604a245386dd9e19accc6ccdcca09d4142f54a1a7f37449bdc304dc30ed025cf00dbf873727ec143240ac8d62e3dab9a0bd7db",
          "sha256": "b9d94cbe932bb4b1220feb0f8f6b6056b0ca75216663759c06289bc7e407572f",
          "sha1": "0a8f18eab8ee535e3c14e4183dcfb0681471ed42",
          "md5": "0eac737965466fe43f527ac30e63252f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "45a6006e0ffba0b15556f7c9e6604a245386dd9e19accc6ccdcca09d4142f54a1a7f37449bdc304dc30ed025cf00dbf873727ec143240ac8d62e3dab9a0bd7db",
          "sha256": "b9d94cbe932bb4b1220feb0f8f6b6056b0ca75216663759c06289bc7e407572f",
          "sha1": "0a8f18eab8ee535e3c14e4183dcfb0681471ed42",
          "md5": "0eac737965466fe43f527ac30e63252f"
        }
      ]
    }
  ]
}
