{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "eb7fb36c608e990d47f03278608d249defc29ca93a0ebf53a68e463cf0184f7c044668d9e56ebbc032d15ed03f34ccb57d38d3e6720c7f408fad603ab562eb6f",
          "sha256": "bdfdcb037f3925ac6e6b60fe9f6ec024b9cfbb7d62a247e515836fcda2bd64e3",
          "sha1": "769212d41b10c1099af1b737bf9be4bbc7df42f6",
          "md5": "b69d7b1681d4bfef8218c8df05eb91b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "eb7fb36c608e990d47f03278608d249defc29ca93a0ebf53a68e463cf0184f7c044668d9e56ebbc032d15ed03f34ccb57d38d3e6720c7f408fad603ab562eb6f",
          "sha256": "bdfdcb037f3925ac6e6b60fe9f6ec024b9cfbb7d62a247e515836fcda2bd64e3",
          "sha1": "769212d41b10c1099af1b737bf9be4bbc7df42f6",
          "md5": "b69d7b1681d4bfef8218c8df05eb91b0"
        }
      ]
    }
  ]
}
