{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "e449f6b75fe4cdc7ec685262f190ba9113cb0815ad10689bd3c29f8f5e2fa574b790bca41add7e2f3e23179b47e6e6d1c6bcb9dac43c44c29443edc806e1f4d6",
          "sha256": "1ced74a28b47ee41dca428142750c023282b615e0e8f6bbf1473e50d328faa88",
          "sha1": "37eaa601ef1e108b7471c6f213c6650f4ec71699",
          "md5": "517ef8ae2cf7f5415ac554ac3e04aee5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "e449f6b75fe4cdc7ec685262f190ba9113cb0815ad10689bd3c29f8f5e2fa574b790bca41add7e2f3e23179b47e6e6d1c6bcb9dac43c44c29443edc806e1f4d6",
          "sha256": "1ced74a28b47ee41dca428142750c023282b615e0e8f6bbf1473e50d328faa88",
          "sha1": "37eaa601ef1e108b7471c6f213c6650f4ec71699",
          "md5": "517ef8ae2cf7f5415ac554ac3e04aee5"
        }
      ]
    }
  ]
}
