{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "7703a5dc6d448cf6c48e1cafb25345db7a6c04490a213dfb3724035114a874cb14177f5e171470053216bfd23713ea0c79df0d22296ad090f16709a2cd96b676",
          "sha256": "7816ea93e6ffb39e515a74b09b6736518edd9d5580a290064381c212a969e4cb",
          "sha1": "3a7cc5b35fa630150af0f213688ef21910b5ddd3",
          "md5": "d61bbd8af165fc63499bb3e1bd05dd82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "7703a5dc6d448cf6c48e1cafb25345db7a6c04490a213dfb3724035114a874cb14177f5e171470053216bfd23713ea0c79df0d22296ad090f16709a2cd96b676",
          "sha256": "7816ea93e6ffb39e515a74b09b6736518edd9d5580a290064381c212a969e4cb",
          "sha1": "3a7cc5b35fa630150af0f213688ef21910b5ddd3",
          "md5": "d61bbd8af165fc63499bb3e1bd05dd82"
        }
      ]
    }
  ]
}
