{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "bd3f3e792f5b3e4cea240fcf163763604968d22270bc180db982983abd5ac15f55b06517319356ef29316356a2c2e218b541084f42c80ea40de3e3f329012450",
          "sha256": "ff59d007ebf82128ac238af82df72946f89a831a7852ddf67c44ae4971bf6e01",
          "sha1": "66e1df61f7cfdc4ec976c8d5069678d34a4cc4f1",
          "md5": "ea0913c02b29af32e233678238dd8a27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "bd3f3e792f5b3e4cea240fcf163763604968d22270bc180db982983abd5ac15f55b06517319356ef29316356a2c2e218b541084f42c80ea40de3e3f329012450",
          "sha256": "ff59d007ebf82128ac238af82df72946f89a831a7852ddf67c44ae4971bf6e01",
          "sha1": "66e1df61f7cfdc4ec976c8d5069678d34a4cc4f1",
          "md5": "ea0913c02b29af32e233678238dd8a27"
        }
      ]
    }
  ]
}
