{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "dfe51f3d4864f30b23929f6869d5e440e4815dee6ca988e8f1ddf677c0fc2bc0a22ca7338a67bc7b41a9ac1039a17c10ba566882c0da364cad8c55cbba810c83",
          "sha256": "b262f4fc350203357890c33d6a883f3c7231bedcf1c7cc51a4e1df8abca9aa27",
          "sha1": "6016e956db418271d04bb7e51bad045ce4e35ce2",
          "md5": "5d7eaa42500cef3ecf9de70526de9618"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "dfe51f3d4864f30b23929f6869d5e440e4815dee6ca988e8f1ddf677c0fc2bc0a22ca7338a67bc7b41a9ac1039a17c10ba566882c0da364cad8c55cbba810c83",
          "sha256": "b262f4fc350203357890c33d6a883f3c7231bedcf1c7cc51a4e1df8abca9aa27",
          "sha1": "6016e956db418271d04bb7e51bad045ce4e35ce2",
          "md5": "5d7eaa42500cef3ecf9de70526de9618"
        }
      ]
    }
  ]
}
