{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "e0f1711388df5ea365e4bededeb4cf378cf230857cdb986a384290aee3fad44a3796f264cc01194bb821a87d4b582594e3bcd3e6d3200a6a437b1cb4e5925f8a",
          "sha256": "0182134f9ad23742913d6f3b562e7ddb37fb0dc27895c0a9b691bbf5641fea92",
          "sha1": "833b401f6116f4eb714e928e41faf5fd4b87f4fa",
          "md5": "ecb0a1f0964d8b2c51cd58bad831f330"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "e0f1711388df5ea365e4bededeb4cf378cf230857cdb986a384290aee3fad44a3796f264cc01194bb821a87d4b582594e3bcd3e6d3200a6a437b1cb4e5925f8a",
          "sha256": "0182134f9ad23742913d6f3b562e7ddb37fb0dc27895c0a9b691bbf5641fea92",
          "sha1": "833b401f6116f4eb714e928e41faf5fd4b87f4fa",
          "md5": "ecb0a1f0964d8b2c51cd58bad831f330"
        }
      ]
    }
  ]
}
