{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "a654550a1cb90e52c452f6a9f7061513dabef50be081b8730cb990b9b12134d3342291983c57a8480cb52abf8f41198c4791369a8e1cb7aaa65f5eca71c4dd00",
          "sha256": "7a29fde3c1a4d397dc42a0ed936c82df6c72512e55aa4e96ee166f1cb4b74fb2",
          "sha1": "6ba9b88efc3f447fc5f0ce5aee53797807296214",
          "md5": "91f22f088a734cb2b8759125a7593a85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "a654550a1cb90e52c452f6a9f7061513dabef50be081b8730cb990b9b12134d3342291983c57a8480cb52abf8f41198c4791369a8e1cb7aaa65f5eca71c4dd00",
          "sha256": "7a29fde3c1a4d397dc42a0ed936c82df6c72512e55aa4e96ee166f1cb4b74fb2",
          "sha1": "6ba9b88efc3f447fc5f0ce5aee53797807296214",
          "md5": "91f22f088a734cb2b8759125a7593a85"
        }
      ]
    }
  ]
}
