{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "414b58912eeb18e1abba24b9eb2359dfbbf7befb58e381bf3f3d83768d64fab5546b4d2aac7123d24ce6da2d2d8f3e3d73da4d597b8a4f631e6aae265a656a98",
          "sha256": "e04f2d230d96121d339229030907c305312876fcb79eab3569bf04b5edb788d3",
          "sha1": "4e4d65486359c2751b0438336ed38029ba747e76",
          "md5": "62065e80a6fe85f4327b81ab2a4c02a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "414b58912eeb18e1abba24b9eb2359dfbbf7befb58e381bf3f3d83768d64fab5546b4d2aac7123d24ce6da2d2d8f3e3d73da4d597b8a4f631e6aae265a656a98",
          "sha256": "e04f2d230d96121d339229030907c305312876fcb79eab3569bf04b5edb788d3",
          "sha1": "4e4d65486359c2751b0438336ed38029ba747e76",
          "md5": "62065e80a6fe85f4327b81ab2a4c02a9"
        }
      ]
    }
  ]
}
