{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "d29f39de528f5d3f67e762ac498dc9bfd579593801a70d350d42a70c1b36cb7cf96f0fb16b9cf9ef6cdd6d40ceab71b1c2f3a9cdfda3599aedbfe3e975e1318d",
          "sha256": "18fc80ab11525952c28b2d3f229e18a054edf2e9815126df0f80fbbda12760fa",
          "sha1": "05f34e463976aa555d778c4559a807e5a512ca91",
          "md5": "11fa4cf3e3e02a8d2b6cb2898cf994ed"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "d29f39de528f5d3f67e762ac498dc9bfd579593801a70d350d42a70c1b36cb7cf96f0fb16b9cf9ef6cdd6d40ceab71b1c2f3a9cdfda3599aedbfe3e975e1318d",
          "sha256": "18fc80ab11525952c28b2d3f229e18a054edf2e9815126df0f80fbbda12760fa",
          "sha1": "05f34e463976aa555d778c4559a807e5a512ca91",
          "md5": "11fa4cf3e3e02a8d2b6cb2898cf994ed"
        }
      ]
    }
  ]
}
