{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "f91917ce26b9f60c4b8e2efd7f228ef685b214dd8306fff0da75b8e42155d1ccbd6c01e1e954e01a9fec3bc5db66d558018d792e18fc6a1349cd6a3649a1e803",
          "sha256": "d7c2590cad3606713d9c4a438e40be1158bc6e0230957427f3d8f94baa2dfeea",
          "sha1": "65fdadf91be9a027729155e65a0f92840169185f",
          "md5": "bb67c8d2e3aa154d1ed5810bb944c562"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "f91917ce26b9f60c4b8e2efd7f228ef685b214dd8306fff0da75b8e42155d1ccbd6c01e1e954e01a9fec3bc5db66d558018d792e18fc6a1349cd6a3649a1e803",
          "sha256": "d7c2590cad3606713d9c4a438e40be1158bc6e0230957427f3d8f94baa2dfeea",
          "sha1": "65fdadf91be9a027729155e65a0f92840169185f",
          "md5": "bb67c8d2e3aa154d1ed5810bb944c562"
        }
      ]
    }
  ]
}
