{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "f6790126bf3dac16965b68f3a4111ef5e01af1a35c621e68d713e35588fc88a14595f788702050955843eff087491e863d05b388148ca4d440eff8829653a0df",
          "sha256": "83ed8e5f03d45443f5729d14179f551e5522bed55cbd568069bed0085ad0a99e",
          "sha1": "d540d7179b5ac955facc9a80687f2b35bbb8d2d0",
          "md5": "b3ca1ecce78d682032997e4dbbeab13d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "f6790126bf3dac16965b68f3a4111ef5e01af1a35c621e68d713e35588fc88a14595f788702050955843eff087491e863d05b388148ca4d440eff8829653a0df",
          "sha256": "83ed8e5f03d45443f5729d14179f551e5522bed55cbd568069bed0085ad0a99e",
          "sha1": "d540d7179b5ac955facc9a80687f2b35bbb8d2d0",
          "md5": "b3ca1ecce78d682032997e4dbbeab13d"
        }
      ]
    }
  ]
}
