{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "7ab89a1e36f9d88e643d5462b1d32c9b802263e427329f4e878c09dcfc9df432b5905583fc16bd25da21dfdddfdaafbe33c604623ac48942f5589d686b17b7e3",
          "sha256": "66a5b6a7fbd3523e6e881defa37b7e3064d90fce81f25495578615e8f9091bb7",
          "sha1": "72be11e87954bf4c54a2096484eb66de245c3061",
          "md5": "49e4f974459709ac2cceb70bf208dd8c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "7ab89a1e36f9d88e643d5462b1d32c9b802263e427329f4e878c09dcfc9df432b5905583fc16bd25da21dfdddfdaafbe33c604623ac48942f5589d686b17b7e3",
          "sha256": "66a5b6a7fbd3523e6e881defa37b7e3064d90fce81f25495578615e8f9091bb7",
          "sha1": "72be11e87954bf4c54a2096484eb66de245c3061",
          "md5": "49e4f974459709ac2cceb70bf208dd8c"
        }
      ]
    }
  ]
}
