{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "6cab33866493eb2b82ad47eb5c76f5bac971dcd187cfa0333000accd152b268810f632c89a4d84388f7ff85ae606420e1d28dca512adb18cfacf0ef570b6afb0",
          "sha256": "6667b42a2eb28ba7d1119955a3f1aae8bb520fdf11088a1dade42c794f163e63",
          "sha1": "4504e09f9b472b3b293f5b8c8d931d5031113a37",
          "md5": "7f08a5bcb5a9e9ed73d4c98f6baf1abf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "6cab33866493eb2b82ad47eb5c76f5bac971dcd187cfa0333000accd152b268810f632c89a4d84388f7ff85ae606420e1d28dca512adb18cfacf0ef570b6afb0",
          "sha256": "6667b42a2eb28ba7d1119955a3f1aae8bb520fdf11088a1dade42c794f163e63",
          "sha1": "4504e09f9b472b3b293f5b8c8d931d5031113a37",
          "md5": "7f08a5bcb5a9e9ed73d4c98f6baf1abf"
        }
      ]
    }
  ]
}
