{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "4a3a37e78467fda45ecbf54e1f15ce1f7c7e292ca3d2579a6603d5d2db94a15248ce2ec04e66a0fc6bad106ce23d54f449b15ad262709a91c8c14529f42ad7b3",
          "sha256": "6d8caea6090e957a42485c910dacc179d5d58365b885042bdd800a5af180aa98",
          "sha1": "b2417ddccdbe9ca8c1f6441c4f467a6f7881be12",
          "md5": "15c6ed01c155b8ae65682c8a51c94912"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "4a3a37e78467fda45ecbf54e1f15ce1f7c7e292ca3d2579a6603d5d2db94a15248ce2ec04e66a0fc6bad106ce23d54f449b15ad262709a91c8c14529f42ad7b3",
          "sha256": "6d8caea6090e957a42485c910dacc179d5d58365b885042bdd800a5af180aa98",
          "sha1": "b2417ddccdbe9ca8c1f6441c4f467a6f7881be12",
          "md5": "15c6ed01c155b8ae65682c8a51c94912"
        }
      ]
    }
  ]
}
