{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "f9dd2bef70d959def556513b33606e6c2dc48b440771c086a86bb50abf804cf056b5c76d2a97da24548e9fb5f1546f7d84e6444a6c9961ea5a1c89fecc9f75a9",
          "sha256": "1600d2d98d9812b64305d4dcda1151f02c0d1767d8cd7c0cde5607ad8052ded9",
          "sha1": "a59a1c5fd201908ecef7de77a679e2946c49677d",
          "md5": "cd7c2ea47ea7064279f79ed44bc8b225"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88797,
          "sha512": "f9dd2bef70d959def556513b33606e6c2dc48b440771c086a86bb50abf804cf056b5c76d2a97da24548e9fb5f1546f7d84e6444a6c9961ea5a1c89fecc9f75a9",
          "sha256": "1600d2d98d9812b64305d4dcda1151f02c0d1767d8cd7c0cde5607ad8052ded9",
          "sha1": "a59a1c5fd201908ecef7de77a679e2946c49677d",
          "md5": "cd7c2ea47ea7064279f79ed44bc8b225"
        }
      ]
    }
  ]
}
