{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "b2d103476077c7b403e688502b019ba7f71a4b270a40b49232a7a495189b32e356bef91731b7a38bfc3118c1e8c9e96885bedf83aca9f465f57f0a970ecd797f",
          "sha256": "2f80e00403842c383f78741dbafc136a88058b32b9c564b3a695bc57c2395954",
          "sha1": "a16d015b8d92e4c50edf2e16061f76e1a45aaa52",
          "md5": "5d2ecc215e0f4583286e5606183b2f62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.32.0-SNAPSHOT.jar",
          "url": "http-api-4.32.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "b2d103476077c7b403e688502b019ba7f71a4b270a40b49232a7a495189b32e356bef91731b7a38bfc3118c1e8c9e96885bedf83aca9f465f57f0a970ecd797f",
          "sha256": "2f80e00403842c383f78741dbafc136a88058b32b9c564b3a695bc57c2395954",
          "sha1": "a16d015b8d92e4c50edf2e16061f76e1a45aaa52",
          "md5": "5d2ecc215e0f4583286e5606183b2f62"
        }
      ]
    }
  ]
}
