{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 122011,
          "sha512": "9c9c3252bdd4c1ada4178bf7d302b62dbef8e41824d115bd3b01b2e48a03c8282801ecacfe2f071a3307d7b434baa397bdf07b062d8484c27454793e5f742862",
          "sha256": "30289676ad782d890e777b3ca681b9a4c820adee9094f3b24313a481518db2cc",
          "sha1": "69b57211f3e584a343bf3f895bdc8a7d8b902f55",
          "md5": "55e2117fed1e66ba4ed87097f456e294"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 122011,
          "sha512": "9c9c3252bdd4c1ada4178bf7d302b62dbef8e41824d115bd3b01b2e48a03c8282801ecacfe2f071a3307d7b434baa397bdf07b062d8484c27454793e5f742862",
          "sha256": "30289676ad782d890e777b3ca681b9a4c820adee9094f3b24313a481518db2cc",
          "sha1": "69b57211f3e584a343bf3f895bdc8a7d8b902f55",
          "md5": "55e2117fed1e66ba4ed87097f456e294"
        }
      ]
    }
  ]
}
