{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 122034,
          "sha512": "0e12cb3223cc8c51ba7fd1e235bc45a4fd191eb766997be8386164272e7c49538c416ca55cc252f33f712462c13fd8f363c5969b9fe86957533e68241063ebe9",
          "sha256": "1f77c31325296e9d5dfd522fc1205999a9aa692748220653ebecade3de6fbaea",
          "sha1": "690aa88c3692e6b86df186d1e4eeafff85d3551f",
          "md5": "860ca6ec3115bdbea5a9808cbf29ff75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 122034,
          "sha512": "0e12cb3223cc8c51ba7fd1e235bc45a4fd191eb766997be8386164272e7c49538c416ca55cc252f33f712462c13fd8f363c5969b9fe86957533e68241063ebe9",
          "sha256": "1f77c31325296e9d5dfd522fc1205999a9aa692748220653ebecade3de6fbaea",
          "sha1": "690aa88c3692e6b86df186d1e4eeafff85d3551f",
          "md5": "860ca6ec3115bdbea5a9808cbf29ff75"
        }
      ]
    }
  ]
}
