{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.7.jar",
          "url": "http-api-1.0.7.jar",
          "size": 91329,
          "sha512": "1e7723ee08882048de2ca4488b29fc0b4dfc7d559b678994c99e2789de7c9942955ad5856cc3fedd660a6d382c6c8ac0dfa4f9f0a842d11ed216c24472c33f52",
          "sha256": "c759b26eebbafc023be38cc5e83d58e53072021866ce15e9d75ebd4d687160ae",
          "sha1": "79cf139742bb2e7e14da96b09e54fe595eacd7a6",
          "md5": "9439087bdc60f478f2e5dbc4e7d3dd3c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.7.jar",
          "url": "http-api-1.0.7.jar",
          "size": 91329,
          "sha512": "1e7723ee08882048de2ca4488b29fc0b4dfc7d559b678994c99e2789de7c9942955ad5856cc3fedd660a6d382c6c8ac0dfa4f9f0a842d11ed216c24472c33f52",
          "sha256": "c759b26eebbafc023be38cc5e83d58e53072021866ce15e9d75ebd4d687160ae",
          "sha1": "79cf139742bb2e7e14da96b09e54fe595eacd7a6",
          "md5": "9439087bdc60f478f2e5dbc4e7d3dd3c"
        }
      ]
    }
  ]
}
