{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.7.jar",
          "url": "http-api-1.0.7.jar",
          "size": 91329,
          "sha512": "62ac69706a159935b9828fd4c07754f2fcdf8b7de026fa86e9257afacdba6e32cc5dbf11fb425357ab3a2a31353e779fbb1d47dfeec4ba9bfbd4037925b0343d",
          "sha256": "54801542c82c060dcb428d5599a496235a96d2b9a67d4080c0dd1650c882910a",
          "sha1": "7dc6c38df2cbca1aa52483726e87e0da5daf5c47",
          "md5": "165d878fadba3f48bc4cdd02686cb7d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.7.jar",
          "url": "http-api-1.0.7.jar",
          "size": 91329,
          "sha512": "62ac69706a159935b9828fd4c07754f2fcdf8b7de026fa86e9257afacdba6e32cc5dbf11fb425357ab3a2a31353e779fbb1d47dfeec4ba9bfbd4037925b0343d",
          "sha256": "54801542c82c060dcb428d5599a496235a96d2b9a67d4080c0dd1650c882910a",
          "sha1": "7dc6c38df2cbca1aa52483726e87e0da5daf5c47",
          "md5": "165d878fadba3f48bc4cdd02686cb7d8"
        }
      ]
    }
  ]
}
