{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-EXPERIMENTAL.jar",
          "url": "http-api-1.0.6-EXPERIMENTAL.jar",
          "size": 91329,
          "sha512": "2d49226e73091d38f9c7b96109beb5c96547b4452d84bfe565a7997d0da3fe85f2a1444633601de8c4d1296e5ec4bb2e0f6c8300997ab9bbae4b28aaeb30b81d",
          "sha256": "6decaff8165bfd966f97d9af0a0b766504c9d99fe5c90af476f644500e2532c9",
          "sha1": "67d2af2a186d3e75db17c58f13efa8f1f02aa201",
          "md5": "84a05c9abf312096d40f24d892abc7f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-EXPERIMENTAL.jar",
          "url": "http-api-1.0.6-EXPERIMENTAL.jar",
          "size": 91329,
          "sha512": "2d49226e73091d38f9c7b96109beb5c96547b4452d84bfe565a7997d0da3fe85f2a1444633601de8c4d1296e5ec4bb2e0f6c8300997ab9bbae4b28aaeb30b81d",
          "sha256": "6decaff8165bfd966f97d9af0a0b766504c9d99fe5c90af476f644500e2532c9",
          "sha1": "67d2af2a186d3e75db17c58f13efa8f1f02aa201",
          "md5": "84a05c9abf312096d40f24d892abc7f8"
        }
      ]
    }
  ]
}
