{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-EXPERIMENTAL.jar",
          "url": "http-api-1.0.6-EXPERIMENTAL.jar",
          "size": 91328,
          "sha512": "2b615c20321f88ac89a039884043cfcb8e543412d9e270c4cc5cd61ff5b579e43f498242fb972d4d75cc465687456654c07651c8cc33e3612439f59559def482",
          "sha256": "435edbafa72b07d87a21cbe8253e77bd9e98f64f96ffb1a55d6d20cfd7e8e9a2",
          "sha1": "41977f791525b3ee85c5799195f13c330b988224",
          "md5": "4dfe539fc169869a561fee2232b4cd89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-EXPERIMENTAL.jar",
          "url": "http-api-1.0.6-EXPERIMENTAL.jar",
          "size": 91328,
          "sha512": "2b615c20321f88ac89a039884043cfcb8e543412d9e270c4cc5cd61ff5b579e43f498242fb972d4d75cc465687456654c07651c8cc33e3612439f59559def482",
          "sha256": "435edbafa72b07d87a21cbe8253e77bd9e98f64f96ffb1a55d6d20cfd7e8e9a2",
          "sha1": "41977f791525b3ee85c5799195f13c330b988224",
          "md5": "4dfe539fc169869a561fee2232b4cd89"
        }
      ]
    }
  ]
}
