{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6-EXPERIMENTAL.jar",
          "url": "http-api-1.0.6-EXPERIMENTAL.jar",
          "size": 88474,
          "sha512": "45582c8f0b4538af826561af16d135c8c3aecce2df29c997e526197041c06b48b6349509badbea809e80ddc520fdc06e046d7afeeed07f87979090ff8917d22e",
          "sha256": "edd7e5364bdaee3369661523337c4b6bfae70d7e19537daebaee4af055ed9b80",
          "sha1": "5545ed852eb3c3ddb2f7876dad8008027da01c1b",
          "md5": "b54ae9fe66619a13c37fd622c52c6671"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6-EXPERIMENTAL.jar",
          "url": "http-api-1.0.6-EXPERIMENTAL.jar",
          "size": 88474,
          "sha512": "45582c8f0b4538af826561af16d135c8c3aecce2df29c997e526197041c06b48b6349509badbea809e80ddc520fdc06e046d7afeeed07f87979090ff8917d22e",
          "sha256": "edd7e5364bdaee3369661523337c4b6bfae70d7e19537daebaee4af055ed9b80",
          "sha1": "5545ed852eb3c3ddb2f7876dad8008027da01c1b",
          "md5": "b54ae9fe66619a13c37fd622c52c6671"
        }
      ]
    }
  ]
}
