{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.4.jar",
          "url": "runescape-api-1.0.4.jar",
          "size": 127786,
          "sha512": "5b5107583e2b50c0b424f656e82a8bad9e724846a72a8115edbaf0230b280094e23d0c4b53fa001bf808c4959e6a5bbdb3a7b7ed31c1f658624bc8625475fab4",
          "sha256": "72c010074f7a654255702ca0c26c14c5fcf25d7189003fade9e11c15b798f22b",
          "sha1": "2c4a556aa7047cf9097ed1153e724b59eac27017",
          "md5": "4513f7d9389d0c7f6e709a55de46cdee"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.4"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.4.jar",
          "url": "runescape-api-1.0.4.jar",
          "size": 127786,
          "sha512": "5b5107583e2b50c0b424f656e82a8bad9e724846a72a8115edbaf0230b280094e23d0c4b53fa001bf808c4959e6a5bbdb3a7b7ed31c1f658624bc8625475fab4",
          "sha256": "72c010074f7a654255702ca0c26c14c5fcf25d7189003fade9e11c15b798f22b",
          "sha1": "2c4a556aa7047cf9097ed1153e724b59eac27017",
          "md5": "4513f7d9389d0c7f6e709a55de46cdee"
        }
      ]
    }
  ]
}
