{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.1-SNAPSHOT.jar",
          "url": "runescape-api-1.0.1-SNAPSHOT.jar",
          "size": 126037,
          "sha512": "c85dbd4e2cbcde9ca06bdd5523ff18582c1c8c346241c8bc1c26ae37e94ce5d811e2cbf3faa4ed9f4437db26883513a079cc0c82b921c4b3024efcd74b5c05d4",
          "sha256": "c84ddbc1be843bbf2f2d324f7e192201844b8d4b441c5498ce35dfd3c4a03285",
          "sha1": "84b7ca51ec3b80557f511363c2fa78e6b9d4711b",
          "md5": "f4d624d5d27e004776d1938e204fbf15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.1-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.1-SNAPSHOT.jar",
          "url": "runescape-api-1.0.1-SNAPSHOT.jar",
          "size": 126037,
          "sha512": "c85dbd4e2cbcde9ca06bdd5523ff18582c1c8c346241c8bc1c26ae37e94ce5d811e2cbf3faa4ed9f4437db26883513a079cc0c82b921c4b3024efcd74b5c05d4",
          "sha256": "c84ddbc1be843bbf2f2d324f7e192201844b8d4b441c5498ce35dfd3c4a03285",
          "sha1": "84b7ca51ec3b80557f511363c2fa78e6b9d4711b",
          "md5": "f4d624d5d27e004776d1938e204fbf15"
        }
      ]
    }
  ]
}
