{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 88795,
          "sha512": "6f77d94c09b7cc3a957697e45c3ecae8ba415587206d8824125fddc90a2caa06f72374e531a7b0eeb28a8acbef8ec2162458c822dc225973badc749643c86d48",
          "sha256": "50066aefe951e8bebd26503464d00a36bfaafd8043a930aa6fbd2fc3ca42302c",
          "sha1": "89a5d201485d0b53ee764df319c1c7739a3b51bd",
          "md5": "c833e57a0ea5cf8e435d3126d7a75aff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0.jar",
          "url": "http-api-4.28.0.jar",
          "size": 88795,
          "sha512": "6f77d94c09b7cc3a957697e45c3ecae8ba415587206d8824125fddc90a2caa06f72374e531a7b0eeb28a8acbef8ec2162458c822dc225973badc749643c86d48",
          "sha256": "50066aefe951e8bebd26503464d00a36bfaafd8043a930aa6fbd2fc3ca42302c",
          "sha1": "89a5d201485d0b53ee764df319c1c7739a3b51bd",
          "md5": "c833e57a0ea5cf8e435d3126d7a75aff"
        }
      ]
    }
  ]
}
