{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88796,
          "sha512": "457c959a1bd38cf0fdb498459ff3c159c46e511d49846cdff17c815a257fc9047d62e2e493162a0d03f2bd933725640a8dda00bb2bce4d284faca1163c774e37",
          "sha256": "96ef8898679f9a53d708de6d31e8e333f45474e6e739a9872f23b0e0ba15f7fa",
          "sha1": "c507df3a80e52a05807e03a6f31b83904daacd5d",
          "md5": "e868c643dcd1f7b63d5f28ef608b3dc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88796,
          "sha512": "457c959a1bd38cf0fdb498459ff3c159c46e511d49846cdff17c815a257fc9047d62e2e493162a0d03f2bd933725640a8dda00bb2bce4d284faca1163c774e37",
          "sha256": "96ef8898679f9a53d708de6d31e8e333f45474e6e739a9872f23b0e0ba15f7fa",
          "sha1": "c507df3a80e52a05807e03a6f31b83904daacd5d",
          "md5": "e868c643dcd1f7b63d5f28ef608b3dc8"
        }
      ]
    }
  ]
}
