{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88796,
          "sha512": "093df8076934b02ec6769a53ae741f9a1ca24fe929d3a9f67028835aaf3f1bfd48e8e2d66dec588a14daea216d6c1780319008434cde986dae5aec5a6609360a",
          "sha256": "88c6f5f71f9ad1e098cceb1a68717a2814b9df63901527e64ad66fbb917eb2d3",
          "sha1": "adcf12d3e7b0f5f1a1d4fcd7f97e28a509ded21c",
          "md5": "d4b1d84380b8e6d945c76c0f47a58f42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88796,
          "sha512": "093df8076934b02ec6769a53ae741f9a1ca24fe929d3a9f67028835aaf3f1bfd48e8e2d66dec588a14daea216d6c1780319008434cde986dae5aec5a6609360a",
          "sha256": "88c6f5f71f9ad1e098cceb1a68717a2814b9df63901527e64ad66fbb917eb2d3",
          "sha1": "adcf12d3e7b0f5f1a1d4fcd7f97e28a509ded21c",
          "md5": "d4b1d84380b8e6d945c76c0f47a58f42"
        }
      ]
    }
  ]
}
