{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88797,
          "sha512": "e318fa04350302791e1cd5c6f8b5baf98ba77e9e277c4a9dea2672b2192fe8f141110c7b85389da4a3edda0b1f4d97b16c46d6dae20d7119801d7e5431d250f7",
          "sha256": "59ac755ceeefe1f04d37072c6c8079dc06f2fa62975c2933761dd371f8940ca2",
          "sha1": "74faafcfd42de02ff8ad0af4ddf828221b7a489d",
          "md5": "3ff54c6e0e8bf7aea8f1135eb9b1fa03"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.25.1.jar",
          "url": "http-api-4.25.1.jar",
          "size": 88797,
          "sha512": "e318fa04350302791e1cd5c6f8b5baf98ba77e9e277c4a9dea2672b2192fe8f141110c7b85389da4a3edda0b1f4d97b16c46d6dae20d7119801d7e5431d250f7",
          "sha256": "59ac755ceeefe1f04d37072c6c8079dc06f2fa62975c2933761dd371f8940ca2",
          "sha1": "74faafcfd42de02ff8ad0af4ddf828221b7a489d",
          "md5": "3ff54c6e0e8bf7aea8f1135eb9b1fa03"
        }
      ]
    }
  ]
}
