{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.1.jar",
          "url": "injector-plugin-2.0.1.jar",
          "size": 119796,
          "sha512": "fca78171b5676defc7778ed9ba190f13adbec4f73320bee947f16aa4aad5cde40393074f4ee61516dec61c7956ae8f99aab2930e1c28fbffdd4ffe94eb4e47f7",
          "sha256": "5b4cbeb044461547b7e6d5a0e99d57fac680c23bd15b563a8ebb9fb322de5269",
          "sha1": "064843352c5e0269b90c7c6b25499fd753221c6b",
          "md5": "c93bb0b984c80bd033e606f3f8930c82"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.1.jar",
          "url": "injector-plugin-2.0.1.jar",
          "size": 119796,
          "sha512": "fca78171b5676defc7778ed9ba190f13adbec4f73320bee947f16aa4aad5cde40393074f4ee61516dec61c7956ae8f99aab2930e1c28fbffdd4ffe94eb4e47f7",
          "sha256": "5b4cbeb044461547b7e6d5a0e99d57fac680c23bd15b563a8ebb9fb322de5269",
          "sha1": "064843352c5e0269b90c7c6b25499fd753221c6b",
          "md5": "c93bb0b984c80bd033e606f3f8930c82"
        }
      ]
    }
  ]
}
