{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.5-SNAPSHOT.jar",
          "url": "http-api-1.0.5-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "03268bbc6f101910726637edd772aff3e748ee7bdbc0012e170f27b1122340634d2873aaadac2a6ef7f3bbda9e2a79e8a003803ffcde387a04d1d19d7982fdeb",
          "sha256": "4ae41025a30798c275067c35cfaf8b60037efb35eafc79bd2b7228aba05bf9a1",
          "sha1": "a9772ff24b5d0585794931c611837f21aac92b6a",
          "md5": "7b2e942ecdf5c03b8169a6f7bb549f11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.5-SNAPSHOT.jar",
          "url": "http-api-1.0.5-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "03268bbc6f101910726637edd772aff3e748ee7bdbc0012e170f27b1122340634d2873aaadac2a6ef7f3bbda9e2a79e8a003803ffcde387a04d1d19d7982fdeb",
          "sha256": "4ae41025a30798c275067c35cfaf8b60037efb35eafc79bd2b7228aba05bf9a1",
          "sha1": "a9772ff24b5d0585794931c611837f21aac92b6a",
          "md5": "7b2e942ecdf5c03b8169a6f7bb549f11"
        }
      ]
    }
  ]
}
