{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.5-SNAPSHOT.jar",
          "url": "http-api-1.0.5-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "423a4191b88d2a89390dc9595fc3ad96251c710ee91fb47b8e165b4d2c99b0df5ddd63c69e130974b8f5b59bfff69e09482b713750e66e8f8d340bec6bc75419",
          "sha256": "0f15cf2df4cfc51e4559e1d88ef04b53b8c9356063750996f6866dfcd7249804",
          "sha1": "f420c28c9126824c089ff8061a72277c0e73d29b",
          "md5": "692c6e6a5d66047bbd4b7c78307f5dd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.5-SNAPSHOT.jar",
          "url": "http-api-1.0.5-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "423a4191b88d2a89390dc9595fc3ad96251c710ee91fb47b8e165b4d2c99b0df5ddd63c69e130974b8f5b59bfff69e09482b713750e66e8f8d340bec6bc75419",
          "sha256": "0f15cf2df4cfc51e4559e1d88ef04b53b8c9356063750996f6866dfcd7249804",
          "sha1": "f420c28c9126824c089ff8061a72277c0e73d29b",
          "md5": "692c6e6a5d66047bbd4b7c78307f5dd1"
        }
      ]
    }
  ]
}
