{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.5-SNAPSHOT.jar",
          "url": "http-api-1.0.5-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "af19f83524cc27465c77faa82d9b0e91e08f712ba9933c361b6158cc7f799d3a63134d6e29a9a494b5ca56afc0ea6e8f20284fc28cc9a19f6f534021570e98d5",
          "sha256": "5402b62418d9bf0e56f6a0b84547971843794b979a702f7253457d323baa8fcc",
          "sha1": "30df57177df824be9383ef2d516176e7d7462071",
          "md5": "ee7931a1ed3c59dc01f12ff589f66a85"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.5-SNAPSHOT.jar",
          "url": "http-api-1.0.5-SNAPSHOT.jar",
          "size": 85931,
          "sha512": "af19f83524cc27465c77faa82d9b0e91e08f712ba9933c361b6158cc7f799d3a63134d6e29a9a494b5ca56afc0ea6e8f20284fc28cc9a19f6f534021570e98d5",
          "sha256": "5402b62418d9bf0e56f6a0b84547971843794b979a702f7253457d323baa8fcc",
          "sha1": "30df57177df824be9383ef2d516176e7d7462071",
          "md5": "ee7931a1ed3c59dc01f12ff589f66a85"
        }
      ]
    }
  ]
}
