{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "605985e812c395d7bbe48269bb7ee2831abacace2c975a2c0a8f4b60c0379b034385670f077d11cc74bd178c065c07745441ca63b12edc1d4f531ee283854866",
          "sha256": "3b6817427de97c8633bfe0fc1d9fa9cfa911e97507ddcd8bcd3d6915c942e047",
          "sha1": "168457065f0e602dba9ab8a53342d4241777ed26",
          "md5": "29374feb35393a09168931b7a265ab64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "605985e812c395d7bbe48269bb7ee2831abacace2c975a2c0a8f4b60c0379b034385670f077d11cc74bd178c065c07745441ca63b12edc1d4f531ee283854866",
          "sha256": "3b6817427de97c8633bfe0fc1d9fa9cfa911e97507ddcd8bcd3d6915c942e047",
          "sha1": "168457065f0e602dba9ab8a53342d4241777ed26",
          "md5": "29374feb35393a09168931b7a265ab64"
        }
      ]
    }
  ]
}
