{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "b391766522d385e45e53a84612ea536bd1fb3d4ff43f6ca55ed4a237e3e5eed3551dddee09a22316d1ad1a772fc3a50cab94d386d67c49ed1351aade474ce2a2",
          "sha256": "651cb417a5fc4a5bbe1935145dada18c373766b3e1b547526e26f43c9945b05e",
          "sha1": "a7587f2f421aeb2380e2ca5623dcd05eae78b14b",
          "md5": "7374f38ac30fea669a4b207f87675d06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "b391766522d385e45e53a84612ea536bd1fb3d4ff43f6ca55ed4a237e3e5eed3551dddee09a22316d1ad1a772fc3a50cab94d386d67c49ed1351aade474ce2a2",
          "sha256": "651cb417a5fc4a5bbe1935145dada18c373766b3e1b547526e26f43c9945b05e",
          "sha1": "a7587f2f421aeb2380e2ca5623dcd05eae78b14b",
          "md5": "7374f38ac30fea669a4b207f87675d06"
        }
      ]
    }
  ]
}
