{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "cf5f2d65881544d959c5e60876506bfba25b8787c420ff94de6655abf6166a66ac83cdc86911344b1d1d3dd644f1a787d122845cc1a80da4a8c35cafc4652aab",
          "sha256": "1e46282c4ca10d42edec2c49403edf60a52efcee28a1114455df3f8e502afaea",
          "sha1": "b5f225ae5e042a7f8b00d5d02d83bbff8e35731b",
          "md5": "bf361881b847042f47811df3b79777e3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "cf5f2d65881544d959c5e60876506bfba25b8787c420ff94de6655abf6166a66ac83cdc86911344b1d1d3dd644f1a787d122845cc1a80da4a8c35cafc4652aab",
          "sha256": "1e46282c4ca10d42edec2c49403edf60a52efcee28a1114455df3f8e502afaea",
          "sha1": "b5f225ae5e042a7f8b00d5d02d83bbff8e35731b",
          "md5": "bf361881b847042f47811df3b79777e3"
        }
      ]
    }
  ]
}
