{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "324519a155a77a72b0e54687329661d7c1d6e7978cf5961f010f230baa1f5bddce82ca7e5f0e061390b020cc39948ceec3e4f0c8f50fe20baf2b59ccb1416dbd",
          "sha256": "6ce011f9d605c9462dd71cf9d126a1a1f859a575ae24eb83690d8acca024bf66",
          "sha1": "ba88e47a813d2f8e1c4e7128a1a3f8c091a3f427",
          "md5": "96bec1da30ba499546d818f3f2eb68bd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "324519a155a77a72b0e54687329661d7c1d6e7978cf5961f010f230baa1f5bddce82ca7e5f0e061390b020cc39948ceec3e4f0c8f50fe20baf2b59ccb1416dbd",
          "sha256": "6ce011f9d605c9462dd71cf9d126a1a1f859a575ae24eb83690d8acca024bf66",
          "sha1": "ba88e47a813d2f8e1c4e7128a1a3f8c091a3f427",
          "md5": "96bec1da30ba499546d818f3f2eb68bd"
        }
      ]
    }
  ]
}
