{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "91bf0ce9b71064c55a09b8604b8d19e414d48d200b5b7726399c6742c80285fb225f9e80718422b894daa31479b11e42bb6e8c4f852cf037a446ee37b8b8fcf1",
          "sha256": "d24ec40c2bc6b645cd719fdc9ae0b54caa3684cc95ec6b902aca661f6fc5c29f",
          "sha1": "78c4bd5144379360f5623cece8771ef4a9bcb233",
          "md5": "956fbafd1ae844bd65aa454ee3e9ced6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "91bf0ce9b71064c55a09b8604b8d19e414d48d200b5b7726399c6742c80285fb225f9e80718422b894daa31479b11e42bb6e8c4f852cf037a446ee37b8b8fcf1",
          "sha256": "d24ec40c2bc6b645cd719fdc9ae0b54caa3684cc95ec6b902aca661f6fc5c29f",
          "sha1": "78c4bd5144379360f5623cece8771ef4a9bcb233",
          "md5": "956fbafd1ae844bd65aa454ee3e9ced6"
        }
      ]
    }
  ]
}
