{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "b87a775c7ffe01d682b1e484db6bd706942ddcd269b0969c5714eed78b7617ce46f6ae1522a3f1ad5897d70a49869aa69fa0ed7252c7ff0bc3219aec8ad6476a",
          "sha256": "ddd8902f5d223d5582ffd2c16c8831d415c42ec56fcd7524a19d19aea0779d73",
          "sha1": "0cad31b9fe45e2e4561936529e56f64f262e60de",
          "md5": "65eecf22ae25c9f17278bb51ade39e77"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "b87a775c7ffe01d682b1e484db6bd706942ddcd269b0969c5714eed78b7617ce46f6ae1522a3f1ad5897d70a49869aa69fa0ed7252c7ff0bc3219aec8ad6476a",
          "sha256": "ddd8902f5d223d5582ffd2c16c8831d415c42ec56fcd7524a19d19aea0779d73",
          "sha1": "0cad31b9fe45e2e4561936529e56f64f262e60de",
          "md5": "65eecf22ae25c9f17278bb51ade39e77"
        }
      ]
    }
  ]
}
