{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "0af8d13d2479b33983cc94dec354bbf05eeb6c86459f55f3ac356952689a89c8e22aa7523c494748922abe376e6ba69b07b90807c40a9763b52c883d5996017f",
          "sha256": "7ca5ba73e750c1677453baf704ca2d4f88273a4707b323cccddd32149ec6fb99",
          "sha1": "217aa7142da06e416385eae7d3c129d5c7c26534",
          "md5": "3743f3380feba07ac75a574128dee23e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "0af8d13d2479b33983cc94dec354bbf05eeb6c86459f55f3ac356952689a89c8e22aa7523c494748922abe376e6ba69b07b90807c40a9763b52c883d5996017f",
          "sha256": "7ca5ba73e750c1677453baf704ca2d4f88273a4707b323cccddd32149ec6fb99",
          "sha1": "217aa7142da06e416385eae7d3c129d5c7c26534",
          "md5": "3743f3380feba07ac75a574128dee23e"
        }
      ]
    }
  ]
}
