{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "dd81e857ef49cb68dce8944c45f1c8def501b18b32cac52d521cb858c44ddca7047cea0db260b8ed7ae58bcb28ec86ee27054c88f8741da986c0e2aa49d575e2",
          "sha256": "47c4df1cfc20ef8c1adbed515fd6a231d3aad800dc45819ad467db724a29c3b9",
          "sha1": "1ad66451f79f8fb65fc9b555f921792779fc9e26",
          "md5": "311b8b38ecf99f62a416830292eb4ac2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "dd81e857ef49cb68dce8944c45f1c8def501b18b32cac52d521cb858c44ddca7047cea0db260b8ed7ae58bcb28ec86ee27054c88f8741da986c0e2aa49d575e2",
          "sha256": "47c4df1cfc20ef8c1adbed515fd6a231d3aad800dc45819ad467db724a29c3b9",
          "sha1": "1ad66451f79f8fb65fc9b555f921792779fc9e26",
          "md5": "311b8b38ecf99f62a416830292eb4ac2"
        }
      ]
    }
  ]
}
