{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "87843d866fe3a3d65ecaca8be1025bae60330fab03755eefea1f70975c9ab1be6c7e1c151d03fc0371bf82907d31bd4b8dcc1726a466e0d8f5fee6436511ffae",
          "sha256": "00899c8fee4f2c36a95f860b2958f0c55b55f06348068b593993da8ef797ccc1",
          "sha1": "635a304c6682e5884f0cf69cea95030f94bc4931",
          "md5": "22b636a4e15f9b99af9de320b0825394"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "87843d866fe3a3d65ecaca8be1025bae60330fab03755eefea1f70975c9ab1be6c7e1c151d03fc0371bf82907d31bd4b8dcc1726a466e0d8f5fee6436511ffae",
          "sha256": "00899c8fee4f2c36a95f860b2958f0c55b55f06348068b593993da8ef797ccc1",
          "sha1": "635a304c6682e5884f0cf69cea95030f94bc4931",
          "md5": "22b636a4e15f9b99af9de320b0825394"
        }
      ]
    }
  ]
}
