{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "f81380ebd18dd013ed157af9a9d9bc2ce9dcaaf6332f6955dc545c91050532ad205245526ed7c44230db9c12713300f9c67db323ae429eef852cfc869cdf72b8",
          "sha256": "4d50925d7de1fac3308e7c356466fde7d1f8ce4f193c4a9decadb89bbe40c6b4",
          "sha1": "29bf5bb2f43c5bfede321a84a6155ef8c25e7dcd",
          "md5": "41fd727d3238731e2837e6abdc3987a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "f81380ebd18dd013ed157af9a9d9bc2ce9dcaaf6332f6955dc545c91050532ad205245526ed7c44230db9c12713300f9c67db323ae429eef852cfc869cdf72b8",
          "sha256": "4d50925d7de1fac3308e7c356466fde7d1f8ce4f193c4a9decadb89bbe40c6b4",
          "sha1": "29bf5bb2f43c5bfede321a84a6155ef8c25e7dcd",
          "md5": "41fd727d3238731e2837e6abdc3987a5"
        }
      ]
    }
  ]
}
