{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "e0f83c0539cefa191269c79c2ed690eea97c72a13ac777473215e40cb677f8c528ebb7ac134269553c538aa9950ea1825199702e4c32a8a20be36be7c09213cc",
          "sha256": "f678ce1b524b592b12a8ca21029fb85b4fba8aaf6a4240bedaed8fee832ba217",
          "sha1": "c534258e60a0bebe084b792754971264e63d67b5",
          "md5": "9dafdbd70ba30d00ca88342906f70031"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "e0f83c0539cefa191269c79c2ed690eea97c72a13ac777473215e40cb677f8c528ebb7ac134269553c538aa9950ea1825199702e4c32a8a20be36be7c09213cc",
          "sha256": "f678ce1b524b592b12a8ca21029fb85b4fba8aaf6a4240bedaed8fee832ba217",
          "sha1": "c534258e60a0bebe084b792754971264e63d67b5",
          "md5": "9dafdbd70ba30d00ca88342906f70031"
        }
      ]
    }
  ]
}
