{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "6af32bc002f59e933b9b4d043d177c03ce6b15324f63064154d467835d451bd9ddfac70ee68492469bdadcb07a7ebfb3277b6d95bbdf5ce5aa18555d72859943",
          "sha256": "62ff2d05cd8928caafd01d718264be3ddc61097b289702416b02c559d40f4d9c",
          "sha1": "b3fd62c1aacbd8f05130ded52f55643f34c41071",
          "md5": "665d19b8cf2cbc8cf16ad0cd67c3f78d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "6af32bc002f59e933b9b4d043d177c03ce6b15324f63064154d467835d451bd9ddfac70ee68492469bdadcb07a7ebfb3277b6d95bbdf5ce5aa18555d72859943",
          "sha256": "62ff2d05cd8928caafd01d718264be3ddc61097b289702416b02c559d40f4d9c",
          "sha1": "b3fd62c1aacbd8f05130ded52f55643f34c41071",
          "md5": "665d19b8cf2cbc8cf16ad0cd67c3f78d"
        }
      ]
    }
  ]
}
