{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "4c85336fb27a50595590f0564d32134c9d3ad25146d42883177d274e43285fbadba3b59daeebd92c0d2c6a4a381aaf39e623ee920ed721c917374e14d52d7edd",
          "sha256": "7a252e0e16a59f262782f1c777b1d174c5a8ce4cba8fa4b924805dbf6c14089a",
          "sha1": "d4cb9034ac8e6ae42ad9044872eb83d618f5acb1",
          "md5": "cb9e4e5f16fc49b891bae8244149bc57"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "4c85336fb27a50595590f0564d32134c9d3ad25146d42883177d274e43285fbadba3b59daeebd92c0d2c6a4a381aaf39e623ee920ed721c917374e14d52d7edd",
          "sha256": "7a252e0e16a59f262782f1c777b1d174c5a8ce4cba8fa4b924805dbf6c14089a",
          "sha1": "d4cb9034ac8e6ae42ad9044872eb83d618f5acb1",
          "md5": "cb9e4e5f16fc49b891bae8244149bc57"
        }
      ]
    }
  ]
}
