{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.26.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "5efeff3e0965a48923b56bd4f2eff4ce0f077f3e172e7586f8f87bcb0ddcb9126e43a94e6c59e672fb426b878ed2ef050cd7a7344aaf58636397bb52af47a0a6",
          "sha256": "9534236da2ada0d8c2e9ee1d88f66c47b2f648728df17de49fd426040fa027c1",
          "sha1": "06770bd7eddb1eef1facac0077b716179dda7e2b",
          "md5": "e1adb2e510b7e7b63d81ff9ad3d8955e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.26.1-SNAPSHOT.jar",
          "url": "http-api-4.26.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "5efeff3e0965a48923b56bd4f2eff4ce0f077f3e172e7586f8f87bcb0ddcb9126e43a94e6c59e672fb426b878ed2ef050cd7a7344aaf58636397bb52af47a0a6",
          "sha256": "9534236da2ada0d8c2e9ee1d88f66c47b2f648728df17de49fd426040fa027c1",
          "sha1": "06770bd7eddb1eef1facac0077b716179dda7e2b",
          "md5": "e1adb2e510b7e7b63d81ff9ad3d8955e"
        }
      ]
    }
  ]
}
