{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.27.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.27.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.27.0-SNAPSHOT.jar",
          "url": "runescape-api-4.27.0-SNAPSHOT.jar",
          "size": 122232,
          "sha512": "83ecb75b5f97484cbd8e70878caad2cd39a282f5966e4d44c633a7caa7392429710659b471b35410459a38052395d17ba0f365452b4ee9552a4b1939d2abd068",
          "sha256": "86e97d0e8592a11dd5b4cd01ad9ec90b17e137b35c86b1e53cc5a04cd6cc3f93",
          "sha1": "2e1acb5563fe2e39b235214136de7c5e34eff1d0",
          "md5": "ff57723ebf46a8ae3f6f758764efea26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.27.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.27.0-SNAPSHOT.jar",
          "url": "runescape-api-4.27.0-SNAPSHOT.jar",
          "size": 122232,
          "sha512": "83ecb75b5f97484cbd8e70878caad2cd39a282f5966e4d44c633a7caa7392429710659b471b35410459a38052395d17ba0f365452b4ee9552a4b1939d2abd068",
          "sha256": "86e97d0e8592a11dd5b4cd01ad9ec90b17e137b35c86b1e53cc5a04cd6cc3f93",
          "sha1": "2e1acb5563fe2e39b235214136de7c5e34eff1d0",
          "md5": "ff57723ebf46a8ae3f6f758764efea26"
        }
      ]
    }
  ]
}
