{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.3-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.3-SNAPSHOT.jar",
          "url": "runescape-api-1.0.3-SNAPSHOT.jar",
          "size": 127733,
          "sha512": "3881338b5545e08efb5a60df5fdcc07ac68912b3bf1d069b4846d4644ec2099548b7e38f4a6d5d4f95abdbc414335545825499fd65d48b9d01b00226d5c2f7f1",
          "sha256": "8c7eae0831ba69f972daa4ac35156fa48c9dee21289fb9b2e5a34679530a3e73",
          "sha1": "a61b4c8c3ad5d14b9eb43bf712c9827f277fe22f",
          "md5": "98a3063aecca72f93daeed021bf96068"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.3-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.3-SNAPSHOT.jar",
          "url": "runescape-api-1.0.3-SNAPSHOT.jar",
          "size": 127733,
          "sha512": "3881338b5545e08efb5a60df5fdcc07ac68912b3bf1d069b4846d4644ec2099548b7e38f4a6d5d4f95abdbc414335545825499fd65d48b9d01b00226d5c2f7f1",
          "sha256": "8c7eae0831ba69f972daa4ac35156fa48c9dee21289fb9b2e5a34679530a3e73",
          "sha1": "a61b4c8c3ad5d14b9eb43bf712c9827f277fe22f",
          "md5": "98a3063aecca72f93daeed021bf96068"
        }
      ]
    }
  ]
}
