{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "3hllzp6lr5gsjfxcqwsismswui"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "injector-plugin-1.1.3.jar",
          "url": "injector-plugin-1.1.3.jar",
          "size": 104423,
          "sha512": "44cd96473b2d5a254191c696bdd10a3cbfdf587ccbb1ce245b0362f0d665812ae1bacd63b33c133eb35be3bcc7c069e5e3941b93b78e79d5630b43beb1e38b33",
          "sha256": "d87217203c93e7c451bbf4c0d514760ce8c24925efb041180dcda42915127ab9",
          "sha1": "730ba0f7d2c59787f01c0f5934f39e38ca1f5b3d",
          "md5": "e94f7dd9f941d075aff3bbae9719e7bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "19.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "3.3.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "injector-plugin-1.1.3.jar",
          "url": "injector-plugin-1.1.3.jar",
          "size": 104423,
          "sha512": "44cd96473b2d5a254191c696bdd10a3cbfdf587ccbb1ce245b0362f0d665812ae1bacd63b33c133eb35be3bcc7c069e5e3941b93b78e79d5630b43beb1e38b33",
          "sha256": "d87217203c93e7c451bbf4c0d514760ce8c24925efb041180dcda42915127ab9",
          "sha1": "730ba0f7d2c59787f01c0f5934f39e38ca1f5b3d",
          "md5": "e94f7dd9f941d075aff3bbae9719e7bb"
        }
      ]
    }
  ]
}
