{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88826,
          "sha512": "c7aca104f90846562ef6286fa35a6e8a00a798b5e8b6a59e65c1d44e376cef0cbe6b65d08791a75ced42464b7296d104be5fde83dcf2653c838ef1c06c0b77e2",
          "sha256": "cd395a803229f5c75f5e0f79df05259a3996ef838a67f9fc4b90d3e2d835fa94",
          "sha1": "dfea359928e6334c07aec438af3d96f8eb1fb8fd",
          "md5": "3ccefc9f9a69b991d0d7944a26a35481"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88826,
          "sha512": "c7aca104f90846562ef6286fa35a6e8a00a798b5e8b6a59e65c1d44e376cef0cbe6b65d08791a75ced42464b7296d104be5fde83dcf2653c838ef1c06c0b77e2",
          "sha256": "cd395a803229f5c75f5e0f79df05259a3996ef838a67f9fc4b90d3e2d835fa94",
          "sha1": "dfea359928e6334c07aec438af3d96f8eb1fb8fd",
          "md5": "3ccefc9f9a69b991d0d7944a26a35481"
        }
      ]
    }
  ]
}
