{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88825,
          "sha512": "5c879113576fb4ae277282129a883a67681365dfa1e934737f601c98d66351e98eb8fe5768544f930d2dc7c7279fc345ea7f1212012d2ad383170fc6166e5a39",
          "sha256": "bcd020c4f7c1b730fcd2961f87a013fd7bfa2bba4406be7b092aa0bad81d4d76",
          "sha1": "d86204bf163f0bfdbfd04f0503c9c50c0d9b63f4",
          "md5": "ddf9ba200e45bb531d6143cbe0e1394e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88825,
          "sha512": "5c879113576fb4ae277282129a883a67681365dfa1e934737f601c98d66351e98eb8fe5768544f930d2dc7c7279fc345ea7f1212012d2ad383170fc6166e5a39",
          "sha256": "bcd020c4f7c1b730fcd2961f87a013fd7bfa2bba4406be7b092aa0bad81d4d76",
          "sha1": "d86204bf163f0bfdbfd04f0503c9c50c0d9b63f4",
          "md5": "ddf9ba200e45bb531d6143cbe0e1394e"
        }
      ]
    }
  ]
}
