{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88826,
          "sha512": "366b91a3813fe8bd837e5378b9028e8fa494cab0da9424ddc6b683edf54e3a08956874ff6b3e8af2cb25b8b46185de92740fdabdfe33a1772bb4722e2241db10",
          "sha256": "0e55f63fe4e2cfc2ccb18db647e11812234b1b90eb0068659f3b7cf94c77fd98",
          "sha1": "ad54c3bae401ddf190e969715900ea22fb1021d7",
          "md5": "6eb97ff1e6eae750b5b8f6099e8c24a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.2.jar",
          "url": "http-api-1.0.2.jar",
          "size": 88826,
          "sha512": "366b91a3813fe8bd837e5378b9028e8fa494cab0da9424ddc6b683edf54e3a08956874ff6b3e8af2cb25b8b46185de92740fdabdfe33a1772bb4722e2241db10",
          "sha256": "0e55f63fe4e2cfc2ccb18db647e11812234b1b90eb0068659f3b7cf94c77fd98",
          "sha1": "ad54c3bae401ddf190e969715900ea22fb1021d7",
          "md5": "6eb97ff1e6eae750b5b8f6099e8c24a6"
        }
      ]
    }
  ]
}
