{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-EXPERIMENTAL.jar",
          "url": "http-api-1.0.4-EXPERIMENTAL.jar",
          "size": 85931,
          "sha512": "cc17b262fb3bb4afd6f8f59880cde811284308a3ec229b5f6b45e96fbeb8ea48ee5b27ae0630f247ad4b82e23a2282bc107e8fc7d6e248a1009db6f59a9e7b53",
          "sha256": "d6645a2f155363673ab684f231741408f48939d72545bf9f8530e2b9d30f2b6f",
          "sha1": "57d86bdffd94bd0955538581378c6b6980131e41",
          "md5": "a485eb17385c0de615b5eeb0080b8914"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-EXPERIMENTAL.jar",
          "url": "http-api-1.0.4-EXPERIMENTAL.jar",
          "size": 85931,
          "sha512": "cc17b262fb3bb4afd6f8f59880cde811284308a3ec229b5f6b45e96fbeb8ea48ee5b27ae0630f247ad4b82e23a2282bc107e8fc7d6e248a1009db6f59a9e7b53",
          "sha256": "d6645a2f155363673ab684f231741408f48939d72545bf9f8530e2b9d30f2b6f",
          "sha1": "57d86bdffd94bd0955538581378c6b6980131e41",
          "md5": "a485eb17385c0de615b5eeb0080b8914"
        }
      ]
    }
  ]
}
