{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-EXPERIMENTAL.jar",
          "url": "http-api-1.0.4-EXPERIMENTAL.jar",
          "size": 85931,
          "sha512": "afe1dd47d96d6f553d6d50f902e08f690c10c2c0cb8d6797bab2a26cf4176b825ae51d9afe1b26c09aad241da4f0dec0293ef3bc7ce3db8140c00045976e500b",
          "sha256": "35429049c57947c0cb9ce5f2412f5ea8f423f5e570c26bf6754e5e8b529ab30f",
          "sha1": "d8095eff0854bd40e63a0a8ba12bf41c1083ace3",
          "md5": "98601410e61773a0ab0580dd369d09a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-EXPERIMENTAL.jar",
          "url": "http-api-1.0.4-EXPERIMENTAL.jar",
          "size": 85931,
          "sha512": "afe1dd47d96d6f553d6d50f902e08f690c10c2c0cb8d6797bab2a26cf4176b825ae51d9afe1b26c09aad241da4f0dec0293ef3bc7ce3db8140c00045976e500b",
          "sha256": "35429049c57947c0cb9ce5f2412f5ea8f423f5e570c26bf6754e5e8b529ab30f",
          "sha1": "d8095eff0854bd40e63a0a8ba12bf41c1083ace3",
          "md5": "98601410e61773a0ab0580dd369d09a1"
        }
      ]
    }
  ]
}
