{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.4-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.4-EXPERIMENTAL.jar",
          "url": "http-api-1.0.4-EXPERIMENTAL.jar",
          "size": 85931,
          "sha512": "3083d80488903f458d8e7e637769613d0ff0acd9d064c814a31cf1eef4022e4b6b5e8925d100b5e187a1421138dc6f148164f532d0ccba46b7fcedb437e08f4b",
          "sha256": "f3d645f58080ba7891a66308522b0553d316b66b3e234c00d92e4bf83025b942",
          "sha1": "7ec6b1ff020e6f1bae90956a8d53aef1cda0d921",
          "md5": "f182236ed1702bda286d7f22e73fabc8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.4-EXPERIMENTAL.jar",
          "url": "http-api-1.0.4-EXPERIMENTAL.jar",
          "size": 85931,
          "sha512": "3083d80488903f458d8e7e637769613d0ff0acd9d064c814a31cf1eef4022e4b6b5e8925d100b5e187a1421138dc6f148164f532d0ccba46b7fcedb437e08f4b",
          "sha256": "f3d645f58080ba7891a66308522b0553d316b66b3e234c00d92e4bf83025b942",
          "sha1": "7ec6b1ff020e6f1bae90956a8d53aef1cda0d921",
          "md5": "f182236ed1702bda286d7f22e73fabc8"
        }
      ]
    }
  ]
}
