{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 121999,
          "sha512": "04ab9b8e2b8f604ae824ca05a2a28e32954508e0c3a4b89a7866ca2dcd566dba9e64f426b29743943baaa146931036629cf198dda806ca9ff3de9e62c945c7cb",
          "sha256": "905e7ca7e157d83ee6f9f7a720a767562a96f84d33056b8443bc0b539c983510",
          "sha1": "beb4622bb4267863e5344f2b633642c0c2f68dc9",
          "md5": "a5c8ab1ba01b03a95c776c16f4c43166"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.1.jar",
          "url": "runescape-api-4.25.1.jar",
          "size": 121999,
          "sha512": "04ab9b8e2b8f604ae824ca05a2a28e32954508e0c3a4b89a7866ca2dcd566dba9e64f426b29743943baaa146931036629cf198dda806ca9ff3de9e62c945c7cb",
          "sha256": "905e7ca7e157d83ee6f9f7a720a767562a96f84d33056b8443bc0b539c983510",
          "sha1": "beb4622bb4267863e5344f2b633642c0c2f68dc9",
          "md5": "a5c8ab1ba01b03a95c776c16f4c43166"
        }
      ]
    }
  ]
}
