{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.29.0-SNAPSHOT.jar",
          "url": "runelite-api-4.29.0-SNAPSHOT.jar",
          "size": 1365130,
          "sha512": "57388a82e83e8a269ea77f0acad36e2535c09121c479cf395ad0ff085473114ef5f6b79187aae4626351103ad9de315fe728372b309fcd185387d04c990282f8",
          "sha256": "8bade27b81619b2f6a78aac94c53fe18c8f3ddd7966b34782abf552cf24c2434",
          "sha1": "a1ffb2163c473af01183d70f563a82aec22a8241",
          "md5": "7d81dba29158e4e4d8a97141fa933a21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.29.0-SNAPSHOT.jar",
          "url": "runelite-api-4.29.0-SNAPSHOT.jar",
          "size": 1365130,
          "sha512": "57388a82e83e8a269ea77f0acad36e2535c09121c479cf395ad0ff085473114ef5f6b79187aae4626351103ad9de315fe728372b309fcd185387d04c990282f8",
          "sha256": "8bade27b81619b2f6a78aac94c53fe18c8f3ddd7966b34782abf552cf24c2434",
          "sha1": "a1ffb2163c473af01183d70f563a82aec22a8241",
          "md5": "7d81dba29158e4e4d8a97141fa933a21"
        }
      ]
    }
  ]
}
