{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.29.0-SNAPSHOT.jar",
          "url": "runelite-api-4.29.0-SNAPSHOT.jar",
          "size": 1364521,
          "sha512": "aa284bdb450d5c88ca277aa835f93837980a63723c18877fc0652f979649b0af9bebeceaefa2b7d1fc8542c0dcacf6cd811afa2acfa7deaf15ae8f1dd8937a5f",
          "sha256": "1c43374841429beae0609270238b4c0f887d52545d6b286a3b3e777354791547",
          "sha1": "79eda9a7a0620e1e67fee92d97b6b15afde4a3df",
          "md5": "4ee8e242239c82129e495c17a056e22e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.29.0-SNAPSHOT.jar",
          "url": "runelite-api-4.29.0-SNAPSHOT.jar",
          "size": 1364521,
          "sha512": "aa284bdb450d5c88ca277aa835f93837980a63723c18877fc0652f979649b0af9bebeceaefa2b7d1fc8542c0dcacf6cd811afa2acfa7deaf15ae8f1dd8937a5f",
          "sha256": "1c43374841429beae0609270238b4c0f887d52545d6b286a3b3e777354791547",
          "sha1": "79eda9a7a0620e1e67fee92d97b6b15afde4a3df",
          "md5": "4ee8e242239c82129e495c17a056e22e"
        }
      ]
    }
  ]
}
