{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.29.0-SNAPSHOT.jar",
          "url": "runelite-api-4.29.0-SNAPSHOT.jar",
          "size": 1364600,
          "sha512": "3292534802f1b1c03db1537c2999dbc1c9204fae38b0d46248051f09955bb23dafcb52d45377e5724232dcd11863d16fcbf5967cbd15ef953d0dbfca0c3434d3",
          "sha256": "520958c28f18f83fec96762d1c2b93acae4f6dd3ab333f8656f9809f4aad5e97",
          "sha1": "e6c4b7536226031fee4e8d5ebab500597ea4cae2",
          "md5": "b6644c65f37760f5788adb86b16948da"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.29.0-SNAPSHOT.jar",
          "url": "runelite-api-4.29.0-SNAPSHOT.jar",
          "size": 1364600,
          "sha512": "3292534802f1b1c03db1537c2999dbc1c9204fae38b0d46248051f09955bb23dafcb52d45377e5724232dcd11863d16fcbf5967cbd15ef953d0dbfca0c3434d3",
          "sha256": "520958c28f18f83fec96762d1c2b93acae4f6dd3ab333f8656f9809f4aad5e97",
          "sha1": "e6c4b7536226031fee4e8d5ebab500597ea4cae2",
          "md5": "b6644c65f37760f5788adb86b16948da"
        }
      ]
    }
  ]
}
