{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.29.0-SNAPSHOT.jar",
          "url": "runelite-api-4.29.0-SNAPSHOT.jar",
          "size": 1365049,
          "sha512": "2b507c674dc8fdb32becc92ff480117fb00ade1360e507db00e573d2c8dbfac54da7ccf98564bbe97086567ee03c17465c25b68e01f3e93f1673b1831cde3472",
          "sha256": "526bde6fac1552bdfe3dad11d17e192f52e776184c8dc3ba68566f9b91ae2a3a",
          "sha1": "611fe6a9c5935796eb4650bc32114c5d47a5e722",
          "md5": "fa1997e0de8375a275b3ee74672672ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.29.0-SNAPSHOT.jar",
          "url": "runelite-api-4.29.0-SNAPSHOT.jar",
          "size": 1365049,
          "sha512": "2b507c674dc8fdb32becc92ff480117fb00ade1360e507db00e573d2c8dbfac54da7ccf98564bbe97086567ee03c17465c25b68e01f3e93f1673b1831cde3472",
          "sha256": "526bde6fac1552bdfe3dad11d17e192f52e776184c8dc3ba68566f9b91ae2a3a",
          "sha1": "611fe6a9c5935796eb4650bc32114c5d47a5e722",
          "md5": "fa1997e0de8375a275b3ee74672672ad"
        }
      ]
    }
  ]
}
