{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.6-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6-EXPERIMENTAL"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runescape-api-1.0.6-EXPERIMENTAL.jar",
          "size": 127833,
          "sha512": "64e6032c08a4cb49a233c8e9dd2b8c1c0962cb7149aa20754387e7888872bf7663410adb23a76d5f63a6be02f113061078a49d88a08cefab4e9813b67733a2ad",
          "sha256": "336abe7822198ad4d2a532b06d8bac5ca3324e6dc2397e11de6df04b91a1d90f",
          "sha1": "f5f9cbfc3f9c42cd2a28c2fe8a34babe402205a7",
          "md5": "2caf130599f4687df595c838914ed219"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6-EXPERIMENTAL"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runescape-api-1.0.6-EXPERIMENTAL.jar",
          "size": 127833,
          "sha512": "64e6032c08a4cb49a233c8e9dd2b8c1c0962cb7149aa20754387e7888872bf7663410adb23a76d5f63a6be02f113061078a49d88a08cefab4e9813b67733a2ad",
          "sha256": "336abe7822198ad4d2a532b06d8bac5ca3324e6dc2397e11de6df04b91a1d90f",
          "sha1": "f5f9cbfc3f9c42cd2a28c2fe8a34babe402205a7",
          "md5": "2caf130599f4687df595c838914ed219"
        }
      ]
    }
  ]
}
