{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.6-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6-EXPERIMENTAL"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runescape-api-1.0.6-EXPERIMENTAL.jar",
          "size": 126086,
          "sha512": "3cc46abb08255e1dd4c4c0e0b5477ae1da73f1665484f9a48be67c12488cb99265742fbc6e376d38255860ed0b229c47ef4d6a07d0e4866ccca60118b23f6df8",
          "sha256": "ff3eb70e38b3bc26be7014c312b6e80d688a26cc3352315164ba725c7b0abb25",
          "sha1": "50527098ba5adb579fadf8351bb1a90120d34a58",
          "md5": "11cc4955c0a8ee64937493f7140d5e8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.6-EXPERIMENTAL"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.6-EXPERIMENTAL.jar",
          "url": "runescape-api-1.0.6-EXPERIMENTAL.jar",
          "size": 126086,
          "sha512": "3cc46abb08255e1dd4c4c0e0b5477ae1da73f1665484f9a48be67c12488cb99265742fbc6e376d38255860ed0b229c47ef4d6a07d0e4866ccca60118b23f6df8",
          "sha256": "ff3eb70e38b3bc26be7014c312b6e80d688a26cc3352315164ba725c7b0abb25",
          "sha1": "50527098ba5adb579fadf8351bb1a90120d34a58",
          "md5": "11cc4955c0a8ee64937493f7140d5e8b"
        }
      ]
    }
  ]
}
