{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1365221,
          "sha512": "0a77138910c8251290bdf0cc9a8edaf4fa77f9780c3bda6a5d6ad035f84290c1224f6db1aca9787140c0144c8227af6d4babb4abd65e07d18b6b0ddd4b59a606",
          "sha256": "bfd7664053df543953d473d6ec547e41f1bb6a82a6793f868f0c6743c303e7f9",
          "sha1": "3b8ee340a1d7e05e0b22769e0334539adf7d957a",
          "md5": "4709c9870f09b2236b2b26140c062ad1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1365221,
          "sha512": "0a77138910c8251290bdf0cc9a8edaf4fa77f9780c3bda6a5d6ad035f84290c1224f6db1aca9787140c0144c8227af6d4babb4abd65e07d18b6b0ddd4b59a606",
          "sha256": "bfd7664053df543953d473d6ec547e41f1bb6a82a6793f868f0c6743c303e7f9",
          "sha1": "3b8ee340a1d7e05e0b22769e0334539adf7d957a",
          "md5": "4709c9870f09b2236b2b26140c062ad1"
        }
      ]
    }
  ]
}
