{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1365254,
          "sha512": "59e2e2783713e66c0f6dcdd174c803d077ea91745c5e5be859f8b6547fec0fabd01e75d592f05225961046282ec8f0dfbb4b701fe57e31eaf31b7104d75cb043",
          "sha256": "ee7f0a1b8894ed40d0fdc71bd7d784f422f55855e0e17f3e95ce4d22edcc72e4",
          "sha1": "ced15ddf5c3b3e00c1aa36c1f901a3bceb6e5684",
          "md5": "fde4756e7c58435ae09c10fc6bdb7472"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1365254,
          "sha512": "59e2e2783713e66c0f6dcdd174c803d077ea91745c5e5be859f8b6547fec0fabd01e75d592f05225961046282ec8f0dfbb4b701fe57e31eaf31b7104d75cb043",
          "sha256": "ee7f0a1b8894ed40d0fdc71bd7d784f422f55855e0e17f3e95ce4d22edcc72e4",
          "sha1": "ced15ddf5c3b3e00c1aa36c1f901a3bceb6e5684",
          "md5": "fde4756e7c58435ae09c10fc6bdb7472"
        }
      ]
    }
  ]
}
