{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1365451,
          "sha512": "f1cc067aaef8feebaf79b2910202a0a64b6b3b2e839436b1694c4bdc9ec956adb33bae4dbebf8c7bdfa3abb2c9ba6196b93828d44cb452431dc9db35af539140",
          "sha256": "9fbe7f94b02c9e3d12a62871c748d35cbc242b43828c23ca82debc3c109665ef",
          "sha1": "649baf2f8b0e4bd0f64f20660010ce793dcecf10",
          "md5": "e41135a8b3ae4a2fb35b5d7af8130f07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.30.0.jar",
          "url": "runelite-api-4.30.0.jar",
          "size": 1365451,
          "sha512": "f1cc067aaef8feebaf79b2910202a0a64b6b3b2e839436b1694c4bdc9ec956adb33bae4dbebf8c7bdfa3abb2c9ba6196b93828d44cb452431dc9db35af539140",
          "sha256": "9fbe7f94b02c9e3d12a62871c748d35cbc242b43828c23ca82debc3c109665ef",
          "sha1": "649baf2f8b0e4bd0f64f20660010ce793dcecf10",
          "md5": "e41135a8b3ae4a2fb35b5d7af8130f07"
        }
      ]
    }
  ]
}
