{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2-SNAPSHOT.jar",
          "url": "runescape-api-4.25.2-SNAPSHOT.jar",
          "size": 122042,
          "sha512": "21b59c04831223a342662c40c42a7fb2348f41f97c406678b33b656799c0a6e9ffa565b36f7a44399f6adae86640acd706cf52d478b16228936c631b1095a942",
          "sha256": "0c06cbb3fde8404fcdc60f558d47494fc41ed67da5f76462d1b8628acdb78040",
          "sha1": "d0f4c759bec2e3bbcc78d8b055e0e153ef56b71a",
          "md5": "e7f26e42315647d5211c1d683b4d2552"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.25.2-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.25.2-SNAPSHOT.jar",
          "url": "runescape-api-4.25.2-SNAPSHOT.jar",
          "size": 122042,
          "sha512": "21b59c04831223a342662c40c42a7fb2348f41f97c406678b33b656799c0a6e9ffa565b36f7a44399f6adae86640acd706cf52d478b16228936c631b1095a942",
          "sha256": "0c06cbb3fde8404fcdc60f558d47494fc41ed67da5f76462d1b8628acdb78040",
          "sha1": "d0f4c759bec2e3bbcc78d8b055e0e153ef56b71a",
          "md5": "e7f26e42315647d5211c1d683b4d2552"
        }
      ]
    }
  ]
}
