{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.0.jar",
          "url": "http-api-1.0.0.jar",
          "size": 88795,
          "sha512": "8c0ed8f7ee449602eb8c8697e5ee368b6f543c0e1701aa7a2e9f701e3158ab93b4c902def5a5497abd2dae89ffb0924ac65d2bb952499214ff152e9b63a9615b",
          "sha256": "c67a0260e485f3f348d7838c26425ebb01f9cb293ad45e2ea8abec666bbd9d04",
          "sha1": "84ca98245555d7b445207bd93664deff848c2d45",
          "md5": "08517f8d69fe4fd4ed396e081c5b8cd6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.0.jar",
          "url": "http-api-1.0.0.jar",
          "size": 88795,
          "sha512": "8c0ed8f7ee449602eb8c8697e5ee368b6f543c0e1701aa7a2e9f701e3158ab93b4c902def5a5497abd2dae89ffb0924ac65d2bb952499214ff152e9b63a9615b",
          "sha256": "c67a0260e485f3f348d7838c26425ebb01f9cb293ad45e2ea8abec666bbd9d04",
          "sha1": "84ca98245555d7b445207bd93664deff848c2d45",
          "md5": "08517f8d69fe4fd4ed396e081c5b8cd6"
        }
      ]
    }
  ]
}
