{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.1-SNAPSHOT.jar",
          "url": "http-api-1.0.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "a94cd2b711f22ded04e0fb75232acb5de3162fa4b912182db61e877cfb849c1f5f47c73e1591276666aa2f2e2c5ebd52dfd79f8b619ed06db0f17403ba85288a",
          "sha256": "a642f3a9c82a63ea03f20a80247e69dc18918568f7226a72f617b58a6ec17ae7",
          "sha1": "9c14782eac2ecec9a7c96e05777eac28818294e8",
          "md5": "5b869f8eb573981fbf32332f439da002"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.1-SNAPSHOT.jar",
          "url": "http-api-1.0.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "a94cd2b711f22ded04e0fb75232acb5de3162fa4b912182db61e877cfb849c1f5f47c73e1591276666aa2f2e2c5ebd52dfd79f8b619ed06db0f17403ba85288a",
          "sha256": "a642f3a9c82a63ea03f20a80247e69dc18918568f7226a72f617b58a6ec17ae7",
          "sha1": "9c14782eac2ecec9a7c96e05777eac28818294e8",
          "md5": "5b869f8eb573981fbf32332f439da002"
        }
      ]
    }
  ]
}
