{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.1-SNAPSHOT.jar",
          "url": "http-api-1.0.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "9ba0c53d17442033aa7dacdec8019187bac855d1b0f212569efc93afbb5636bfd9b260a59b852585523e6f6ec28d1f872fdfc1926e9c24886b6270899cfaf75b",
          "sha256": "d8519934f1f15219a2bc9441028681ea039163d4a1d15e310f9901cb017e02cd",
          "sha1": "49bec4d4ba26fe69b9633866b2aa82d47fe61f15",
          "md5": "319a843cc98ff6e91c55d017fe3753a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.1-SNAPSHOT.jar",
          "url": "http-api-1.0.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "9ba0c53d17442033aa7dacdec8019187bac855d1b0f212569efc93afbb5636bfd9b260a59b852585523e6f6ec28d1f872fdfc1926e9c24886b6270899cfaf75b",
          "sha256": "d8519934f1f15219a2bc9441028681ea039163d4a1d15e310f9901cb017e02cd",
          "sha1": "49bec4d4ba26fe69b9633866b2aa82d47fe61f15",
          "md5": "319a843cc98ff6e91c55d017fe3753a4"
        }
      ]
    }
  ]
}
