{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.1-SNAPSHOT.jar",
          "url": "http-api-1.0.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "7885d115c5ec313d4653940e09c0843b70cb32d7adeb429ffee3e33be09ea0c630cd9fcaebd073898e1d9abd23f80d674cdff9c2dcf625c6115848173eed5796",
          "sha256": "5f949270676c76536d7e3db2edd5464e7d619283da80b85252d2d7b1bb315066",
          "sha1": "937850e965fbb8c0659f6f70017bbb57dc5e6a70",
          "md5": "18c678bfb515cc33631c6571904b817b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.1-SNAPSHOT.jar",
          "url": "http-api-1.0.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "7885d115c5ec313d4653940e09c0843b70cb32d7adeb429ffee3e33be09ea0c630cd9fcaebd073898e1d9abd23f80d674cdff9c2dcf625c6115848173eed5796",
          "sha256": "5f949270676c76536d7e3db2edd5464e7d619283da80b85252d2d7b1bb315066",
          "sha1": "937850e965fbb8c0659f6f70017bbb57dc5e6a70",
          "md5": "18c678bfb515cc33631c6571904b817b"
        }
      ]
    }
  ]
}
