{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.1-SNAPSHOT.jar",
          "url": "http-api-1.0.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "b78f82c33ec7996c284ec68dcd202c1ce04dfccc634606e7afe05e1d88f2cac01c02ebbf710f00c4b5417b7df1cb734b122eb849fff2dc88b4fd0069ca42bd6f",
          "sha256": "5ddc7040f49ca688561b5d2887b2e0c7a023121f307788ca4001f7e3b5551f21",
          "sha1": "4bb429886c4a1854a4992a854fd104b81b999404",
          "md5": "46fccd27bc96b67bec557019eb7bdaf7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.1-SNAPSHOT.jar",
          "url": "http-api-1.0.1-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "b78f82c33ec7996c284ec68dcd202c1ce04dfccc634606e7afe05e1d88f2cac01c02ebbf710f00c4b5417b7df1cb734b122eb849fff2dc88b4fd0069ca42bd6f",
          "sha256": "5ddc7040f49ca688561b5d2887b2e0c7a023121f307788ca4001f7e3b5551f21",
          "sha1": "4bb429886c4a1854a4992a854fd104b81b999404",
          "md5": "46fccd27bc96b67bec557019eb7bdaf7"
        }
      ]
    }
  ]
}
