{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "7af18ffaae1feb0fc5d48c11119c59157de3255756d2c2deba1a549f1e271370e5b4d464fa953ca1f498e852e1b8231962e46537214bffd184ada34b1efd627d",
          "sha256": "ef55242cafef92e141aca4ef36e8a23b5fe873b84615bb15fd8c053b6b25c5fb",
          "sha1": "c9db819d54f7b50540fa6d6cdc5d8208aecf77bf",
          "md5": "cb7b2d1b0396dbb4381c862c13614753"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "7af18ffaae1feb0fc5d48c11119c59157de3255756d2c2deba1a549f1e271370e5b4d464fa953ca1f498e852e1b8231962e46537214bffd184ada34b1efd627d",
          "sha256": "ef55242cafef92e141aca4ef36e8a23b5fe873b84615bb15fd8c053b6b25c5fb",
          "sha1": "c9db819d54f7b50540fa6d6cdc5d8208aecf77bf",
          "md5": "cb7b2d1b0396dbb4381c862c13614753"
        }
      ]
    }
  ]
}
