{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "4c6ccbf3efe1e1c45fa6eaee05a22667d18098531bddcaa2658775680c8f2820d9b2cc4fa47740d13710b36edf183e24c97647813a616d3891931c332c77ce08",
          "sha256": "ab580f242d22db236bca8dcd91d98ce21f87592058f0debd5911c5dd513631eb",
          "sha1": "8188ad90d6ad23741e76a8e895bb8812043b7af4",
          "md5": "ee752c4c35a2a9e9b0c9ba4dd8d5de58"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "4c6ccbf3efe1e1c45fa6eaee05a22667d18098531bddcaa2658775680c8f2820d9b2cc4fa47740d13710b36edf183e24c97647813a616d3891931c332c77ce08",
          "sha256": "ab580f242d22db236bca8dcd91d98ce21f87592058f0debd5911c5dd513631eb",
          "sha1": "8188ad90d6ad23741e76a8e895bb8812043b7af4",
          "md5": "ee752c4c35a2a9e9b0c9ba4dd8d5de58"
        }
      ]
    }
  ]
}
