{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "6a3447b76685d7dc593bda5656740e28f5c2a4455f5575ddceb584ea55ee674e2eb4aebc963e446ef5e0d77d08124143e1adf72144e6fb63bf8cbeedf4bba86b",
          "sha256": "5ea014e5d1a0d99605f3f9ba8a77d2c3b06d30fab9b00ece851296adf3d666bf",
          "sha1": "a3c1e472c76eb7fcd6eeead45e54955687bca603",
          "md5": "4420a4947384e40da16bca504a470c9f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "6a3447b76685d7dc593bda5656740e28f5c2a4455f5575ddceb584ea55ee674e2eb4aebc963e446ef5e0d77d08124143e1adf72144e6fb63bf8cbeedf4bba86b",
          "sha256": "5ea014e5d1a0d99605f3f9ba8a77d2c3b06d30fab9b00ece851296adf3d666bf",
          "sha1": "a3c1e472c76eb7fcd6eeead45e54955687bca603",
          "md5": "4420a4947384e40da16bca504a470c9f"
        }
      ]
    }
  ]
}
