{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "72ff0b47191dc09c3e2b3b6203ac133c98dbf122139da502686f794255cbb835102a6de97c7eda9b4537683291614832a8e3cf4589c0f34a086646866994a368",
          "sha256": "18d2c19604f980e27cdaf211bccf8a9ae39d89405b603f8ca31d03aa027859da",
          "sha1": "c39c96a5e130ba739f15ceaed08035a789b7cd44",
          "md5": "70bac681088e1d185b63838728998309"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "72ff0b47191dc09c3e2b3b6203ac133c98dbf122139da502686f794255cbb835102a6de97c7eda9b4537683291614832a8e3cf4589c0f34a086646866994a368",
          "sha256": "18d2c19604f980e27cdaf211bccf8a9ae39d89405b603f8ca31d03aa027859da",
          "sha1": "c39c96a5e130ba739f15ceaed08035a789b7cd44",
          "md5": "70bac681088e1d185b63838728998309"
        }
      ]
    }
  ]
}
