{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "7b48a8c64a6467e5dc10c5d623ccea75881c70447af5492a0d24fbf671ec875a3356466c572082f6a26c64f22790cc867b6f0129145f6c63ec28cd6c219358bd",
          "sha256": "a82785aa062859ea6a60e38adbe983ba93668113f59565175b05abcda25ee850",
          "sha1": "2cc68431379adb531ab464a958cc1f133c1690c6",
          "md5": "f40cfba2ac2820e2b9abdd36eb9dbf07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "7b48a8c64a6467e5dc10c5d623ccea75881c70447af5492a0d24fbf671ec875a3356466c572082f6a26c64f22790cc867b6f0129145f6c63ec28cd6c219358bd",
          "sha256": "a82785aa062859ea6a60e38adbe983ba93668113f59565175b05abcda25ee850",
          "sha1": "2cc68431379adb531ab464a958cc1f133c1690c6",
          "md5": "f40cfba2ac2820e2b9abdd36eb9dbf07"
        }
      ]
    }
  ]
}
