{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "ddb3d6040f0f1ea2e3daba79b7c110110e8585ebcca8d1cd79af7d06b330ad03aeaf53aac7c2a6677f42cc7bb84c40150ef08ffb52d6326a8b49c0752c949583",
          "sha256": "ac88ee928ee42d5613c7c5fbf873a5937057dfed9315765fd806199b5014b026",
          "sha1": "e78ce7fd4ea34e338d3defcbc3e8fe5ea425a020",
          "md5": "d8e93c3753b03430e77165b02a7af3e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "ddb3d6040f0f1ea2e3daba79b7c110110e8585ebcca8d1cd79af7d06b330ad03aeaf53aac7c2a6677f42cc7bb84c40150ef08ffb52d6326a8b49c0752c949583",
          "sha256": "ac88ee928ee42d5613c7c5fbf873a5937057dfed9315765fd806199b5014b026",
          "sha1": "e78ce7fd4ea34e338d3defcbc3e8fe5ea425a020",
          "md5": "d8e93c3753b03430e77165b02a7af3e2"
        }
      ]
    }
  ]
}
