{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "ebde239f8826cc43ae0e36c02b1a8498849d10a9e7680b8a1c9306966c44a776889e4f1fafcb5c30ccd0b98db1d73f2ecffc044438ad19a22fefc539134c2f5c",
          "sha256": "2b8bfe99b6afd7cb1f694977bc1f0c9fcf35cd171503bac39314302e423912f0",
          "sha1": "15088ff3a78bd81dc751d54edd607483d7c164fe",
          "md5": "ff3340d11a4dfb30cae2fcb7a12f4c75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "ebde239f8826cc43ae0e36c02b1a8498849d10a9e7680b8a1c9306966c44a776889e4f1fafcb5c30ccd0b98db1d73f2ecffc044438ad19a22fefc539134c2f5c",
          "sha256": "2b8bfe99b6afd7cb1f694977bc1f0c9fcf35cd171503bac39314302e423912f0",
          "sha1": "15088ff3a78bd81dc751d54edd607483d7c164fe",
          "md5": "ff3340d11a4dfb30cae2fcb7a12f4c75"
        }
      ]
    }
  ]
}
