{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "d850fb040c2786291b2d2cc4e3561bb269ce5697fac0b44e313a1e835148ca9c161614fa9b008196cb34ee1dc2e501a15ff5c31642b8751a27e36797e0c99b4b",
          "sha256": "fe43600f3ce7f10ecf5b35ac9b18798dc1714ebdfb76bd1a4288f7cbb7d308b1",
          "sha1": "ffaed535d825de60ae0710cde19dd9d31d678882",
          "md5": "c96922aaa505fa26d44b52f685c14f2a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "d850fb040c2786291b2d2cc4e3561bb269ce5697fac0b44e313a1e835148ca9c161614fa9b008196cb34ee1dc2e501a15ff5c31642b8751a27e36797e0c99b4b",
          "sha256": "fe43600f3ce7f10ecf5b35ac9b18798dc1714ebdfb76bd1a4288f7cbb7d308b1",
          "sha1": "ffaed535d825de60ae0710cde19dd9d31d678882",
          "md5": "c96922aaa505fa26d44b52f685c14f2a"
        }
      ]
    }
  ]
}
