{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "5eaf114520de8a7cd516dd8a55aabbfbc66b1569668427c0e48eafc9f0ec81bdae00a7f3bff7918f9367fbb0ed89f3ee3cb968acdbc5b23d06fb0e10e322821a",
          "sha256": "477e30ec182fa669bc0b32fd2b585ba921a736d9402ecc5fbb8dd69a81460fac",
          "sha1": "1c89c1f9fcef7968c31726da2e3f114edc4a3a14",
          "md5": "f859970972bc967d63947c2dd3bf42a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "5eaf114520de8a7cd516dd8a55aabbfbc66b1569668427c0e48eafc9f0ec81bdae00a7f3bff7918f9367fbb0ed89f3ee3cb968acdbc5b23d06fb0e10e322821a",
          "sha256": "477e30ec182fa669bc0b32fd2b585ba921a736d9402ecc5fbb8dd69a81460fac",
          "sha1": "1c89c1f9fcef7968c31726da2e3f114edc4a3a14",
          "md5": "f859970972bc967d63947c2dd3bf42a1"
        }
      ]
    }
  ]
}
