{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "cfda029404b98ea0c53d4b1775138e255d613aa92441deb89fb92464f042ae0154639a20607afb45d1ef14b08b3981b68541a8ea2f19dc17ab0370545f606a76",
          "sha256": "2dda47db0eca2e7ac3e5195552ff03f6b7e0a537f51e3dd79383e68bc78d504e",
          "sha1": "f762886ada514b83ba2a2c322482224bba9a0116",
          "md5": "c685cb295bc32878cdf5753ccb43d329"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "cfda029404b98ea0c53d4b1775138e255d613aa92441deb89fb92464f042ae0154639a20607afb45d1ef14b08b3981b68541a8ea2f19dc17ab0370545f606a76",
          "sha256": "2dda47db0eca2e7ac3e5195552ff03f6b7e0a537f51e3dd79383e68bc78d504e",
          "sha1": "f762886ada514b83ba2a2c322482224bba9a0116",
          "md5": "c685cb295bc32878cdf5753ccb43d329"
        }
      ]
    }
  ]
}
