{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "0797f14304f6cb7dfbf537064a48688e29bdca820d232418a941ef72c523080282ee57f84cd00520a4121e18cc9ffbbafdaef61f496cc7073d729e872d2de8b3",
          "sha256": "23f3b06525fc5d31e79fdedb5271994e82971badf44b8941978b484dd679c029",
          "sha1": "c6e5fbec72a921ea308c5447337cf25e9a22734f",
          "md5": "f2f12ab8d070301289615e2ad5b87032"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "0797f14304f6cb7dfbf537064a48688e29bdca820d232418a941ef72c523080282ee57f84cd00520a4121e18cc9ffbbafdaef61f496cc7073d729e872d2de8b3",
          "sha256": "23f3b06525fc5d31e79fdedb5271994e82971badf44b8941978b484dd679c029",
          "sha1": "c6e5fbec72a921ea308c5447337cf25e9a22734f",
          "md5": "f2f12ab8d070301289615e2ad5b87032"
        }
      ]
    }
  ]
}
