{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "830f614336bf1ef409d7ae36450a7ce73558f31bd22b8a8a5bbf2df94576bd584322f586d5e82b8a29792e1802a3c1bee9ef8576dc0f19465bd3131d8c8bb4c7",
          "sha256": "74961f55ac6e439574ae2dd301912de6f85e433dfa2839af0a860f44d84ec22b",
          "sha1": "ac6ea6c0f4a3849b44fbc31f8b04f7b447dce09e",
          "md5": "29462a51d16eb161ba42caa0baf8170c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "830f614336bf1ef409d7ae36450a7ce73558f31bd22b8a8a5bbf2df94576bd584322f586d5e82b8a29792e1802a3c1bee9ef8576dc0f19465bd3131d8c8bb4c7",
          "sha256": "74961f55ac6e439574ae2dd301912de6f85e433dfa2839af0a860f44d84ec22b",
          "sha1": "ac6ea6c0f4a3849b44fbc31f8b04f7b447dce09e",
          "md5": "29462a51d16eb161ba42caa0baf8170c"
        }
      ]
    }
  ]
}
