{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "8620b470971f30463b6139b3a6dd4b5bf96cd3d604fba28fcc7b3dd5f473921868645a36b47f478eca70a2ca0f1875946c5c2446dabb70a2417dae3726a4e04b",
          "sha256": "0e7ba2f62cc5da4a29b5db86e2156ef76a984add96a0c4586dc9c16d8d49aaf3",
          "sha1": "57c95f4033949d260b98f2ab20ab356b8dd94b3b",
          "md5": "68f01dafe10c6b47790cb99f05041368"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "8620b470971f30463b6139b3a6dd4b5bf96cd3d604fba28fcc7b3dd5f473921868645a36b47f478eca70a2ca0f1875946c5c2446dabb70a2417dae3726a4e04b",
          "sha256": "0e7ba2f62cc5da4a29b5db86e2156ef76a984add96a0c4586dc9c16d8d49aaf3",
          "sha1": "57c95f4033949d260b98f2ab20ab356b8dd94b3b",
          "md5": "68f01dafe10c6b47790cb99f05041368"
        }
      ]
    }
  ]
}
