{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "0ec26d46fe86d62f460db680f4f2416a5a23be4817b1a9ddc11cc97c2119af1f335c3957af74549be23b67e394f6cc01bdb04b9393b5f060c2dc3c9d16e2d7ea",
          "sha256": "5e11db464a9425b50c0cf8d5b2e0a18c75b2f0fcf1ee8bcd6e3729be0d59b0ba",
          "sha1": "5385d62a7e70994852b6ad90d03227a5f317135b",
          "md5": "f8ab2697ec182673f06b035514a6af97"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "0ec26d46fe86d62f460db680f4f2416a5a23be4817b1a9ddc11cc97c2119af1f335c3957af74549be23b67e394f6cc01bdb04b9393b5f060c2dc3c9d16e2d7ea",
          "sha256": "5e11db464a9425b50c0cf8d5b2e0a18c75b2f0fcf1ee8bcd6e3729be0d59b0ba",
          "sha1": "5385d62a7e70994852b6ad90d03227a5f317135b",
          "md5": "f8ab2697ec182673f06b035514a6af97"
        }
      ]
    }
  ]
}
