{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "1d7965bf54836bd0f34d4f35cb0ce4d64ed513e12b9aeb94fa817ca05ebefc2c7d458741710e73bee709c16ae8692a3009bc4b1a0190a00fee12acd5ccb996f5",
          "sha256": "748041f1ce3075577651f6dde4838a40d099b6e02d9e2828748adefc532192f2",
          "sha1": "fb38ac583a0fabcb094040f806ab8174431528cc",
          "md5": "af22392a065cb76f6ad7f7e721bbf7be"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "1d7965bf54836bd0f34d4f35cb0ce4d64ed513e12b9aeb94fa817ca05ebefc2c7d458741710e73bee709c16ae8692a3009bc4b1a0190a00fee12acd5ccb996f5",
          "sha256": "748041f1ce3075577651f6dde4838a40d099b6e02d9e2828748adefc532192f2",
          "sha1": "fb38ac583a0fabcb094040f806ab8174431528cc",
          "md5": "af22392a065cb76f6ad7f7e721bbf7be"
        }
      ]
    }
  ]
}
