{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.28.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "95ce44d4ba07b534be2c06ed3c5c75d0526e92308ac2216fcad7a9043bc1a55c3d5c67f045ec4cc9c8559a85ee8f0132648092dbf1ac193a65826d9577fe315d",
          "sha256": "0f4c9dd5faf87e05a110eac584589055d18150e19cda9c4703df32c0d3eaa00f",
          "sha1": "333b86fdf6cd27f43a86e63a893aefb5148097a3",
          "md5": "6f79f7d79f5f80a7a082838b695bff19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.28.0-SNAPSHOT.jar",
          "url": "http-api-4.28.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "95ce44d4ba07b534be2c06ed3c5c75d0526e92308ac2216fcad7a9043bc1a55c3d5c67f045ec4cc9c8559a85ee8f0132648092dbf1ac193a65826d9577fe315d",
          "sha256": "0f4c9dd5faf87e05a110eac584589055d18150e19cda9c4703df32c0d3eaa00f",
          "sha1": "333b86fdf6cd27f43a86e63a893aefb5148097a3",
          "md5": "6f79f7d79f5f80a7a082838b695bff19"
        }
      ]
    }
  ]
}
