{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.32.0-SNAPSHOT.jar",
          "url": "runescape-api-4.32.0-SNAPSHOT.jar",
          "size": 124788,
          "sha512": "387aba5d971613e3ebfad77c36d2fecc8178dba5e99ff5dbc9f73902d8478f7ddc5d0f822363b13db10e3828c586b8737b9d728e57770ce03ee2bcc3526a085f",
          "sha256": "c129f358e124a3940ef899d72f3320dd591fee84f1a56d395e5e59d6e7cd8503",
          "sha1": "51d5572b79f1792dcfbbbff7ec9bd25de467675f",
          "md5": "d4b7a0138a214b861ed6f90aed68c710"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.32.0-SNAPSHOT.jar",
          "url": "runescape-api-4.32.0-SNAPSHOT.jar",
          "size": 124788,
          "sha512": "387aba5d971613e3ebfad77c36d2fecc8178dba5e99ff5dbc9f73902d8478f7ddc5d0f822363b13db10e3828c586b8737b9d728e57770ce03ee2bcc3526a085f",
          "sha256": "c129f358e124a3940ef899d72f3320dd591fee84f1a56d395e5e59d6e7cd8503",
          "sha1": "51d5572b79f1792dcfbbbff7ec9bd25de467675f",
          "md5": "d4b7a0138a214b861ed6f90aed68c710"
        }
      ]
    }
  ]
}
