{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.32.0-SNAPSHOT.jar",
          "url": "runescape-api-4.32.0-SNAPSHOT.jar",
          "size": 125188,
          "sha512": "c96dfafea5ad2ac3ead9c6ccd5bbff5946dc912bf4027dc14fd2355cc8a0743007da11ed3909eb89f81a08ee68bb0f9c0aa183cb73184a4c05b7c2ddeb9f3756",
          "sha256": "82f6e238866d7cdcd7d2e479823df800f8d69016b5dad7f3b025102f627fb149",
          "sha1": "97ff2b3cf5f9c09f1cb6eb2c767186c129db38c3",
          "md5": "dd91912ed3ac1026e188ef6d6231b6cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.32.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.32.0-SNAPSHOT.jar",
          "url": "runescape-api-4.32.0-SNAPSHOT.jar",
          "size": 125188,
          "sha512": "c96dfafea5ad2ac3ead9c6ccd5bbff5946dc912bf4027dc14fd2355cc8a0743007da11ed3909eb89f81a08ee68bb0f9c0aa183cb73184a4c05b7c2ddeb9f3756",
          "sha256": "82f6e238866d7cdcd7d2e479823df800f8d69016b5dad7f3b025102f627fb149",
          "sha1": "97ff2b3cf5f9c09f1cb6eb2c767186c129db38c3",
          "md5": "dd91912ed3ac1026e188ef6d6231b6cf"
        }
      ]
    }
  ]
}
