{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.2-SNAPSHOT.jar",
          "url": "runelite-api-1.0.2-SNAPSHOT.jar",
          "size": 1378040,
          "sha512": "5b9270a3f2fc473b488ce70a833a1f8865a73d15f596a0c0565fda548eae62b9ee9772a62d186bb55655af9b825d04461f844ba508de5a4a8ef91df5d38907f9",
          "sha256": "3bc7f4ef4a2b4068bc92444bb061b2b94332cd9a704fbd6f61fb8f4fdbde0b85",
          "sha1": "411f8a218ce9225763df93a986349bc8ba82c5c4",
          "md5": "1c115d9ebc79b71387b5208901d67398"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.2-SNAPSHOT.jar",
          "url": "runelite-api-1.0.2-SNAPSHOT.jar",
          "size": 1378040,
          "sha512": "5b9270a3f2fc473b488ce70a833a1f8865a73d15f596a0c0565fda548eae62b9ee9772a62d186bb55655af9b825d04461f844ba508de5a4a8ef91df5d38907f9",
          "sha256": "3bc7f4ef4a2b4068bc92444bb061b2b94332cd9a704fbd6f61fb8f4fdbde0b85",
          "sha1": "411f8a218ce9225763df93a986349bc8ba82c5c4",
          "md5": "1c115d9ebc79b71387b5208901d67398"
        }
      ]
    }
  ]
}
