{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.8-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.8-SNAPSHOT.jar",
          "url": "runescape-api-1.0.8-SNAPSHOT.jar",
          "size": 127715,
          "sha512": "9c5a6eed7a1a1ae53f858255aa9f43ae41ff54c8c44e4c07cadc0b3ad8114e4f4b3739e1f1e744ec905ddbf005c5fe6284f1eaee5b285a5f2348891c085e37fd",
          "sha256": "9a4d113d20c14938a47724a9cda0ddfdcd1f9320df990843492da2c2adfdfd4a",
          "sha1": "8d6373ff7c1f8f9b572484b0f69ac87bb3180c45",
          "md5": "7f38159ad264bfadcfbec8217951d2b0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.8-SNAPSHOT"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.8-SNAPSHOT.jar",
          "url": "runescape-api-1.0.8-SNAPSHOT.jar",
          "size": 127715,
          "sha512": "9c5a6eed7a1a1ae53f858255aa9f43ae41ff54c8c44e4c07cadc0b3ad8114e4f4b3739e1f1e744ec905ddbf005c5fe6284f1eaee5b285a5f2348891c085e37fd",
          "sha256": "9a4d113d20c14938a47724a9cda0ddfdcd1f9320df990843492da2c2adfdfd4a",
          "sha1": "8d6373ff7c1f8f9b572484b0f69ac87bb3180c45",
          "md5": "7f38159ad264bfadcfbec8217951d2b0"
        }
      ]
    }
  ]
}
