{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.29.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.29.0-SNAPSHOT.jar",
          "url": "runescape-api-4.29.0-SNAPSHOT.jar",
          "size": 123041,
          "sha512": "fb06918852062e090ddd6f0a6cef52ee8c1ec7b8064b5ea0c7bb85a9b00ea877c7d79738031b7aff7166e1880d184f1d726b7f3d4d945bc9dbe47b928e089a72",
          "sha256": "c725cb255fafac83d4069247e1466a49227105e729e9a654d74a07344c0f2871",
          "sha1": "a692385a9359d69c26d97877500a1885ced304a5",
          "md5": "ea200841e3e20553305bf22550da1f05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.29.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.29.0-SNAPSHOT.jar",
          "url": "runescape-api-4.29.0-SNAPSHOT.jar",
          "size": 123041,
          "sha512": "fb06918852062e090ddd6f0a6cef52ee8c1ec7b8064b5ea0c7bb85a9b00ea877c7d79738031b7aff7166e1880d184f1d726b7f3d4d945bc9dbe47b928e089a72",
          "sha256": "c725cb255fafac83d4069247e1466a49227105e729e9a654d74a07344c0f2871",
          "sha1": "a692385a9359d69c26d97877500a1885ced304a5",
          "md5": "ea200841e3e20553305bf22550da1f05"
        }
      ]
    }
  ]
}
