{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs.rs",
    "module": "runescape-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.29.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.29.0-SNAPSHOT.jar",
          "url": "runescape-api-4.29.0-SNAPSHOT.jar",
          "size": 122849,
          "sha512": "611c5f3edd3003780676be2ed0a82211bca7ff28350e749766e45e2ba7876655a9db255ae454e63e2d904479b6dca072b218439e978f259da96002feef4fdef3",
          "sha256": "94dc8dfeef63896581e27fadaebc344cc52e1077969faf74c65eb5399b7c211e",
          "sha1": "f20dd913008afc521972319d2be215b6e137ebf8",
          "md5": "e03bd92ceef6a7ca2412148bd35a53e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.openosrs",
          "module": "runelite-api",
          "version": {
            "requires": "4.29.0-SNAPSHOT"
          }
        },
        {
          "group": "com.openosrs",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-4.29.0-SNAPSHOT.jar",
          "url": "runescape-api-4.29.0-SNAPSHOT.jar",
          "size": 122849,
          "sha512": "611c5f3edd3003780676be2ed0a82211bca7ff28350e749766e45e2ba7876655a9db255ae454e63e2d904479b6dca072b218439e978f259da96002feef4fdef3",
          "sha256": "94dc8dfeef63896581e27fadaebc344cc52e1077969faf74c65eb5399b7c211e",
          "sha1": "f20dd913008afc521972319d2be215b6e137ebf8",
          "md5": "e03bd92ceef6a7ca2412148bd35a53e7"
        }
      ]
    }
  ]
}
