{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85080,
          "sha512": "0a3cd15c84c5df1a6240295ff3d2157e3343421d9a4eabdc58c9369599aa2b1ec72d1e4a006e7500e08d817c2ddc29edd9f75a996b883d6a78ab4dd033675967",
          "sha256": "a850eb39656926f280601243316f7f52e69d99be8e070f9dde6955db7d651ccd",
          "sha1": "8c6c5a92e0ab56a7002c588a3cbe37aef54db763",
          "md5": "26e52ecd8055b7cec4a91198b17a1514"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85080,
          "sha512": "0a3cd15c84c5df1a6240295ff3d2157e3343421d9a4eabdc58c9369599aa2b1ec72d1e4a006e7500e08d817c2ddc29edd9f75a996b883d6a78ab4dd033675967",
          "sha256": "a850eb39656926f280601243316f7f52e69d99be8e070f9dde6955db7d651ccd",
          "sha1": "8c6c5a92e0ab56a7002c588a3cbe37aef54db763",
          "md5": "26e52ecd8055b7cec4a91198b17a1514"
        }
      ]
    }
  ]
}
