{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85080,
          "sha512": "55a4c2a06b6208b93b5aba7d1578fa13057aaff7ca85d3114389cfd4cb85c18548dce102cecd8e856f238458b982da891e6b1f276bfe410329921261a63b36e3",
          "sha256": "b0b2b51cdf34e6c6dc328ba2a37a204327731e0bd17c148b6ab5c4e18801085f",
          "sha1": "3129e09cda2ba0e2a027fbe84fa72471e4b39ea0",
          "md5": "f050a189c989fc3ec60e80a3bb8fb866"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85080,
          "sha512": "55a4c2a06b6208b93b5aba7d1578fa13057aaff7ca85d3114389cfd4cb85c18548dce102cecd8e856f238458b982da891e6b1f276bfe410329921261a63b36e3",
          "sha256": "b0b2b51cdf34e6c6dc328ba2a37a204327731e0bd17c148b6ab5c4e18801085f",
          "sha1": "3129e09cda2ba0e2a027fbe84fa72471e4b39ea0",
          "md5": "f050a189c989fc3ec60e80a3bb8fb866"
        }
      ]
    }
  ]
}
