{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85081,
          "sha512": "c4d1f758764e90576719d64269a4d3239cb34910ca7e7f619f895b0d5c9244f01cfa9bd3685fd8e3cf5bef5ed8ec8edd513f81abae2755ffe49b01437b6db13e",
          "sha256": "2636769c53aa184273e158cc3bf5dea705a4f261f939b87a9b8c8bcacdb7503e",
          "sha1": "3291d724e55a4eebe50f0007bf5fa05a7c45214d",
          "md5": "97ae761523385a89ea3f176a890a07f4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85081,
          "sha512": "c4d1f758764e90576719d64269a4d3239cb34910ca7e7f619f895b0d5c9244f01cfa9bd3685fd8e3cf5bef5ed8ec8edd513f81abae2755ffe49b01437b6db13e",
          "sha256": "2636769c53aa184273e158cc3bf5dea705a4f261f939b87a9b8c8bcacdb7503e",
          "sha1": "3291d724e55a4eebe50f0007bf5fa05a7c45214d",
          "md5": "97ae761523385a89ea3f176a890a07f4"
        }
      ]
    }
  ]
}
