{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85080,
          "sha512": "9cfae6f6f2ad7d0014adc902f590f249bdc68d14181c3f887433e9ee3aa4f19e166cd60eae4cb13651e3ecbdbaaebf5d8fabb57de889e702b627e910177bf5d4",
          "sha256": "7ac7d0361ed8bd146d1d244b94e0f93c72f8dc0b3dc5f8dee0804691ceb62c2a",
          "sha1": "36867644bfbbc4a503eff337ad938cc98cce565d",
          "md5": "2d918d6c59f5e0a1e0ba46f79baedbd1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85080,
          "sha512": "9cfae6f6f2ad7d0014adc902f590f249bdc68d14181c3f887433e9ee3aa4f19e166cd60eae4cb13651e3ecbdbaaebf5d8fabb57de889e702b627e910177bf5d4",
          "sha256": "7ac7d0361ed8bd146d1d244b94e0f93c72f8dc0b3dc5f8dee0804691ceb62c2a",
          "sha1": "36867644bfbbc4a503eff337ad938cc98cce565d",
          "md5": "2d918d6c59f5e0a1e0ba46f79baedbd1"
        }
      ]
    }
  ]
}
