{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85081,
          "sha512": "132d7930b19d4f90a47eabb3d3080a42be902372738927a46d501377212914711d8a994f897bb49461ac33c1e8b4ad5ce52c91b0f272cc7609bc1eafdd18ffe3",
          "sha256": "ef5b21f3982ee243ca7941c468080b2ac152568b814a46eeb2f1d3ba67654398",
          "sha1": "d66721eca82ea8e0597e78f8d625c9bb7401e61d",
          "md5": "9b6b611bf4afadfbc71d03deb41821aa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85081,
          "sha512": "132d7930b19d4f90a47eabb3d3080a42be902372738927a46d501377212914711d8a994f897bb49461ac33c1e8b4ad5ce52c91b0f272cc7609bc1eafdd18ffe3",
          "sha256": "ef5b21f3982ee243ca7941c468080b2ac152568b814a46eeb2f1d3ba67654398",
          "sha1": "d66721eca82ea8e0597e78f8d625c9bb7401e61d",
          "md5": "9b6b611bf4afadfbc71d03deb41821aa"
        }
      ]
    }
  ]
}
