{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85079,
          "sha512": "6f619687a040a63f847e4abbdc376d3daf18ba5bd7e318d32c67c1fed825bb2d5b8f606b73ee7c4ed7082ee427c8a6718d9f7f9cf2192daf7bca7b9e0308f897",
          "sha256": "09ac5bb6b74fa6dae6553ad3b6d81592c9e7a3b2d32772824908c5cc6d50d173",
          "sha1": "e50754b87400d6522f814967ab9a692801829f56",
          "md5": "135f0d6d7887b290109a2a706ae4ecb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85079,
          "sha512": "6f619687a040a63f847e4abbdc376d3daf18ba5bd7e318d32c67c1fed825bb2d5b8f606b73ee7c4ed7082ee427c8a6718d9f7f9cf2192daf7bca7b9e0308f897",
          "sha256": "09ac5bb6b74fa6dae6553ad3b6d81592c9e7a3b2d32772824908c5cc6d50d173",
          "sha1": "e50754b87400d6522f814967ab9a692801829f56",
          "md5": "135f0d6d7887b290109a2a706ae4ecb5"
        }
      ]
    }
  ]
}
