{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85865,
          "sha512": "6bcad11cd7378e51bd8a82b3e9da9cd3221b10fb2be1cef25e073839c5a2dc2b3ad7848712cb85858f1cba36fb8cba884ab79bd7b7c1e71a9bd043ded72d8527",
          "sha256": "4565ec74a37c54e4fdf6c58cd4874e3891e7f2b78929190439c453fd93f3ba39",
          "sha1": "ff25d05444b691c91d312509ee2b5fb1e5d2ff59",
          "md5": "ea04ff22ca67029d60b69f44fb934a0f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-SNAPSHOT.jar",
          "url": "http-api-1.0.3-SNAPSHOT.jar",
          "size": 85865,
          "sha512": "6bcad11cd7378e51bd8a82b3e9da9cd3221b10fb2be1cef25e073839c5a2dc2b3ad7848712cb85858f1cba36fb8cba884ab79bd7b7c1e71a9bd043ded72d8527",
          "sha256": "4565ec74a37c54e4fdf6c58cd4874e3891e7f2b78929190439c453fd93f3ba39",
          "sha1": "ff25d05444b691c91d312509ee2b5fb1e5d2ff59",
          "md5": "ea04ff22ca67029d60b69f44fb934a0f"
        }
      ]
    }
  ]
}
