{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.8-SNAPSHOT.jar",
          "url": "runelite-api-1.0.8-SNAPSHOT.jar",
          "size": 1378329,
          "sha512": "2024df44f855763f06842eb1d7671b90668151caab3dbdf3bbc7628d036637b268267f0afc86c0628a7a692b759f066880e685bd7898380af3b3710f3040d1eb",
          "sha256": "63010c19c17f39e0f7e87b0cf19455bacdc316ac0aa5d5f348b6a98fb31bb786",
          "sha1": "b088af8a393b6e95241603e716695a8c976f1e4d",
          "md5": "a4e7dad6b85b1354ffb3cbc3cb3ecbb1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.8-SNAPSHOT.jar",
          "url": "runelite-api-1.0.8-SNAPSHOT.jar",
          "size": 1378329,
          "sha512": "2024df44f855763f06842eb1d7671b90668151caab3dbdf3bbc7628d036637b268267f0afc86c0628a7a692b759f066880e685bd7898380af3b3710f3040d1eb",
          "sha256": "63010c19c17f39e0f7e87b0cf19455bacdc316ac0aa5d5f348b6a98fb31bb786",
          "sha1": "b088af8a393b6e95241603e716695a8c976f1e4d",
          "md5": "a4e7dad6b85b1354ffb3cbc3cb3ecbb1"
        }
      ]
    }
  ]
}
