{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.8-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.8-SNAPSHOT.jar",
          "url": "runelite-api-1.0.8-SNAPSHOT.jar",
          "size": 1378708,
          "sha512": "d58e4af5e4965885ca002e90e7291282e91151bcd842f24777096ee26a88ed9e586e0d9e6cd2dfaac13ef88b074978d0ac3694182f2839dd9dee3fe782a1314f",
          "sha256": "a29c9c6897a892db15b075f1c929334eb67e9acc3226e4611d71b7aeb63f575b",
          "sha1": "0b736c9b1bccb251cbdb8faa2ea283d5be0a4548",
          "md5": "f937ee9592383c19165598aceba901f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.8-SNAPSHOT.jar",
          "url": "runelite-api-1.0.8-SNAPSHOT.jar",
          "size": 1378708,
          "sha512": "d58e4af5e4965885ca002e90e7291282e91151bcd842f24777096ee26a88ed9e586e0d9e6cd2dfaac13ef88b074978d0ac3694182f2839dd9dee3fe782a1314f",
          "sha256": "a29c9c6897a892db15b075f1c929334eb67e9acc3226e4611d71b7aeb63f575b",
          "sha1": "0b736c9b1bccb251cbdb8faa2ea283d5be0a4548",
          "md5": "f937ee9592383c19165598aceba901f0"
        }
      ]
    }
  ]
}
