{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1353634,
          "sha512": "69cef28b015dc0a7100603f76215bc350d0f4d44bde0c9a081db91bb9830366fa472e66debf9267d91af0a678cc57c49b6ae3485b12fc0c7d4685d1621a4a0cf",
          "sha256": "ed1c7ef77a3a3042d0ae1a0fd08d24899da7151043c77aa2f15d25d15d0e060e",
          "sha1": "b36d5cb485440869a353d142ec8e8834ce5dc49c",
          "md5": "2dd2d80c192ed6ca597cbc793c88f8e0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1353634,
          "sha512": "69cef28b015dc0a7100603f76215bc350d0f4d44bde0c9a081db91bb9830366fa472e66debf9267d91af0a678cc57c49b6ae3485b12fc0c7d4685d1621a4a0cf",
          "sha256": "ed1c7ef77a3a3042d0ae1a0fd08d24899da7151043c77aa2f15d25d15d0e060e",
          "sha1": "b36d5cb485440869a353d142ec8e8834ce5dc49c",
          "md5": "2dd2d80c192ed6ca597cbc793c88f8e0"
        }
      ]
    }
  ]
}
