{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1351584,
          "sha512": "1ca051cf516fe81ad214b55f94b696e8392fc7d4ce62e705009f67ee5790ecf566706cd5df8bca6d13e343fad0d39d4081577e465fb6e9274e9faaa7f0469571",
          "sha256": "ccd59d74bddfd47955badea30786f865081ef694e9561ac50818f6074f6cae10",
          "sha1": "acd9585a52a1dd1256cbeb165c9298ac68eed30d",
          "md5": "44d446febfeef264a42036ae61e3f706"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1351584,
          "sha512": "1ca051cf516fe81ad214b55f94b696e8392fc7d4ce62e705009f67ee5790ecf566706cd5df8bca6d13e343fad0d39d4081577e465fb6e9274e9faaa7f0469571",
          "sha256": "ccd59d74bddfd47955badea30786f865081ef694e9561ac50818f6074f6cae10",
          "sha1": "acd9585a52a1dd1256cbeb165c9298ac68eed30d",
          "md5": "44d446febfeef264a42036ae61e3f706"
        }
      ]
    }
  ]
}
