{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1351854,
          "sha512": "f3bb6dcf6166ccf0ee08f8405b7dfae1af2637c1b0fa4334bf65ef127aed433135480c9ec823558b231567cd81041a26d82ce0800eed8960f7b946130fe11328",
          "sha256": "4e7a7935834ea46cb5b64ca4831de8e35af8e22c6dabc4d43901c17dba6ad71f",
          "sha1": "d486599b6307d6a7a16e549f7a45a1c3fc11004b",
          "md5": "500980abc104c4e268756ebdcf9c2238"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1351854,
          "sha512": "f3bb6dcf6166ccf0ee08f8405b7dfae1af2637c1b0fa4334bf65ef127aed433135480c9ec823558b231567cd81041a26d82ce0800eed8960f7b946130fe11328",
          "sha256": "4e7a7935834ea46cb5b64ca4831de8e35af8e22c6dabc4d43901c17dba6ad71f",
          "sha1": "d486599b6307d6a7a16e549f7a45a1c3fc11004b",
          "md5": "500980abc104c4e268756ebdcf9c2238"
        }
      ]
    }
  ]
}
