{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1355740,
          "sha512": "34dad2d6a62369a445f8a2a77404d757277fe4ec6717f682c950eb26e3e69185061b6177f5bbc77a68f77ed1d666be5cccd8aaefd974846e33b982fa5a9a375f",
          "sha256": "a60eee57078511c876a841bc28f583d35540285fe63ee81b1aa89241bac46f28",
          "sha1": "6d7b0b50e2dcde477c7078cd42c07577d9ba0b99",
          "md5": "7ad91efdbb1bd4f182a95b5fd645427b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1355740,
          "sha512": "34dad2d6a62369a445f8a2a77404d757277fe4ec6717f682c950eb26e3e69185061b6177f5bbc77a68f77ed1d666be5cccd8aaefd974846e33b982fa5a9a375f",
          "sha256": "a60eee57078511c876a841bc28f583d35540285fe63ee81b1aa89241bac46f28",
          "sha1": "6d7b0b50e2dcde477c7078cd42c07577d9ba0b99",
          "md5": "7ad91efdbb1bd4f182a95b5fd645427b"
        }
      ]
    }
  ]
}
