{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1351334,
          "sha512": "838855397020b87c3099e9fdbf8302b48d1dc4bbfec64a2e72a706e67716c21b7d2345c722eab5acff20efe7f2d3327e6e7f58caa2c36cad10efd7b068893bfe",
          "sha256": "fc881c1b3fa43e3d29318fd3cbf985fc20d5515536deac156195d001d2b483f6",
          "sha1": "6024bdce5a3f6046004dc159f456be20136cdd5f",
          "md5": "27142fe982da617832e89a1ee7a12058"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.2-SNAPSHOT.jar",
          "url": "runelite-api-4.25.2-SNAPSHOT.jar",
          "size": 1351334,
          "sha512": "838855397020b87c3099e9fdbf8302b48d1dc4bbfec64a2e72a706e67716c21b7d2345c722eab5acff20efe7f2d3327e6e7f58caa2c36cad10efd7b068893bfe",
          "sha256": "fc881c1b3fa43e3d29318fd3cbf985fc20d5515536deac156195d001d2b483f6",
          "sha1": "6024bdce5a3f6046004dc159f456be20136cdd5f",
          "md5": "27142fe982da617832e89a1ee7a12058"
        }
      ]
    }
  ]
}
