{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "injector-plugin",
    "version": "2.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.4.jar",
          "url": "injector-plugin-2.0.4.jar",
          "size": 119219,
          "sha512": "56b97d1ed5eaf5fb2bdcbdf7d5c06439aaeea9502df134664cdb21cd0e4cfa7bd6ecbba5f1c95987b43fb8fa68f00fa64bfc45f21b7d12bd9c088e83bf608934",
          "sha256": "012d17b10269d7573bf8614941716baa8fa38a7513a8fa83ff9c502a1ff5b05e",
          "sha1": "f40ac7243c42763230d5afedfac06a12aea6f2b5",
          "md5": "247bd90d3ade9ab4e9be3eb2af73fb13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.0"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "com.openosrs",
          "module": "deobfuscator",
          "version": {
            "requires": "4.31.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "injector-plugin-2.0.4.jar",
          "url": "injector-plugin-2.0.4.jar",
          "size": 119219,
          "sha512": "56b97d1ed5eaf5fb2bdcbdf7d5c06439aaeea9502df134664cdb21cd0e4cfa7bd6ecbba5f1c95987b43fb8fa68f00fa64bfc45f21b7d12bd9c088e83bf608934",
          "sha256": "012d17b10269d7573bf8614941716baa8fa38a7513a8fa83ff9c502a1ff5b05e",
          "sha1": "f40ac7243c42763230d5afedfac06a12aea6f2b5",
          "md5": "247bd90d3ade9ab4e9be3eb2af73fb13"
        }
      ]
    }
  ]
}
