{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88795,
          "sha512": "a73356cec8bec96a4fc3e9e2e50ff2fbf4298017cb0aeef914c113a340bad1d9f29eef04ed60079c8b2e866d6b3c3e8f29c7aa5310a57103d8bbafba18c47c33",
          "sha256": "dafefcb505d1317d8732f88a6bfbf420d74026285441334c539f09e077b39c32",
          "sha1": "5a7788606f56cdeb0c354fff986adfa15cdf5c61",
          "md5": "59f3acee7da232730df3c9a3c69cf468"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88795,
          "sha512": "a73356cec8bec96a4fc3e9e2e50ff2fbf4298017cb0aeef914c113a340bad1d9f29eef04ed60079c8b2e866d6b3c3e8f29c7aa5310a57103d8bbafba18c47c33",
          "sha256": "dafefcb505d1317d8732f88a6bfbf420d74026285441334c539f09e077b39c32",
          "sha1": "5a7788606f56cdeb0c354fff986adfa15cdf5c61",
          "md5": "59f3acee7da232730df3c9a3c69cf468"
        }
      ]
    }
  ]
}
