{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88795,
          "sha512": "7f888926288742f33382d6d26550525a574d568da373321ffdcfbcbf87b366175f7af2659f1de1d338f4dfcf676a8aa36ca5effd1b37d563d299b3dcaf7ca4be",
          "sha256": "f1d0f68994043e722db14ea88749e9b8490ea7cae25fe5d30a105dcff982c949",
          "sha1": "7631839b5d53e45d46729adc69ddba460c31d2ba",
          "md5": "a7247889b400d842129aa5ef0b364e89"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88795,
          "sha512": "7f888926288742f33382d6d26550525a574d568da373321ffdcfbcbf87b366175f7af2659f1de1d338f4dfcf676a8aa36ca5effd1b37d563d299b3dcaf7ca4be",
          "sha256": "f1d0f68994043e722db14ea88749e9b8490ea7cae25fe5d30a105dcff982c949",
          "sha1": "7631839b5d53e45d46729adc69ddba460c31d2ba",
          "md5": "a7247889b400d842129aa5ef0b364e89"
        }
      ]
    }
  ]
}
