{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.30.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88795,
          "sha512": "8cc018274914df908188a473f1a52e77c3c47c6067eed0e559bed86ecd3fb9d627e37fcdc354146faa50ceba13d937c29d8e70cd34d7e461489db5388f0ad961",
          "sha256": "98c070f5616d61bab5bfee80535f3e3061315e3444aaee1c93915c47453db9e4",
          "sha1": "218d7ea56ac6a55fd7d0cd7f2503ad2a56b3e095",
          "md5": "0928c9d66a4db0062cd38be7a6efd9e6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.30.0.jar",
          "url": "http-api-4.30.0.jar",
          "size": 88795,
          "sha512": "8cc018274914df908188a473f1a52e77c3c47c6067eed0e559bed86ecd3fb9d627e37fcdc354146faa50ceba13d937c29d8e70cd34d7e461489db5388f0ad961",
          "sha256": "98c070f5616d61bab5bfee80535f3e3061315e3444aaee1c93915c47453db9e4",
          "sha1": "218d7ea56ac6a55fd7d0cd7f2503ad2a56b3e095",
          "md5": "0928c9d66a4db0062cd38be7a6efd9e6"
        }
      ]
    }
  ]
}
