{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.6.jar",
          "url": "http-api-1.0.6.jar",
          "size": 91329,
          "sha512": "ddca090b3494adebe7989d42fc9a15640e605d040f3b46fa624ad3d443f26e0162006f716ced540cced8909919c3c7c961b34859bde5c8818e1395057183df97",
          "sha256": "809b22fa98691fc826a03ba8ebb4d8eeab46457ce943f9282a729b705811a440",
          "sha1": "e00ffbf9a3a91a726bf8ea336e2be56bec1aaa49",
          "md5": "a346038f3c7da456e08d161faf375a0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.6.jar",
          "url": "http-api-1.0.6.jar",
          "size": 91329,
          "sha512": "ddca090b3494adebe7989d42fc9a15640e605d040f3b46fa624ad3d443f26e0162006f716ced540cced8909919c3c7c961b34859bde5c8818e1395057183df97",
          "sha256": "809b22fa98691fc826a03ba8ebb4d8eeab46457ce943f9282a729b705811a440",
          "sha1": "e00ffbf9a3a91a726bf8ea336e2be56bec1aaa49",
          "md5": "a346038f3c7da456e08d161faf375a0b"
        }
      ]
    }
  ]
}
