{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1351768,
          "sha512": "51039ab1d86907af25ab470c6dad22940c6889db0f2329583d6b4c4d1950b785a4baaeac4b3adf87cc2d7ff6c327b51d57070b801b9058a7bc5f37f5766ddbdd",
          "sha256": "8a15fbc202a9a1856689adbaf52693c8eab725b0e8177cf33445937182e9b171",
          "sha1": "8c6a11e1f334370320cf471caf0aab4ad4f2c177",
          "md5": "e5b984b67498b1b9e3c734d15e415807"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1351768,
          "sha512": "51039ab1d86907af25ab470c6dad22940c6889db0f2329583d6b4c4d1950b785a4baaeac4b3adf87cc2d7ff6c327b51d57070b801b9058a7bc5f37f5766ddbdd",
          "sha256": "8a15fbc202a9a1856689adbaf52693c8eab725b0e8177cf33445937182e9b171",
          "sha1": "8c6a11e1f334370320cf471caf0aab4ad4f2c177",
          "md5": "e5b984b67498b1b9e3c734d15e415807"
        }
      ]
    }
  ]
}
