{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.25.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1347669,
          "sha512": "d9e08549387715070508af3845ad7c48590355086c53a35a1633ee3d14c026c7b27d60a19535c56835442dc4a2815ec0260e1262e8d5e4a1bbe0cdd52c64b9e1",
          "sha256": "77617702640d7d84c051144c1403250cf327a598bd6a2401a578670c9e13fefb",
          "sha1": "2261d26acab208988929c2143399aa5b1b4ff039",
          "md5": "58c99d34f72695850b248c4a3783fe59"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.25.1.jar",
          "url": "runelite-api-4.25.1.jar",
          "size": 1347669,
          "sha512": "d9e08549387715070508af3845ad7c48590355086c53a35a1633ee3d14c026c7b27d60a19535c56835442dc4a2815ec0260e1262e8d5e4a1bbe0cdd52c64b9e1",
          "sha256": "77617702640d7d84c051144c1403250cf327a598bd6a2401a578670c9e13fefb",
          "sha1": "2261d26acab208988929c2143399aa5b1b4ff039",
          "md5": "58c99d34f72695850b248c4a3783fe59"
        }
      ]
    }
  ]
}
