{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "script-assembler-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.0.jar",
          "url": "script-assembler-plugin-1.0.0.jar",
          "size": 7061,
          "sha512": "9d1c7142252f85c3ee86371e97a8ac88ef65b757fda9eae18dee247252b45dc1605a82eb212f26ffa9870f709925d5231a159deeae04fb9d117ff46897483278",
          "sha256": "a544f8cb5ce900d94ed072bfb0259249bc709c39d0fac529875cccb4772dd3e7",
          "sha1": "7862ec312326de0db866ba501341254364453662",
          "md5": "6c34f82f12a41aad7930de6b47135533"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.8-1"
          }
        },
        {
          "group": "com.openosrs",
          "module": "cache",
          "version": {
            "requires": "4.31.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "script-assembler-plugin-1.0.0.jar",
          "url": "script-assembler-plugin-1.0.0.jar",
          "size": 7061,
          "sha512": "9d1c7142252f85c3ee86371e97a8ac88ef65b757fda9eae18dee247252b45dc1605a82eb212f26ffa9870f709925d5231a159deeae04fb9d117ff46897483278",
          "sha256": "a544f8cb5ce900d94ed072bfb0259249bc709c39d0fac529875cccb4772dd3e7",
          "sha1": "7862ec312326de0db866ba501341254364453662",
          "md5": "6c34f82f12a41aad7930de6b47135533"
        }
      ]
    }
  ]
}
