{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "runelite-api",
    "version": "1.0.4-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-1.0.4-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.4-EXPERIMENTAL.jar",
          "size": 1377509,
          "sha512": "8846b0b7b31d9e32dc3b6db7c6b40c59e22769d89bc667ecc9fdf166a59f370217e2ee4f7ac5c6903d0049a830c64812b7eb55b9275f55ac7263a0dd2cafb26d",
          "sha256": "566f1c7b4967b5620d1cadae3dda36a5d20e5f8ccea2ca2c1b5de3b1c2314429",
          "sha1": "0e58782eb94b7a8183e9172960efac90ed0dd84f",
          "md5": "c0336f861f8c570bb9f26b8a56141b26"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-1.0.4-EXPERIMENTAL.jar",
          "url": "runelite-api-1.0.4-EXPERIMENTAL.jar",
          "size": 1377509,
          "sha512": "8846b0b7b31d9e32dc3b6db7c6b40c59e22769d89bc667ecc9fdf166a59f370217e2ee4f7ac5c6903d0049a830c64812b7eb55b9275f55ac7263a0dd2cafb26d",
          "sha256": "566f1c7b4967b5620d1cadae3dda36a5d20e5f8ccea2ca2c1b5de3b1c2314429",
          "sha1": "0e58782eb94b7a8183e9172960efac90ed0dd84f",
          "md5": "c0336f861f8c570bb9f26b8a56141b26"
        }
      ]
    }
  ]
}
