{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite.rs",
    "module": "runescape-api",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.2.jar",
          "url": "runescape-api-1.0.2.jar",
          "size": 126897,
          "sha512": "94e7ba1a95bcfb4cc7f69184ae63e26c8bfadfbd964e803e5414a4e4b46f922d64e4f2798d11038abd0a16c621e850bb4d512444935d44eeccc5cbcc35258091",
          "sha256": "1ec7dfd3e3851a372ab559de902e89419d9f2d7f5d09a50136d98ee36afdcd07",
          "sha1": "8f8c3c18ea27c77161c1b02265f6c6419fd318d8",
          "md5": "158e3a379f771e3a58f6fe17f300bd1f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.unethicalite",
          "module": "runelite-api",
          "version": {
            "requires": "1.0.2"
          }
        },
        {
          "group": "net.unethicalite",
          "module": "injection-annotations",
          "version": {
            "requires": "1.1"
          }
        }
      ],
      "files": [
        {
          "name": "runescape-api-1.0.2.jar",
          "url": "runescape-api-1.0.2.jar",
          "size": 126897,
          "sha512": "94e7ba1a95bcfb4cc7f69184ae63e26c8bfadfbd964e803e5414a4e4b46f922d64e4f2798d11038abd0a16c621e850bb4d512444935d44eeccc5cbcc35258091",
          "sha256": "1ec7dfd3e3851a372ab559de902e89419d9f2d7f5d09a50136d98ee36afdcd07",
          "sha1": "8f8c3c18ea27c77161c1b02265f6c6419fd318d8",
          "md5": "158e3a379f771e3a58f6fe17f300bd1f"
        }
      ]
    }
  ]
}
