{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "fb1808ee8889a9339f7c0f52d2af211aa6c5f30eac4464deace80eab50bd9ef0ab981a4abbe29989a19f11ba3e1cf97669ee38f4784cac3d52aa04b22a187210",
          "sha256": "aa9e25cbf58161e61f6fd364ac020d4cee03538fcd6c1b3f058fbde7f1280cdc",
          "sha1": "fa8000906c7b41514e03e5ba477b80bb59b3efd4",
          "md5": "fe21f7fda5b6cc28aa1027282f8d88d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88794,
          "sha512": "fb1808ee8889a9339f7c0f52d2af211aa6c5f30eac4464deace80eab50bd9ef0ab981a4abbe29989a19f11ba3e1cf97669ee38f4784cac3d52aa04b22a187210",
          "sha256": "aa9e25cbf58161e61f6fd364ac020d4cee03538fcd6c1b3f058fbde7f1280cdc",
          "sha1": "fa8000906c7b41514e03e5ba477b80bb59b3efd4",
          "md5": "fe21f7fda5b6cc28aa1027282f8d88d2"
        }
      ]
    }
  ]
}
