{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "e8930e14a8931d75bcd71b3f31b483b0f34382852d199ea9832eae2569370ca7357d5e4810f7bd809ee4551bfcd3cbf66234ca1bccf1f349eaa2b008a498daa9",
          "sha256": "c577fe9bf700b164f44c20fb3706efa3f02240b27eb5442d97d16adbce34549f",
          "sha1": "fd292954b2ceb3668e7995a37b425bcd92a7387e",
          "md5": "92cc9649390040781e22f6dd0753d35a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "e8930e14a8931d75bcd71b3f31b483b0f34382852d199ea9832eae2569370ca7357d5e4810f7bd809ee4551bfcd3cbf66234ca1bccf1f349eaa2b008a498daa9",
          "sha256": "c577fe9bf700b164f44c20fb3706efa3f02240b27eb5442d97d16adbce34549f",
          "sha1": "fd292954b2ceb3668e7995a37b425bcd92a7387e",
          "md5": "92cc9649390040781e22f6dd0753d35a"
        }
      ]
    }
  ]
}
