{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "d812e2f218b14043aef048d21f6b9be312f5665bb910d6a14949a17077397056105e2adf03997eeedadb016f9b7c71e5f9dd697f197e7b85d6f1053553dc69e1",
          "sha256": "7c74af0ba6ffa6763b1fb438fb3260f8558dd2ac985fb52c40fa5582e7a2c36a",
          "sha1": "899428527021705cbe9cd8c6fa203e485cbfbb27",
          "md5": "7ac07c5366db63399a7e4e8b3b0db84b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "d812e2f218b14043aef048d21f6b9be312f5665bb910d6a14949a17077397056105e2adf03997eeedadb016f9b7c71e5f9dd697f197e7b85d6f1053553dc69e1",
          "sha256": "7c74af0ba6ffa6763b1fb438fb3260f8558dd2ac985fb52c40fa5582e7a2c36a",
          "sha1": "899428527021705cbe9cd8c6fa203e485cbfbb27",
          "md5": "7ac07c5366db63399a7e4e8b3b0db84b"
        }
      ]
    }
  ]
}
