{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "e7486aaa86a2c9dfc187358ace7004d4e9822fffdacb4fcef50df817a139f425030101e18bffa194fd100148d66665be73489cba6cc86ac90a75bdebe5ee8d83",
          "sha256": "df183efe00abf4529b9aca24ccde4ddc1b938529c43caa8b6a1cb7b4fa00fd6b",
          "sha1": "4f16bf9c4df1152f2d0e5bb93b1d149d75162c53",
          "md5": "7c7693698d4522ffa414c9ee1ab0fd4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88795,
          "sha512": "e7486aaa86a2c9dfc187358ace7004d4e9822fffdacb4fcef50df817a139f425030101e18bffa194fd100148d66665be73489cba6cc86ac90a75bdebe5ee8d83",
          "sha256": "df183efe00abf4529b9aca24ccde4ddc1b938529c43caa8b6a1cb7b4fa00fd6b",
          "sha1": "4f16bf9c4df1152f2d0e5bb93b1d149d75162c53",
          "md5": "7c7693698d4522ffa414c9ee1ab0fd4b"
        }
      ]
    }
  ]
}
