{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "http-api",
    "version": "4.29.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "096c74280b81982ec2c3a4b71b685192e6718d274a2bb8c70eac8db1189b5702671bd89972b06bcb5575240641e02326dbaca881020ae1c233acde9ea7e9073c",
          "sha256": "a50096bfda328b606c70f618145abde90fd9b9a7350fa07f4ffbf65598bb6720",
          "sha1": "5f2f427df4afc53486664d38a5141159ce662972",
          "md5": "5bae7011a9cb76cd3157f58eea7cb551"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-4.29.0-SNAPSHOT.jar",
          "url": "http-api-4.29.0-SNAPSHOT.jar",
          "size": 88796,
          "sha512": "096c74280b81982ec2c3a4b71b685192e6718d274a2bb8c70eac8db1189b5702671bd89972b06bcb5575240641e02326dbaca881020ae1c233acde9ea7e9073c",
          "sha256": "a50096bfda328b606c70f618145abde90fd9b9a7350fa07f4ffbf65598bb6720",
          "sha1": "5f2f427df4afc53486664d38a5141159ce662972",
          "md5": "5bae7011a9cb76cd3157f58eea7cb551"
        }
      ]
    }
  ]
}
