{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.5.jar",
          "url": "http-api-1.0.5.jar",
          "size": 88474,
          "sha512": "9b7a48b36302553180693dfcfe6d38f3f791ec1472e5a801f09f0cb0359b7888972b1d9478fd688ad2c7afe5137f3046b4247b02ed4edb451d6fef7a600cc5b5",
          "sha256": "9b02cb6f97c08af6f85b8cec06be8e6f13e3c8761835d8a9582cffca2a5e1613",
          "sha1": "64fa6238f922745b699d8b43401769086fa92d2b",
          "md5": "9aba0e07bca97d877cf898414e4bfd18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.5.jar",
          "url": "http-api-1.0.5.jar",
          "size": 88474,
          "sha512": "9b7a48b36302553180693dfcfe6d38f3f791ec1472e5a801f09f0cb0359b7888972b1d9478fd688ad2c7afe5137f3046b4247b02ed4edb451d6fef7a600cc5b5",
          "sha256": "9b02cb6f97c08af6f85b8cec06be8e6f13e3c8761835d8a9582cffca2a5e1613",
          "sha1": "64fa6238f922745b699d8b43401769086fa92d2b",
          "md5": "9aba0e07bca97d877cf898414e4bfd18"
        }
      ]
    }
  ]
}
