{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-EXPERIMENTAL.jar",
          "url": "http-api-1.0.3-EXPERIMENTAL.jar",
          "size": 85080,
          "sha512": "2ffd99138ebe71a41c0b90523042c7440baa4032abc3c8d95b52fdf014c68ff048747ac61b3e3c593950ec37bcf6d877c5b075685933c7cf2d7a726e0a570835",
          "sha256": "a81ba4378572a63fb92526c573e83ef410eecba249fa21acc8c2d2c00d3bf37c",
          "sha1": "33111601265a53d23b06cb1620bd2e65e41320ef",
          "md5": "73e1d1bb110c63517e1bc805cff33fa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-EXPERIMENTAL.jar",
          "url": "http-api-1.0.3-EXPERIMENTAL.jar",
          "size": 85080,
          "sha512": "2ffd99138ebe71a41c0b90523042c7440baa4032abc3c8d95b52fdf014c68ff048747ac61b3e3c593950ec37bcf6d877c5b075685933c7cf2d7a726e0a570835",
          "sha256": "a81ba4378572a63fb92526c573e83ef410eecba249fa21acc8c2d2c00d3bf37c",
          "sha1": "33111601265a53d23b06cb1620bd2e65e41320ef",
          "md5": "73e1d1bb110c63517e1bc805cff33fa5"
        }
      ]
    }
  ]
}
