{
  "formatVersion": "1.1",
  "component": {
    "group": "net.unethicalite",
    "module": "http-api",
    "version": "1.0.3-EXPERIMENTAL",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "http-api-1.0.3-EXPERIMENTAL.jar",
          "url": "http-api-1.0.3-EXPERIMENTAL.jar",
          "size": 85080,
          "sha512": "3d275616558d5d5d091dae1191974852747ea8d8565ee7a165b610dc6d7ae5ba7006f41d4f1cb085f0b2e44fb80d8147e22d135ffdeb986a55941416f07cf2c3",
          "sha256": "31b43c7073f4029a87a237039f3005246581d5168bc0dd41d7c6b6518850f346",
          "sha1": "b7afbb0921bd3a88efc7423dc88f9abf7411bf6f",
          "md5": "73af74c8d9af019d22f8ddad7e3a5724"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.5"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.9.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-csv",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        }
      ],
      "files": [
        {
          "name": "http-api-1.0.3-EXPERIMENTAL.jar",
          "url": "http-api-1.0.3-EXPERIMENTAL.jar",
          "size": 85080,
          "sha512": "3d275616558d5d5d091dae1191974852747ea8d8565ee7a165b610dc6d7ae5ba7006f41d4f1cb085f0b2e44fb80d8147e22d135ffdeb986a55941416f07cf2c3",
          "sha256": "31b43c7073f4029a87a237039f3005246581d5168bc0dd41d7c6b6518850f346",
          "sha1": "b7afbb0921bd3a88efc7423dc88f9abf7411bf6f",
          "md5": "73af74c8d9af019d22f8ddad7e3a5724"
        }
      ]
    }
  ]
}
