{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1366226,
          "sha512": "ab9625a64845087bf4679395afe42faaaf01cb127d2ad6a133ba9a4e154559534fa8510c2a298a39b754e9ce0eef8c21b1dc39a318870f336327d13707518129",
          "sha256": "e27a835b1084050758f38ac759a782cfb0426c429b03c5dfa2b9a3ca80e25ac9",
          "sha1": "047a57c92d9d0b138fb70da36a36f31736ae70a2",
          "md5": "f11e690d2eb68e479c18682fa3ce09c5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1366226,
          "sha512": "ab9625a64845087bf4679395afe42faaaf01cb127d2ad6a133ba9a4e154559534fa8510c2a298a39b754e9ce0eef8c21b1dc39a318870f336327d13707518129",
          "sha256": "e27a835b1084050758f38ac759a782cfb0426c429b03c5dfa2b9a3ca80e25ac9",
          "sha1": "047a57c92d9d0b138fb70da36a36f31736ae70a2",
          "md5": "f11e690d2eb68e479c18682fa3ce09c5"
        }
      ]
    }
  ]
}
