{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1368794,
          "sha512": "d806f5cdbb5e729defb83203cc3a28ac2afdf78143480718e624c96217d877b7612aabb2e40edfec47847b896ac3bf6235b6da03b1083c98101a9fbe0d3cd89a",
          "sha256": "8e4bbd060c49f46a488a73112d393c24e7d6f65114e8e529e4287950a9680212",
          "sha1": "00d9764e3372d80704c8881c773a3e6680166763",
          "md5": "95b7ebb5fad80c7717cd145489fb5454"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1368794,
          "sha512": "d806f5cdbb5e729defb83203cc3a28ac2afdf78143480718e624c96217d877b7612aabb2e40edfec47847b896ac3bf6235b6da03b1083c98101a9fbe0d3cd89a",
          "sha256": "8e4bbd060c49f46a488a73112d393c24e7d6f65114e8e529e4287950a9680212",
          "sha1": "00d9764e3372d80704c8881c773a3e6680166763",
          "md5": "95b7ebb5fad80c7717cd145489fb5454"
        }
      ]
    }
  ]
}
