{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1373414,
          "sha512": "f6dfe1054b47c9b4c48520fe2572751ccef80952891b5af9fd019857f9472f1e5ba4f25b9746ae00efbe97c571e0a12d84e75f3bfff219dce2abbfc7044de4d1",
          "sha256": "6536fb7f6857673d02764eff977c514d8fbe2e910911a445b4897f43c6bcf583",
          "sha1": "b8e6d09ffc995d43f14ae5e051c350756eb4306f",
          "md5": "7a535dc65898efd59ae650779a88531d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1373414,
          "sha512": "f6dfe1054b47c9b4c48520fe2572751ccef80952891b5af9fd019857f9472f1e5ba4f25b9746ae00efbe97c571e0a12d84e75f3bfff219dce2abbfc7044de4d1",
          "sha256": "6536fb7f6857673d02764eff977c514d8fbe2e910911a445b4897f43c6bcf583",
          "sha1": "b8e6d09ffc995d43f14ae5e051c350756eb4306f",
          "md5": "7a535dc65898efd59ae650779a88531d"
        }
      ]
    }
  ]
}
