{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1369582,
          "sha512": "bb8083ab1ad93d42aed8e5b331972dc681b1e64f31b9861920b4bd8386c3ec91310493f18f2152d49d7250efbe33ca0ecf9567d6cc686a97e9391e2bdb4c69d2",
          "sha256": "c011f75add4144c78ca3a1c2144520ca10d366b3c5ce7ecaad293b91c9a1f514",
          "sha1": "01c520ec649501cae740fd4ea7ec3ddbe5421a53",
          "md5": "98cc2c663a54a65946a7595b56443334"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1369582,
          "sha512": "bb8083ab1ad93d42aed8e5b331972dc681b1e64f31b9861920b4bd8386c3ec91310493f18f2152d49d7250efbe33ca0ecf9567d6cc686a97e9391e2bdb4c69d2",
          "sha256": "c011f75add4144c78ca3a1c2144520ca10d366b3c5ce7ecaad293b91c9a1f514",
          "sha1": "01c520ec649501cae740fd4ea7ec3ddbe5421a53",
          "md5": "98cc2c663a54a65946a7595b56443334"
        }
      ]
    }
  ]
}
