{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1368795,
          "sha512": "4f41e833a3f117753b2aa9c1375a32602c6e12fb8999b2d840638a124bdad0bd086ef0ab6f17e38267c4d17934b036eaddbb98f16897e58fee15295d498a6f5f",
          "sha256": "4b23bf502ada550752277d94109438ac551a876e2eb137358cf01b0c2a2b5a73",
          "sha1": "2d249dd1fbf2d28e961322edd9efb1428998fa26",
          "md5": "31788b1e5d4605ad3a692ff071b974d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1368795,
          "sha512": "4f41e833a3f117753b2aa9c1375a32602c6e12fb8999b2d840638a124bdad0bd086ef0ab6f17e38267c4d17934b036eaddbb98f16897e58fee15295d498a6f5f",
          "sha256": "4b23bf502ada550752277d94109438ac551a876e2eb137358cf01b0c2a2b5a73",
          "sha1": "2d249dd1fbf2d28e961322edd9efb1428998fa26",
          "md5": "31788b1e5d4605ad3a692ff071b974d5"
        }
      ]
    }
  ]
}
