{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1372197,
          "sha512": "96a7cfd838a1fc53e138b8afe60a2e9e93e4de227556b82a1db299b446de6daef10cdfec885285d96ad74bf6da4ae4542cd186a542b2a017d1863d4cecb71daf",
          "sha256": "503d12eb892ff0b295fd0b6563e08ff752eca1d665852f2149ba25dfb430a601",
          "sha1": "17d49848f11c799c0b92fa29275a3f66148104c2",
          "md5": "d01992078bf8b94e087baf99e606f485"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1372197,
          "sha512": "96a7cfd838a1fc53e138b8afe60a2e9e93e4de227556b82a1db299b446de6daef10cdfec885285d96ad74bf6da4ae4542cd186a542b2a017d1863d4cecb71daf",
          "sha256": "503d12eb892ff0b295fd0b6563e08ff752eca1d665852f2149ba25dfb430a601",
          "sha1": "17d49848f11c799c0b92fa29275a3f66148104c2",
          "md5": "d01992078bf8b94e087baf99e606f485"
        }
      ]
    }
  ]
}
