{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1371242,
          "sha512": "b1ff44da51ab39d190180533b49c5bcceff10972c29241cd61dc360e3836fc415c9a45d81327f1142675ae25e0ac7843a4eadebd2b2dc901abfcaf6a5cefc022",
          "sha256": "df94709d964a8ba4946331f2e866906b2673ac3fac7a0b487e5418f8c2778347",
          "sha1": "94f5094b733fb038caa4df751d12d292c4094ad6",
          "md5": "1a4d1c678e486658b59e7b8d39dba6ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1371242,
          "sha512": "b1ff44da51ab39d190180533b49c5bcceff10972c29241cd61dc360e3836fc415c9a45d81327f1142675ae25e0ac7843a4eadebd2b2dc901abfcaf6a5cefc022",
          "sha256": "df94709d964a8ba4946331f2e866906b2673ac3fac7a0b487e5418f8c2778347",
          "sha1": "94f5094b733fb038caa4df751d12d292c4094ad6",
          "md5": "1a4d1c678e486658b59e7b8d39dba6ad"
        }
      ]
    }
  ]
}
