{
  "formatVersion": "1.1",
  "component": {
    "group": "com.openosrs",
    "module": "runelite-api",
    "version": "4.32.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1367952,
          "sha512": "b883602ce935b63fca5193a8f42db68d1b0b3b387e1b376bf8e8e54ad21fb3665f0ba8d389c92a5a84014d1a851a2fb0b3af1e48f091f1aedacdc7a0c17edf64",
          "sha256": "43f8e179774a0939ae14164e74026a8335dcf6bbf0ea7fecdc8c63e8b1c3e82e",
          "sha1": "ca41836d5f03643e43af14490dad878e2f518fe6",
          "md5": "4c472a41a578ec4b071c8c884e0adeca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1.1-jre"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-text",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.32"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "22.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "runelite-api-4.32.0-SNAPSHOT.jar",
          "url": "runelite-api-4.32.0-SNAPSHOT.jar",
          "size": 1367952,
          "sha512": "b883602ce935b63fca5193a8f42db68d1b0b3b387e1b376bf8e8e54ad21fb3665f0ba8d389c92a5a84014d1a851a2fb0b3af1e48f091f1aedacdc7a0c17edf64",
          "sha256": "43f8e179774a0939ae14164e74026a8335dcf6bbf0ea7fecdc8c63e8b1c3e82e",
          "sha1": "ca41836d5f03643e43af14490dad878e2f518fe6",
          "md5": "4c472a41a578ec4b071c8c884e0adeca"
        }
      ]
    }
  ]
}
